### ISSUE TITLE
Disable report button when reports not available

### ISSUE THREAD

**Issue by allisonmuise** [Esri/crowdsource-manager#10]
Reports are not available when no features are selected and when multiple features are selected. Disable the Report button in these circumstances.

**Comment by allisonmuise** [comment]
To implement this change, please:

- Grey out and de-activate this button when multiple features or no features are selected
- Change tooltip for this button to say: 'View details for a single selected feature'
- Remove current browser messaging

**Comment by CTLocalGovTeam** [comment]
@allisonmuise 
OK.  We will implement this in the next release.

**Comment by allisonmuise** [comment]
verified
