### ISSUE TITLE
Popup content/editing panel

### ISSUE THREAD

**Issue by allisonmuise** [Esri/crowdsource-manager#101]
The first tab in the new Details panel, this tab will display the popup content as configured in the web map. Below the popup content display thumbnail links to non-image attachments (word docs, pdfs, etc)

This tab will always be present.

On layer load, no features will be selected so display a configurable message 'Select a feature to get started.' in the panel. This message should be editable through the app configuration panel. 

If the layer contains editable fields, display a method of toggling the view to editing mode. (I will send a photo of the UI)

In editing mode, a vertical list of editable fields replaces viewing mode content in the popup content panel. Editable fields are displayed based on their content type (drop downs for domains, value types are enforced, required values are enforced, date/time pickers for date fields, etc).

Below all fields are two buttons for saving/cancelling the edits. On save, edits are committed and the panel exits edit mode. On Cancel, edits are not committed and panel exits edit mode

When multiple features/records are selected, this panel automatically toggles to editing mode. If all selected features have the same value for an editable field, display that value, otherwise do not display a value for that field.
 
All changes are applied to all selected features. Display a confirmation/warning message when clicking Save in multi-feature editing mode indicating the number of features about the updated. 

On Save: commit edits, clear selection, and display the details of the most recently selected feature. On Cancel: discard edits, clear selection, and display the details of the most recently selected feature.

**Comment by allisonmuise** [comment]
![picture3](https://cloud.githubusercontent.com/assets/2752195/12792216/9b43b442-ca5f-11e5-88d0-8b32bde309b1.png)
![picture2](https://cloud.githubusercontent.com/assets/2752195/12792219/9d66d218-ca5f-11e5-9f94-9574e07b34d1.png)

see ppt sent via email for additional details re: styling

**Comment by CTLocalGovTeam** [comment]
@allisonmuise 
When attachments are enabled for a layer, and no 'non-image' attachments are available for a selected feature, do we display the 'Attachments' section title with the text 'No attachments found', OR
we don't display the 'Attachments' section title at all?

**Comment by allisonmuise** [comment]
@CTLocalGovTeam : Don't display the attachments section at all

**Comment by allisonmuise** [comment]
verified
