### ISSUE TITLE
Upgrading dependent static libraries

### ISSUE THREAD

**Issue by CTLocalGovTeam** [Esri/crowdsource-manager#104]
@allisonmuise ,

Considering all the new enhancements we are planning to do a complete revamp of CS Manager. We find various dependent static libraries like bootstrap, JQuery, etc., with reference to their old version. The following lists all the existing references against their latest versions: 

![image](https://cloud.githubusercontent.com/assets/2959186/12944864/f8a975f8-d00f-11e5-92cb-143b69e7c121.png)

Please let us know if we should upgrade these libraries.

**Comment by allisonmuise** [comment]
@CTLocalGovTeam : Yes, let's upgrade these libraries as part of this project.
