### ISSUE TITLE
Using third party table sorting plugin for sorting fields in the table

### ISSUE THREAD

**Issue by CTLocalGovTeam** [Esri/crowdsource-manager#106]
@allisonmuise 
As recommended in the mockups, we are using the bootstrap bordered table with calcite css overrides for displaying the feature layer table. In order to implement sorting functionality, we need to use a third party plugin and propose to use this [jQuery TableSorter](http://tablesorter.com/docs/) plugin that we can integrate with. 
Please let us know if we can go ahead and use this.

**Comment by allisonmuise** [comment]
@CTLocalGovTeam : Please discuss on the call this AM

**Comment by allisonmuise** [comment]
go ahead with this plugin

**Comment by allisonmuise** [comment]
verified
