### ISSUE TITLE
Approach for displaying default basemap of the Org on initial load

### ISSUE THREAD

**Issue by CTLocalGovTeam** [Esri/crowdsource-manager#107]
@allisonmuise 
On initial load, before user selects a layer to load, the map needs to display the default basemap of the Org. To implement this, our initial thought was to load this from the `defaultbasemap` property in Org properties. 
![image](https://cloud.githubusercontent.com/assets/2959186/13283032/dadc830a-db11-11e5-935e-1c7a8d80b0d9.png)

Is it ok to safely assume that the `baseMapLayers` in `defaultbasemap` will always be a list of tiled map services? If other kinds of layers are expected, then we will need to handle loading each type of layer separately. 

An alternative to this, is to query the basemap group configured at the Org to get all webmaps and load the first webmap as the basemap. We feel this is a more straightforward way as compared to the above approach. 
![image](https://cloud.githubusercontent.com/assets/2959186/13283183/9505496a-db12-11e5-8c9f-7daa1da35567.png)

Please let us know your thoughts.

**Comment by allisonmuise** [comment]
@CTLocalGovTeam : Please use the second approach. The goal is just to show something in that space before the user begins work, so let's go with the more straightforward approach.

**Comment by allisonmuise** [comment]
verified
