### ISSUE TITLE
Remove Sign-in button and associated code

### ISSUE THREAD

**Issue by CTLocalGovTeam** [Esri/crowdsource-manager#109]
@allisonmuise 
Since authentication will now be handled at the app item level by making it private/public, 
* Do we need to show the user name when a user logs in? Sign-in can be triggered by the app-item or a map-item.
* If we don't display the username, how does the user sign out?
* If user is already signed in another tab, the app should auto-sign in. Correct?
* Do we also remove code written to handle the sign-in process and private/public group cases?

**Comment by allisonmuise** [comment]
Let's leave the sign in button
