### ISSUE TITLE
Add records count to UI

### ISSUE THREAD

**Issue by allisonmuise** [Esri/crowdsource-manager#115]
Add the number of records currently in the table to the UI - upper right corner of the table?

**Comment by CTLocalGovTeam** [comment]
@allisonmuise 
This is not implemented yet. If you'd like us to implement this, please let us know. We are thinking of a label "No of records: 28" at the upper right corner of the table.

**Comment by allisonmuise** [comment]
Yes, please

**Comment by CTLocalGovTeam** [comment]
@allisonmuise ,

We have implemented this in last [Merge Request](https://github.com/Esri/crowdsource-manager/pull/127)

Please check this fix also.

-- Pratik Gohil

**Comment by allisonmuise** [comment]
verified
