### ISSUE TITLE
Add item counts to details tabs

### ISSUE THREAD

**Issue by allisonmuise** [Esri/crowdsource-manager#116]
Add the number of related records to the title of the related records tab, and the number of media items (attached photos & popup media) to the title of the media tab.

**Comment by CTLocalGovTeam** [comment]
@allisonmuise 
As discussed, displaying the number of media items is not required in current release.
Displaying the number of related records is implemented.

**Comment by allisonmuise** [comment]
This is correct. Thanks.

**Comment by allisonmuise** [comment]
Related record count button should be in theme color

**Comment by CTLocalGovTeam** [comment]
@allisonmuise ,

Accidentally, this issue was tagged in the last [Merge Request](https://github.com/Esri/crowdsource-manager/pull/127).
We are analyzing the recent change request of this issue, and will update you on this.

--Pratik Gohil

**Comment by allisonmuise** [comment]
verified
