### ISSUE TITLE
Display icons for non-image attachments

### ISSUE THREAD

**Issue by CTLocalGovTeam** [Esri/crowdsource-manager#119]
@allisonmuise 

We are thinking of displaying the file extension in uppercase, overlaid on top of the existing icon. This way, we will be able to support all kinds of file types and eliminate the need to maintain and display icons only for major file types.

Please let us know if this is ok.

![image](https://cloud.githubusercontent.com/assets/2959186/13836855/d5828b68-ebc2-11e5-9189-806c0f0c43b0.png)

**Comment by allisonmuise** [comment]
Yes, that works for me.

**Comment by CTLocalGovTeam** [comment]
@allisonmuise 

Here is the screenshot of scenario were user hovers the non image attachment(see first attachment). Since we have less space to show the document name, we will show ellipsis if name is too long.

![img1](https://cloud.githubusercontent.com/assets/2959186/13850239/1a4967fa-ec7f-11e5-83ef-45207d37054f.png)

**Comment by allisonmuise** [comment]
:+1:

**Comment by CTLocalGovTeam** [comment]
@allisonmuise ,

We have implemented this in last [Merge Request](https://github.com/Esri/crowdsource-manager/pull/126)

Please check this fix also.

-- Pratik Gohil

**Comment by allisonmuise** [comment]
verified
