### ISSUE TITLE
Question: Icon size of App header in tablets/Ipad

### ISSUE THREAD

**Issue by CTLocalGovTeam** [Esri/crowdsource-manager#122]
@allisonmuise   
We had a question regarding the icons size in app header for Ipad/tablets.

In last version of Manager application, the icons size in app header in tablets (60px in  height) were slightly larger than the desktops browsers. (50 px in height). Inclusive to this, we think keeping the size of icons slightly larger will be easier to tap to open the widgets.

![img_0070](https://cloud.githubusercontent.com/assets/2959186/13986865/b7718ce2-f12a-11e5-8296-025845537a6a.PNG)

In current version, should we follow the same procedure or should we keep the size of icons consistent on both desktop and tablets. (50 px in height)

Kindly share your thoughts on this.

**Comment by allisonmuise** [comment]
Let's keep the icons in both environments at 20px, and keep the header height the same in both as well.

**Comment by allisonmuise** [comment]
verified
