### ISSUE TITLE
Mockup options for position of Help icon and Sign in button

### ISSUE THREAD

**Issue by CTLocalGovTeam** [Esri/crowdsource-manager#123]
@allisonmuise 

We mocked up the options to position the help icon and sign in button as discussed.

Please let us know you think about these.

![image](https://cloud.githubusercontent.com/assets/2959186/13990711/879f84cc-f0d2-11e5-9781-d29018472a1c.png)

![image](https://cloud.githubusercontent.com/assets/2959186/13990727/91943338-f0d2-11e5-9eac-789e09b91164.png)

![image](https://cloud.githubusercontent.com/assets/2959186/13990616/3e20c0d6-f0d2-11e5-80ac-37cc52c27ccb.png)

![image](https://cloud.githubusercontent.com/assets/2959186/13990625/445f63b2-f0d2-11e5-9fd9-bc030f14661b.png)

![image](https://cloud.githubusercontent.com/assets/2959186/13990739/9d0aa59e-f0d2-11e5-8b02-dd5c3800eb48.png)

**Comment by allisonmuise** [comment]
I like option 5. I like that help icon too!

**Comment by CTLocalGovTeam** [comment]
@allisonmuise ,

We have implemented this in last [Merge Request](https://github.com/Esri/crowdsource-manager/pull/126)

Please check this fix also.

-- Pratik Gohil

**Comment by allisonmuise** [comment]
verified
