### ISSUE TITLE
Unable to submit form if selected features having different values for required field

### ISSUE THREAD

**Issue by CTLocalGovTeam** [Esri/crowdsource-manager#124]
@allisonmuise 

In case of multiple feature selection, currently supported scenarios are- 

1. if selected features having same value for a field then, respective input field in popup form will be shown with field value.

2. if selected features having different values for a field then, respective input field in popup form will be shown with empty value. if user does not change its value and submit the form then, that value will not be updated for the selected features.

Scenario no 2 works properly if field is optional. But if field is required then user is not able to submit the form as it does not allow to validate the empty value for the required field. 
Hence for the required field, user have to enter the value to update the selected features.

Please let us know your thoughts.

-Varsha

**Comment by allisonmuise** [comment]
Is it possible to only validate form fields that have values? I can see many use cases where a field may be required and populated with an assortment of values that the user does not want to change. While that field in the form may be empty, that field in the data is not. 

For example, each feature may have a required field for the assignee. Many reports currently assigned to all workers are ready to be moved from one status to the next. I should be able to do this without updating the assignee field value.

**Comment by CTLocalGovTeam** [comment]
@allisonmuise ,

Yes, It is possible to only validate form fields that have values.

Popup-form behavior after incorporating above change in following scenarios :

1. If selected features having different value for a required field then,
     a. Empty value will be shown in respective input field.
    b. Without changing the value user will be able to submit the form without getting any validation error for the empty value of required field.

2. If selected features having same value for a required field then,
    a. Value will be shown in respective input field.
    b. If user sets the empty value for the field then validation error will be displayed and form will not be submitted.

Please confirm.

-Varsha

**Comment by allisonmuise** [comment]
@CTLocalGovTeam 
The behaviors above are correct.
Thanks Varsha

**Comment by allisonmuise** [comment]
verified
