### ISSUE TITLE
Approach used to display charts in media tab

### ISSUE THREAD

**Issue by CTLocalGovTeam** [Esri/crowdsource-manager#125]
To page through multiple charts in media panel, we use "_goToPrevMedia" and "_goToNextMedia" methods. This is the same as used in esri info window class internally. So Using these methods we are able to generate Charts dynamically on the click of 'next' and 'previous' arrow buttons in the Media tab.

We also verified that the above mentioned private method is available in ArcGIS JS API 3.13/3.14/3.15/3.16.

We wanted to confirm if it is alright to use these private methods.
- Garima Pandey

**Comment by allisonmuise** [comment]
@CTLocalGovTeam 
Yes Garima, go ahead.

**Comment by CTLocalGovTeam** [comment]
@allisonmuise ,

We have implemented this in last [Merge Request](https://github.com/Esri/crowdsource-manager/pull/126)

Please check this fix also.

-- Pratik Gohil

**Comment by allisonmuise** [comment]
verified
