### ISSUE TITLE
images with links have incorrectly built URLs

### ISSUE THREAD

**Issue by allisonmuise** [Esri/crowdsource-manager#129]
When an image is added to the popup with a URL in the Link parameter, clicking the image in the web map popup opens that URL. Clicking the image in Manager attempts to open the URL of the application with the link appended to the end.

For example:

An image is added to the popup with the following parameters:
![2016-04-13 2-48-35 pm](https://cloud.githubusercontent.com/assets/2752195/14510532/dad06ee4-0186-11e6-9f70-d7a2de5e8a79.png)

Viewing a popup with this image in the web map viewer, I can click that image:
![2016-04-13 2-49-42 pm](https://cloud.githubusercontent.com/assets/2752195/14510599/1a276818-0187-11e6-8a24-9a2b69496eb3.png)

and it opens http://www.esri.com/

Clicking that image in Manager:
![2016-04-13 2-51-24 pm](https://cloud.githubusercontent.com/assets/2752195/14510636/3fe47744-0187-11e6-8bcb-7f14d4adc06e.png)

Tries to open http://localgovtestdev.mapsdevext.arcgis.com/apps/CrowdsourceManager/esri.com

**Comment by CTLocalGovTeam** [comment]
@allisonmuise 
We remember seeing this issue on our side in early dev, but are unable to repro this anymore. The issue we had noticed that although the url is incorrect, the page loads correctly. 
On your side, is the page not loading at all?

**Comment by CTLocalGovTeam** [comment]
@allisonmuise,

We are unable to reproduce this issue at our side & in the app link shared by you ([App link] (http://localgovtestdev.mapsdevext.arcgis.com/apps/CrowdsourceManager/index.html?appid=612278df714841859acbfb5b1875e82f))

![url-link-issue](https://cloud.githubusercontent.com/assets/2959186/14554844/0449557e-030d-11e6-9d24-2f328f219ea8.gif)

Can you please share an app which replicates this issue ?

--Pratik Gohil

**Comment by allisonmuise** [comment]
I can no longer repro the issue on that app, either, so I'll close this issue
