### ISSUE TITLE
Expose image caption, title

### ISSUE THREAD

**Issue by allisonmuise** [Esri/crowdsource-manager#130]
Display image/chart title centered above graphic

Display image/chart caption centered below graphic. In cases where caption doesn't fit on one line, end with ellipsis and show full caption on hover.

**Comment by allisonmuise** [comment]
@CTLocalGovTeam : Could you evaluate this to see if it could be done for the 4.2 milestone?

**Comment by CTLocalGovTeam** [comment]
@allisonmuise ,

We are planning to display image/chart title/caption as shown below. Title & Caption will be displayed in transparent bar & font style will be as per standard.

1.
![1](https://cloud.githubusercontent.com/assets/2959186/14600510/a91fc0a0-057a-11e6-921f-59b44ef3ac54.PNG)

2.
![2](https://cloud.githubusercontent.com/assets/2959186/14600539/ca45c89c-057a-11e6-91c9-ca1641f266ef.PNG)

3.
![3](https://cloud.githubusercontent.com/assets/2959186/14600545/cfa0c972-057a-11e6-98e8-5cc146038118.PNG)

4.
![4](https://cloud.githubusercontent.com/assets/2959186/14600550/d4c0341a-057a-11e6-90ba-f8a3743d8495.PNG)

5.
![5](https://cloud.githubusercontent.com/assets/2959186/14600555/dade17a4-057a-11e6-96c5-6660733ed1c5.PNG)

6.
![6](https://cloud.githubusercontent.com/assets/2959186/14600557/dfcdd04c-057a-11e6-9794-5095457eea5a.PNG)

Please confirm ?

--Pratik Gohil

**Comment by allisonmuise** [comment]
I don't like that this obscures part of the graphic. Is that information only shown on hover, or is it always visible?

**Comment by CTLocalGovTeam** [comment]
@allisonmuise We could do it either way. Displaying it on hover actually makes more sense as it doesn't obscure part of the graphic.

**Comment by allisonmuise** [comment]
Let's try with it displayed on hover

**Comment by allisonmuise** [comment]
verified
