### ISSUE TITLE
Image sizes in Media tab

### ISSUE THREAD

**Issue by allisonmuise** [Esri/crowdsource-manager#131]
The dimensions of the graphics shown in the media tab always seem to be the same as the thumbnail shown in the AGOL popup, even if the image is considerably larger and even if there is more room available on the Media tab.

The goal of this tab was to show larger than thumbnail images. Is it possible to fit the image to the size of the media tab space?

**Comment by CTLocalGovTeam** [comment]
We checked at our end and saw that media tab always displays the image as the thumbnail shown in AGOL irrespective of its larger dimensions.

We will implement the change here. Now if an image has larger dimensions, we will fit the image to the size of media tab without distorting the image.

**Comment by allisonmuise** [comment]
perfect. thanks!

**Comment by allisonmuise** [comment]
verified
