### ISSUE TITLE
Sorting text cut off

### ISSUE THREAD

**Issue by allisonmuise** [Esri/crowdsource-manager#134]
The hanging 'g's are cut off on each line of text. Can they be given an extra pt or 2 of space?

![2016-04-13 3-20-32 pm](https://cloud.githubusercontent.com/assets/2752195/14511288/486905a2-018b-11e6-9980-0cd4fb1d9747.png)

**Comment by CTLocalGovTeam** [comment]
Sure thing. We will implement this.

**Comment by allisonmuise** [comment]
verified
