### ISSUE TITLE
Add Search Capability

### ISSUE THREAD

**Issue by ldafner** [Esri/crowdsource-manager#137]
Would be helpful to be able to search on layers in map. So not just scrolling through requests or clicking on map to access information,  but being able to search by attributes/fields...
- name of person who contributed
- type of issue submitted
- etc.

**Comment by allisonmuise** [comment]
@ldafner This should work, already. Have you configured the search settings on the map? From the details page of the map in ArcGIS Online, edit the settings and scroll to near the bottom. You should be able to set the search up to search on those fields, and these settings should be reflected in the app. Let me know if this doesn't work for you.

**Comment by allisonmuise** [comment]
Also - in the next version we'll take it one step further and allow filtering based on the filter configurations in the map.

**Comment by allisonmuise** [comment]
closing. Let me know if this doesn't work for you and I'll re-open this issue.
