### ISSUE TITLE
add space in nls string for required fields

### ISSUE THREAD

**Issue by allisonmuise** [Esri/crowdsource-manager#138]

**Comment by allisonmuise** [comment]
Simply adding a space in the NLS files doesn't seem to resolve this. @CTLocalGovTeam  could you take a look? This refers to the '(required)' string that gets appended to the end of field aliases in the editing forms.

**Comment by CTLocalGovTeam** [comment]
@allisonmuise ,

We didn't get this, can you please elaborate what the issue is ?

--Pratik Gohil

**Comment by allisonmuise** [comment]
When a field does not accept null values, the string '(required)' is appended to the field alias in the geoform. Currently this is appearing without a space *field alias(required)* instead of *field alias (required)*. 

I tried adding a space before the ( in the nls files, but that didn't seem to fix the issue. Could you add the space wherever it needs to go?

**Comment by CTLocalGovTeam** [comment]
@allisonmuise ,

The _field alias & (required)_ text are 2 separate pieces of text, that is why adding a space in nls won't work. We can include a space between them while displaying in the form.

The fix for this will be included in the next code drop.

--Pratik Gohil

**Comment by allisonmuise** [comment]
verified
