### ISSUE TITLE
Help optional?

### ISSUE THREAD

**Issue by allisonmuise** [Esri/crowdsource-manager#141]
@CTLocalGovTeam 

I know it's late in the dev process, so please tell me if this can't be done without jeopardizing the current delivery schedules for this and other apps:

Would it be possible to add a configuration option for the appearance of the help widget? The current app doesn't have a help widget, so ideally users would have the option to opt-in to this new function. This would need an additional configuration parameter (off by default) which controls the appearance of the help icon in the app header. When help is disable, the other icons should shift to fill the empty space.

**Comment by CTLocalGovTeam** [comment]
@allisonmuise ,

Yes, we can implement this without affecting other projects, however we would need 2 more days to deliver manager app.

--Pratik Gohil

**Comment by allisonmuise** [comment]
@CTLocalGovTeam 
Thanks, let's go ahead with this change. Sorry for not catching it earlier!

-Allison

**Comment by allisonmuise** [comment]
verified
