### ISSUE TITLE
Issue with feature layer when labels are added to it.

### ISSUE THREAD

**Issue by CTLocalGovTeam** [Esri/crowdsource-manager#143]
@allisonmuise ,

We have came across following issue with feature layer when labels are added to it.

Consider operational layer(with labels) is selected in webmap(its feature & labels gets displayed on map).

Issue 1:
When second operational layer(with labels) is selected in webmap, labels of previous selected operational layer is not removed.

Issue 2:
When feature is edited using popup, its value gets updated but label does not reflect the updated value.

--Pratik Gohil

**Comment by allisonmuise** [comment]
verified
