### ISSUE TITLE
time filter doesn't show all features when enableFilter is False

### ISSUE THREAD

**Issue by allisonmuise** [Esri/crowdsource-manager#146]
The time filter should also allow all features to load when enableFilter is False, either by setting the two handles to the widest range ont he time slider or by setting the single handle tot he position that will load all features.

**Comment by CTLocalGovTeam** [comment]
@allisonmuise ,

When enableFilter is False, we are setting the time-slider as you have suggested. 

Case 1 : (1 handle)
Handle will be moved to the end of the time-slider.

Case 2 : (2 handles)
Second handle will be moved to the end of the time-slider.

We have implemented this and will deliver it in the upcoming build. 

--Pratik Gohil

**Comment by CTLocalGovTeam** [comment]
@allisonmuise 
Just to confirm, the filtering piece in Manager only deals with filters which ask for values.
The time slider is actually not a filter within the app's context while still behaving like a filter.

Then there are filters which do not ask for values. These will always be honored regardless of enableFilter is False/True. Correct?

**Comment by allisonmuise** [comment]
Correct

**Comment by allisonmuise** [comment]
verified
