### ISSUE TITLE
Time values do not show when editing features

### ISSUE THREAD

**Issue by ScottOppmann** [Esri/crowdsource-manager#147]
When you configure time on a date field and attempt to edit a feature in Manager, the data picker shows but doesn't allow you to specify a time.  Date picker should allow users to specify a time much like crowdsource-reporter does now.

@allisonmuise - Would like to resolve prior to UC 2016 release.

**Comment by allisonmuise** [comment]
@CTLocalGovTeam : Could you look at the LOE to do this?

**Comment by allisonmuise** [comment]
verified
