### ISSUE TITLE
Enhancement - Ability to select multiple records on map

### ISSUE THREAD

**Issue by MikeMillerGIS** [Esri/crowdsource-manager#150]
Currently you can hold the control key and add to selection, but with stacked data, I am not able to get all the points at a location

Example:
![image](https://cloud.githubusercontent.com/assets/2707285/15368716/3f419664-1cfd-11e6-8d2d-296e8e2a2261.png)

@allisonmuise

**Comment by CTLocalGovTeam** [comment]
@MikeMillerGIS , @allisonmuise ,

We have implemented multiple selection for stacked point data which can be delivered on Monday.

Do we also need to support polyline & polygon stacked selection ?

--Pratik Gohil

**Comment by MikeMillerGIS** [comment]
for consistency, I would say yes, but I will defer to @allisonmuise

**Comment by allisonmuise** [comment]
@CTLocalGovTeam : Please hold on further development work on this. Can you describe the action for selecting multiple points how you have it currently implemented? How significant are the changes to the code? (trying to assess risk for including this post-code freeze and mid-testing)

**Comment by allisonmuise** [comment]
@CTLocalGovTeam : Please do not deliver this change. I am putting it in the queue for the next release.

**Comment by allisonmuise** [comment]
@CTLocalGovTeam : Please share the approach you are considering as I want to confirm that it will be intuitive for the audience, without conflicting with actions used elsewhere in the software.

**Comment by CTLocalGovTeam** [comment]
@allisonmuise , @MikeMillerGIS 

We are considering below approach for multiple selection in different cases

Case 1 : Selection of multiple polygon
a. When polygon feature is selected on map, if there are stacked polygon features then multiple(stacked) features will be selected as show below

![selecting multiple feature polygon](https://cloud.githubusercontent.com/assets/2959186/16799080/bb44a324-490c-11e6-95da-4287fe5a94c9.gif)

Case 2 : De-selection of multiple polygon
a. When selected stacked polygon features are de-selected  on map, then stacked features will be de-selected as shown below
![deselecting multiple feature polygon](https://cloud.githubusercontent.com/assets/2959186/16799161/07d04cf2-490d-11e6-9ca5-e5ad7398364d.gif)

Case 3 : Selection of multiple points
a. When point feature is selected on map, if there are stacked point features then multiple(stacked) features will be selected as show below
![selecting multiple feature points](https://cloud.githubusercontent.com/assets/2959186/16799204/3d9ca16e-490d-11e6-9ff5-c000d68d02cb.gif)

Case 4 : De-selection of multiple points
a. When user tries to de-select stacked point feature on map, then stacked features will be de-selected as shown below
![deselecting multiple feature points](https://cloud.githubusercontent.com/assets/2959186/16799230/62754702-490d-11e6-8c3c-5abc5a8d7659.gif)

Case 5 : Single feature selection & stacked feature selection using CTRL key
a. When single polygon & stacked polygon feature is selected, then both single feature & stacked features will be selected as shown below
![selecting multiple feature polygon and single selection](https://cloud.githubusercontent.com/assets/2959186/16799373/3234613a-490e-11e6-96f0-c09f3465f1f4.gif)

Case 6 : When single feature & stacked features is selected using CTRL key & after that CTRL key is removed and mouse is clicked on selected stacked features, then rest of feature will be de-selected & stacked features on which mouse is clicked will be selected. This case works in similar manner as single selection works. 
![selecting the selected stacked polygon feature](https://cloud.githubusercontent.com/assets/2959186/16799720/d233aa32-490f-11e6-895e-ab8b41a1d320.gif)

Case 7 : Selecting stacked features on map & after that selecting single feature from grid
a. When stacked features is selected from map & after that single feature is selected from grid, then all the feature will be de-selected & only that feature will be selected as shown below
![selecting records from grid after stacked feature selection](https://cloud.githubusercontent.com/assets/2959186/16800086/1ff405fe-4911-11e6-8c9f-0eb33985bee8.gif)

All above scenario will work same for polyline feature.

Please let us know your thoughts on this.

--Pratik Gohil

**Comment by MikeMillerGIS** [comment]
They all look good to me.  

Should we add a selected record count to the record count text in the top right?
1 selected / 9 records

**Comment by allisonmuise** [comment]
@CTLocalGovTeam : I agree with Mike. Looks good, but the indication of the number of selected features would be a nice enhancement.

**Comment by CTLocalGovTeam** [comment]
@allisonmuise , @MikeMillerGIS 

OK. We will implement this enhancement which displays number of selected features.

--Pratik Gohil

**Comment by allisonmuise** [comment]
verified
