### ISSUE TITLE
BUG-000099306 ArcGIS Online Crowdsource Manager App displays icon for attached files as .DOCX although the attached file type differs.

### ISSUE THREAD

**Issue by MikeMillerGIS** [Esri/crowdsource-manager#153]
![image](https://cloud.githubusercontent.com/assets/2707285/15369557/2339d6bc-1d01-11e6-91ba-e84048919afd.png)
![image](https://cloud.githubusercontent.com/assets/2707285/15369565/2eeb0940-1d01-11e6-869b-de1b93724533.png)

**Comment by CTLocalGovTeam** [comment]
@allisonmuise, @MikeMillerGIS, @ScottOppmann 

We are analysing this issue and will keep you updated.

--Pratik Gohil

**Comment by CTLocalGovTeam** [comment]
@allisonmuise , @MikeMillerGIS , @ScottOppmann 

As per CrowdSource Manager ticket [#154](https://github.com/Esri/crowdsource-manager/issues/154) we will be displaying all .mp4 attachments in the media panel.

Do we still need to show the same .mp4 attachment in the popup tab?

--Pratik Gohil

**Comment by allisonmuise** [comment]
No, please don't display mp4 attachments on the popup tab

**Comment by allisonmuise** [comment]
zipped folders are also displaying with the docx icon

**Comment by allisonmuise** [comment]
templates report #1329

**Comment by CTLocalGovTeam** [comment]
@allisonmuise,

We are analysing this issue and will keep you updated.

--Pratik Gohil

**Comment by CTLocalGovTeam** [comment]
@allisonmuise 
This was occurring due to a minor error in code. We had a question while fixing this. 

What do we display if the file does not have any extension? 
Currently, it displays ".ZIP" which we feel is inaccurate. We think we should just display "FILE" if the attachment does not have any file extension. Please confirm.

**Comment by allisonmuise** [comment]
@CTLocalGovTeam Other than ZIP, what cases would cause a file not to have an extension?

**Comment by CTLocalGovTeam** [comment]
@allisonmuise,
Whenever a file is uploaded without any file extension, it will be displayed as "FILE", whereas currently it displays ".ZIP". The file may not have an extension either due to user error while creating the file or the extension can be manually removed from the file name.

**Comment by allisonmuise** [comment]
verified
