### ISSUE TITLE
Labelling uneditable layers

### ISSUE THREAD

**Issue by allisonmuise** [Esri/crowdsource-manager#160]
When an editable (to Manager) layer has labels, both the features and the labels draw as expected.

When an uneditable layer has labels, only the labels draw. 

Uneditable layers are:
- Map services
- layers with no editable fields
- layers with editing disable
- services without editing capabilities
- layers without popups (untested #158 )

**Comment by CTLocalGovTeam** [comment]
@allisonmuise ,

We are investigating this issue & will post an update soon.

--Pratik Gohil

**Comment by CTLocalGovTeam** [comment]
@allisonmuise ,

We have fixed issue for below uneditable layer

- Map services
- layers with no editable fields
- layers with editing disable
- services without editing capabilities
- layers without popups (untested #158 ) (Will be implemented in AGOL 4.3)

--Pratik Gohil

**Comment by allisonmuise** [comment]
verified
