### ISSUE TITLE
Labels occaisionally draw under their features

### ISSUE THREAD

**Issue by allisonmuise** [Esri/crowdsource-manager#161]
Labels should always draw above all features to be consistent with AGOL.
(noticed with polygon layers)

**Comment by allisonmuise** [comment]
@CTLocalGovTeam : This can be moved to 4.3 if high LOE or high risk change. Please let me know.

**Comment by CTLocalGovTeam** [comment]
@allisonmuise ,

This is a low LOE & low risk change. We can include this in the next code drop.

--Pratik Gohil

**Comment by allisonmuise** [comment]
verified
