### ISSUE TITLE
Issue with types having multiple domains for the same field per type

### ISSUE THREAD

**Issue by CTLocalGovTeam** [Esri/crowdsource-manager#162]
@allisonmuise 

We have discovered an issue with a specific case where types are defined in the feature layer and based on the type, there are different domains applied to another field.

For e.g., type field is COUNTY and city field has multiple domains containing city names based on the county name as shown in the graphic below.

![image](https://cloud.githubusercontent.com/assets/2959186/15536260/3072f9b6-228e-11e6-8231-679406eb5807.png)

When you are setting up a filter in ArcGIS webmap it shows up like this.
The values are grouped together based on common codes.

![image](https://cloud.githubusercontent.com/assets/2959186/15536286/52722294-228e-11e6-8991-f8c920c9299c.png)

The app displays all codes in the filter instead of their descriptions in this case. The geoform works correctly and handles this case.

![image](https://cloud.githubusercontent.com/assets/2959186/15536519/458ae678-228f-11e6-915a-efa8db5d3d93.png)

This scenario is not handled in the app and needs to be implemented the same way it works in ArcGIS MapViewer. It should display a comma separated list of values.

This is a medium LOE and medium risk fix. 

Please let us know your thoughts on this.

**Comment by CTLocalGovTeam** [comment]
@allisonmuise, @ScottOppmann 

We'll fix this issue and will keep you updated.

--Pratik Gohil

**Comment by allisonmuise** [comment]
verified
