### ISSUE TITLE
Unable to remove a filter when there are no records due to other filters

### ISSUE THREAD

**Issue by CTLocalGovTeam** [Esri/crowdsource-manager#163]
@allisonmuise 

The following screenshot shows data in name and phone fields
![filter data](https://cloud.githubusercontent.com/assets/2959186/15751998/d4b30e4a-2909-11e6-9a25-82e3f68765f3.png)

Applied filters
![filter applied](https://cloud.githubusercontent.com/assets/2959186/15752041/f57b96ce-2909-11e6-9f4b-9550acc9970e.PNG)

As both filters result in zero records, when user tries to remove any one filter (name or phone) the app does not allow to remove it.
![image](https://cloud.githubusercontent.com/assets/2959186/15752108/3488050a-290a-11e6-8699-64024ea657fb.png)

This is because when we remove the filter (name) the app queries the records with the other filter (phones) which results in zero records. The app then reverts the filter (name) back to its original value assuming that zero records are due to incorrect value set in the selected filter. This means a user will not be able to remove any of these filters and see records. 

The solutions is a minor fix in the code which prevents reverting the filter in such a scenario. 

We would like your approval to include a fix for this in tomorrows delivery.

-Pratik

**Comment by allisonmuise** [comment]
@CTLocalGovTeam : Good catch! Yes, please include this fix.

**Comment by allisonmuise** [comment]
cc @skrishn

**Comment by allisonmuise** [comment]
verified
