### ISSUE TITLE
Design feedback

### ISSUE THREAD

**Issue by allisonmuise** [Esri/crowdsource-manager#170]
@CTLocalGovTeam : Minor enhancements requested by the design team:

1) The animation of the map/layer selection panel opening and collapsing should be twice as fast 
2) When the panel is open and the user clicks on close, the close button should remain fixed to the panel as is until the panel reaches the left edge of the screen. Then as the panel slides away the button can change from the close icon to the open icon.
3) Add a subtle drop shadow under the open panel

I realize these weren't included in the original quote so I can move to the next milestone if necessary.

**Comment by CTLocalGovTeam** [comment]
@allisonmuise

We are analysing this enhancement and will keep you updated.

--Pratik Gohil

**Comment by CTLocalGovTeam** [comment]
@allisonmuise,

We'll implement this enhancement and will keep you updated.

--Pratik Gohil

**Comment by CTLocalGovTeam** [comment]
@allisonmuise,

We have implemented above design as shown below. Animation value is changed from 1000ms to 500ms to increase its speed. 

![shadow](https://cloud.githubusercontent.com/assets/2959186/17920900/c605db30-69f4-11e6-82d4-e06fe14ec022.gif)

--Pratik Gohil

**Comment by allisonmuise** [comment]
verified
