### ISSUE TITLE
Next arrow in media panel needs extra clicks to complete carousel cycle

### ISSUE THREAD

**Issue by CTLocalGovTeam** [Esri/crowdsource-manager#171]
@allisonmuise ,

We have found below issue in our internal testing

Issue : Next arrow in media panel needs extra clicks to complete carousel cycle & display next arrow in disabled mode to indicate there are no further media.

Steps:
1. Consider total 6 images are added in popup media, in which 4 images are configured with valid URL & 2 image are configured with blank URL
2. Now, only 4 images should get displayed in media panel because its URL is present & its displayed correctly
3. But when we see 4th image in media panel ideally next arrow should be disabled because next 2 images do not have any URL. But in this case, next arrow remains enabled which gives impression that there are still more images. When we click, nothing happens & you need 2 empty clicks to display the next arrow in disabled state

Same is the case with chart when there is no data in any of the configured fields.

This needs some investigation & work to fix this.

--Pratik Gohil

**Comment by allisonmuise** [comment]
@CTLocalGovTeam : Please continue investigating and let's discuss on Wednesday. 

Fixing this will not be high priority for this release - Only if the cause is relatively easy to identify and the code changes are minor.

**Comment by allisonmuise** [comment]
verified
