### ISSUE TITLE
Video panel is not getting displayed initially in IE9

### ISSUE THREAD

**Issue by CTLocalGovTeam** [Esri/crowdsource-manager#172]
@allisonmuise ,

We have one known issue when we try to display video in media panel in IE9

Steps:
1. Configure video URL as value in one of the string field
2. When we open media panel in IE9, initially blank panel is displayed.
3. When we do left mouse click, nothing happens.
3. But, when we do right mouse click on it, video panel is displayed & works as expected

We are still investigating solution for this.

--Pratik Gohil

**Comment by allisonmuise** [comment]
@CTLocalGovTeam : Please let me know if IE9 can be accommodated easily, or if addressing this will require significant deviation from what the other browsers require.

**Comment by CTLocalGovTeam** [comment]
@allisonmuise ,

Sure, we will update you if any significant deviation is required to fix this.

--Pratik Gohil

**Comment by skrishn** [comment]
@allisonmuise verified.
