### ISSUE TITLE
Media panel displays images of last selected feature of previous layer

### ISSUE THREAD

**Issue by CTLocalGovTeam** [Esri/crowdsource-manager#173]
@allisonmuise,

We have found below issue in our internal testing, but its rarely re-producible

Issue : Sometimes popup media images of currently configured layer is not getting displayed in media panel
Steps:
1. Choose a webmap with more than 2 layers
2. Configure popup media of each layer with separate images & only configure chart for any 1 of the layer
3. Click on feature for one of the layer, its popup images gets displayed in media panel correctly
4. Now, click on feature for another layer, observe that media panel still displays images of previous layer feature.

This issue is only with popup media, for feature attachments & field hyperlink it works fine.

We are investigating the solution for this.

--Pratik Gohil

**Comment by allisonmuise** [comment]
@CTLocalGovTeam : Please continue investigating and let's discuss on Wednesday.  In testing I saw this once also, but wasn't able to reproduce. 

Fixing this will not be high priority for this release - Only if the cause is relatively easy to identify and the code changes are minor.

**Comment by allisonmuise** [comment]
did not see this in testing
