### ISSUE TITLE
remove coloured badge from Comments tab

### ISSUE THREAD

**Issue by allisonmuise** [Esri/crowdsource-manager#175]
Instead of the coloured badge, please append (#) to the tab label, for example: Comments (52)
See the mockup for the Add Comment button sent via email.

(per feedback from David Dodge)

**Comment by CTLocalGovTeam** [comment]
@allisonmuise ,

Sure, we will implement this and keep you updated.

--Pratik Gohil

**Comment by allisonmuise** [comment]
verified
