### ISSUE TITLE
What controls the width of the columns in the table?

### ISSUE THREAD

**Issue by allisonmuise** [Esri/crowdsource-manager#176]
Is the width of the table columns controlled by the size of the field? What about fields that don't have set lengths, such as Floats? Is there a defined minimum width or max width?

**Comment by CTLocalGovTeam** [comment]
@allisonmuise,

> Is the width of the table columns controlled by the size of the field?


No, the width of the table columns is not controlled by the size of the field.

> What about fields that don't have set lengths, such as Floats?

When the name of the field exceeds the maximum width, it gets cut off. This behaviour is carried forward from previous version of manager application

> Is there a defined minimum width or max width?


Yes, there is a minimum & maximum width defined for each table column.

--Pratik Gohil

**Comment by allisonmuise** [comment]
@CTLocalGovTeam : Thanks for the info.
