### ISSUE TITLE
center select map text in grey space rather than on screen

### ISSUE THREAD

**Issue by allisonmuise** [Esri/crowdsource-manager#177]

**Comment by ScottOppmann** [comment]
@allisonmuise - we need to provide cybertech some more detail for this issue.

**Comment by CTLocalGovTeam** [comment]
@allisonmuise, @ScottOppmann 

We are analysing this enhancement as per the title of this ticket. We will keep to updated regarding our understandings on this.

--Pratik Gohil

**Comment by CTLocalGovTeam** [comment]
@allisonmuise , @ScottOppmann 

Is this the gray area you are referring to ? Would you like the select map text centered in this gray area ?

![image](https://cloud.githubusercontent.com/assets/2959186/17853523/9c7abddc-688a-11e6-8f76-744be62b8631.png)

--Pratik Gohil

**Comment by allisonmuise** [comment]
@CTLocalGovTeam Yes, that is correct

**Comment by allisonmuise** [comment]
verified
