### ISSUE TITLE
type error on feature load

### ISSUE THREAD

**Issue by allisonmuise** [Esri/crowdsource-manager#179]
When loading the details for a feature (load app>click on map>click on layer>select feature in table) I am seeing a type error in the console (TypeError: n is undefined).

I will send a repro URL via email.

**Comment by CTLocalGovTeam** [comment]
@allisonmuise,

We have analysed this issue & there are few observations which are listed below.

- Console error "TypeError: n is undefined" occurs only first time when we select feature in table. On second selection it works fine as shown below.

![1](https://cloud.githubusercontent.com/assets/2959186/17483053/2a03de5c-5da2-11e6-816c-a1d49b9e5433.gif)

- When we run this issue in chrome it displays this same error in console with different wording like "TypeError: Cannot read property 'relationships' of undefined" as shown below

![image](https://cloud.githubusercontent.com/assets/2959186/17483421/92a058ea-5da3-11e6-9b1f-b45d744e55ba.png)

- We have created a sample for this issue that just loads the webmap(Manager Map 1 in our case) & on it's feature click it displays its popup on left side of the screen. But, on click of the feature it shows error in console as shown below. Sample can be accessed [here](http://203.199.47.146/showRelatedRecordIssue.html) & arcgis reference from where sample is referred can be accessed [here](https://developers.arcgis.com/javascript/3/jssamples/popup_sidepanel.html)

![2](https://cloud.githubusercontent.com/assets/2959186/17483322/2b451c1c-5da3-11e6-8795-b37afe52fa40.gif)

- This is when app tries to set the content for popup & the API internally is not able to find the relationships of the layer.

- We are still investigating this issue but from the initial observations it looks like an API issue

Please share your thoughts on this.

--Pratik Gohil

**Comment by allisonmuise** [comment]
@CTLocalGovTeam 

Do you see the same API issue with version 3.17, or is it only the dev 3.18 API that causes the problem?

**Comment by CTLocalGovTeam** [comment]
@allisonmuise ,

> Do you see the same API issue with version 3.17, or is it only the dev 3.18 API that causes the problem?

    Yes, we could see this problem in both 3.17 & dev 3.18 API

We further analysed this issue and found that when application is trying to get the InfoContent of feature, for the first time the InfoTemplate is empty and that's why API was failing to load its InfoContent.

So to fix this we updated the code to check if InfoTemplate is not found then set the InfoTemplate  using the layers popup info.

We are testing this at our end & will keep you updated.

--Pratik Gohil

**Comment by allisonmuise** [comment]
thanks!

**Comment by skrishn** [comment]
@allisonmuise verified
