### ISSUE TITLE
Use org extents to load initial basemap

### ISSUE THREAD

**Issue by allisonmuise** [Esri/crowdsource-manager#183]
When app loads a basemap is loaded into the map pane. Load this basemap using the org extents instead of loading it to a global scale.

**Comment by allisonmuise** [comment]
@CTLocalGovTeam : This still seems to be loading to a global scale.

**Comment by CTLocalGovTeam** [comment]
@allisonmuise,

We are not able to reproduce this issue at our end. Could you please share the app url so that it could help us in analysing it.

--Pratik Gohil

**Comment by allisonmuise** [comment]
@CTLocalGovTeam 

Repro URL sent via email. The behaviors I expect are:

-	The map should show me just the basemap (no data) as it does in the currently-released version
-	The map should be zoomed to the extents defined in the organization (in this org that should be eastern Canada)

This can be addressed after Feb 1st to accommodate other projects.

**Comment by allisonmuise** [comment]
verified
