### ISSUE TITLE
configured favicon is orverwritten with app logo

### ISSUE THREAD

**Issue by allisonmuise** [Esri/crowdsource-manager#184]
browser tab displays miniaturized version of the app logo, even when a different favicon is specified in the app configuration.

@CTLocalGovTeam : can you fix this for 4.3?

**Comment by CTLocalGovTeam** [comment]
@allisonmuise,

We are analysing this enhancement and will keep you updated.

--Pratik Gohil

**Comment by skrishn** [comment]
@allisonmuise verified
