### ISSUE TITLE
"Edits could not be saved." error

### ISSUE THREAD

**Issue by MKellyEsri** [Esri/crowdsource-manager#185]
When editing related records I am getting an "Edits could not be saved" error. Is there a particular format the geodatabase/feature service has to be setup for these updates to work?

![image](https://cloud.githubusercontent.com/assets/9192183/17850964/91d76b60-6857-11e6-9922-cd7964469c60.png)

I have added a GlobalID to a point feature class, and am using this as a parent record in the table (in a Guid field). I set it up as a 1-m composite relationship.

The following is the message I see when looking at the network traffic:

![image](https://cloud.githubusercontent.com/assets/9192183/17851033/f45f93ac-6857-11e6-84e0-718939879e7c.png)

The UPDATE statement conflicted with the FOREIGN KEY constraint "REL_FK_SOCIALHOUSING_HOUSINGPROJECTS2_0". The conflict occurred in database "db_115", table "user_115.SOCIALHOUSING_HOUSING_PROJECT_LOCATIONS2", column 'GlobalID'. ↵The statement has been terminated.

The following is the request being sent:

![image](https://cloud.githubusercontent.com/assets/9192183/17851081/203f7d0c-6858-11e6-83a1-174b1af9fc63.png)

Edits can be made through Collector and viewed, but can't be edited through the Crowdsource Manager.

You can find an example application [here](http://esriireland.maps.arcgis.com/apps/CrowdsourceManager/index.html?appid=95ef1f953dbb4d459c98cf1bbac034cb), associated webmap [here](http://esriireland.maps.arcgis.com/home/webmap/viewer.html?webmap=715d73ca4e6141ebb458351139077c8f) and original file geodatabase [here](http://esriireland.maps.arcgis.com/home/item.html?id=5beabdaa09e54f958dc48d1f2ce1b988). Just click on any of the points and try edit the related records.

If I manually make the same request via Rest but remove the Guid attribute the update goes through as expected. If I remove the Guid as an editable attribute in the webmap, it is still passed through in the update. Any thoughts appreciated!

**Comment by allisonmuise** [comment]
@MKellyEsri : Please contact Esri Support Services for help with this. They will be able to walk you through the troubleshooting steps to identify why this message is appearing.

**Comment by MKellyEsri** [comment]
Thanks Allison I'll do that.

**Comment by MKellyEsri** [comment]
Just in case anyone comes across this, the problem was happening because Global ID's were enabled on the related table (so there was a ParentGuid field for the relate, as well as a GlobalId field to uniquely identify each row in the table). Once you don't enable Global ID's on the related table, the edits go through as expected.

**Comment by allisonmuise** [comment]
@MKellyEsri Thanks for following up! That's good to know. I'll get the developers to take a look at this for a future release, too.

**Comment by MKellyEsri** [comment]
FYI it's logged as Esri Support Case #01821589

**Comment by allisonmuise** [comment]
duplicate #196
