### ISSUE TITLE
add basemap widget

### ISSUE THREAD

**Issue by allisonmuise** [Esri/crowdsource-manager#189]
when collecting feedback in remote areas, a combination of aerial imagery and topo maps may be required to find the correct location. Currently the app only supports one basemap.

**Comment by allisonmuise** [comment]
I suggest starting with the button graphic from Basic Viewer. This button could sit in line with the navigation widgets on the left side of the map. Clicking the widget would expand a panel (like the search does) containing the basemap options. This panel should be styled to fit in with Manager. Do not use the same styling from Basic Viewer.

**Comment by CTLocalGovTeam** [comment]
@allisonmuise,

Following are the screenshots of the basemap gallery in the different scenarios, depending on the availability of the area.

**Case1: Scroll handle at extreme top**
![image](https://user-images.githubusercontent.com/2959186/30797128-7d14c2e2-a1f2-11e7-8361-30425204d0e2.png)

**Case2: Scroll handle at the center**
![image](https://user-images.githubusercontent.com/2959186/30797136-82aa4150-a1f2-11e7-9006-d71c5ffedd17.png)

**Case3: Scroll handle at the extreme bottom**
![image](https://user-images.githubusercontent.com/2959186/30797140-8623aec0-a1f2-11e7-9e78-fc41e5e18219.png)

Please confirm, should we go ahead with this implementation?




--Pratik Gohil

**Comment by allisonmuise** [comment]
I'm ok with case 1 & case 2, but I don't like case 3. What are the alternatives for this? Can we automatically expand that window? Is there another way to display that widget when it doesn't fit in the available space?

How does browser size impact all three scenarios?

**Comment by CTLocalGovTeam** [comment]
@allisonmuise,

> I'm ok with case 1 & case 2, but I don't like case 3. 

We could handle case 3 as shown below
![image](https://user-images.githubusercontent.com/2959186/30853388-4b9b3f2c-a2cc-11e7-8fb5-216ba6eea22d.png)

> What are the alternatives for this?

We could consider different alternatives as described below

Alternate approach 1:
![image](https://user-images.githubusercontent.com/2959186/30848716-981bc0c4-a2bd-11e7-875a-f423b2cd0deb.png)
![image](https://user-images.githubusercontent.com/2959186/30848727-a467b5f4-a2bd-11e7-8dbe-e25258c80c5c.png)



Alternate approach 2:
![image](https://user-images.githubusercontent.com/2959186/30853512-a708c6d6-a2cc-11e7-8870-22be4c49bc9b.png)

Please share your thoughts on this.


--Pratik Gohil

**Comment by allisonmuise** [comment]
I think Approach 1 (always opens in center) will allow for the most consistent behavior, regardless of screen size or layout, so let's proceed with that.

**Comment by CTLocalGovTeam** [comment]
@allisonmuise,

We are planning to implement the further functionalities listed below similar to
[Crowdsource Reporter Basemap Gallery Comment](https://github.com/Esri/crowdsource-reporter/issues/226#issuecomment-331868863)
1. Adding a new configuration parameter for selecting a basemap group(default would be empty). When no group is configured, app will fetch org's basemap group.
2. Closing the basemap gallery on selection
3. Displaying the selected basemap with a border

Please confirm?

--Pratik Gohil

**Comment by allisonmuise** [comment]
@CTLocalGovTeam Yes, this sounds good.

**Comment by allisonmuise** [comment]
@CTLocalGovTeam Could we make this configurable, and off by default?

**Comment by allisonmuise** [comment]
@CTLocalGovTeam  Could we add a bit of white space between the nav buttons and the basemap and legend buttons. I'd like the space between the basemap and legend buttons, as well.

**Comment by allisonmuise** [comment]
@CTLocalGovTeam  Could we add a bit of white space between the nav buttons and the basemap and legend buttons. I'd like the space between the basemap and legend buttons, as well.

**Comment by allisonmuise** [comment]
@CTLocalGovTeam  Could we add a bit of white space between the nav buttons and the basemap and legend buttons. I'd like the space between the basemap and legend buttons, as well.

**Comment by CTLocalGovTeam** [comment]
@allisonmuise,

Following is the screenshot after adding space between navigation, basemap and legend buttons.

![image](https://user-images.githubusercontent.com/2959186/32600479-bc98bab8-c565-11e7-891a-df7da233501b.png)


Please confirm should we implement this?

--Pratik Gohil

**Comment by allisonmuise** [comment]
@CTLocalGovTeam Yes! That is exactly what I had in mind. Thanks!

**Comment by allisonmuise** [comment]
verified

**Comment by skrishn** [comment]
@allisonmuise added testcase
