### ISSUE TITLE
Sign out doesn't work

### ISSUE THREAD

**Issue by allisonmuise** [Esri/crowdsource-manager#19]
after clicking 'sign out' the app should return the user to the sign in screen.
Currently, the app just reloads, and I'm still signed in.

**Comment by daFiter** [comment]
I am getting this same issue on the current version.

**Comment by allisonmuise** [comment]
@daFiter The app appears to be functioning as expected for me. Could you please describe in more detail what you are experiencing and how that differs from what you are expecting, including what browser you are using, the version, and exact steps to reproduce the issue? Screenshots would also help. Thanks.
