### ISSUE TITLE
 Display form hints as grey, italicized text above the parameters

### ISSUE THREAD

**Issue by allisonmuise** [Esri/crowdsource-manager#191]
Form hints are currently displayed below the parameter and looks slightly dissociated. The would be more helpful if they were above the parameter.

**Comment by CTLocalGovTeam** [comment]
@allisonmuise,

This ticket is not assigned to CT. Please confirm.

--Pratik Gohil

**Comment by allisonmuise** [comment]
@CTLocalGovTeam : apologies - it is now assigned.

**Comment by allisonmuise** [comment]
verified!
