### ISSUE TITLE
map panel wraps late

### ISSUE THREAD

**Issue by allisonmuise** [Esri/crowdsource-manager#192]
Maps with long names cause a scroll bar to appear, even though it looks like the text does eventually wrap. Text should wrap before a scroll bar is needed.
![9-7-2016 12-19-10 pm](https://cloud.githubusercontent.com/assets/2752195/18327955/acc32bec-7501-11e6-8617-f8c9133b0c89.png)

**Comment by CTLocalGovTeam** [comment]
@allisonmuise,

We are unable to reproduce this issue.

We tried to reproduce it by entering data in webmap & operational layer name in different formats as listed below.

> 1. Long text with no spaces

![image](https://cloud.githubusercontent.com/assets/2959186/20882168/b20abbf2-bb05-11e6-97c0-b877f3afc089.png)

> 2. Alphanumeric text followed by one single hyphen(-) followed by long text with no spaces

![image](https://cloud.githubusercontent.com/assets/2959186/20882326/60a1e5c8-bb06-11e6-85c4-b91580726254.png)

> 3. Exact text as shown in above image

![image](https://cloud.githubusercontent.com/assets/2959186/20882427/e7330b76-bb06-11e6-9a43-6efd2c34dd6b.png)

Could you please share the URL of the published application which contains this issue. It would be helpful to us.

--Pratik Gohil

**Comment by CTLocalGovTeam** [comment]
@allisonmuise,

As updated above we are not yet able to reproduce this please let us know how we should take it forward.

--Pratik Gohil

**Comment by allisonmuise** [comment]
@CTLocalGovTeam We were also unable to reproduce this issue last night. I'll close it for now, and reopen if we find another repro case.

**Comment by allisonmuise** [comment]
@CTLocalGovTeam - I'm sorry - I'd missed this comment. I'll update with a URL later today

**Comment by allisonmuise** [comment]
http://arcgis4localgov2.maps.arcgis.com/apps/CrowdsourceManager/index.html?appid=6b6341e04a42460595347a35fcdd0932

Note - I am only seeing this behavior in FireFox. I don't see it in Chrome.

**Comment by CTLocalGovTeam** [comment]
@allisonmuise,

For breaking the word we are using css property word-break : break-word which breaks word to another line & its working fine in the chrome. But, it seems that this property is not supported in Firefox & IE and hence scrollbar gets appear. However, we can use another css property word-break : break-all. But, by using this if there is single long word it will get break and distributed in 2 lines as shown below.

![image](https://cloud.githubusercontent.com/assets/2959186/22020384/fb9c7cca-dcdd-11e6-8b45-0eab3e21b0d9.png)

Please share your thoughts on this.

--Pratik Gohil

**Comment by allisonmuise** [comment]
@CTLocalGovTeam 
Pratik, I assume that if there was a space in there somewhere it would break at the space first and only split a word if there was no way to accommodate a word otherwise?

If so, let's use this. it is preferable to the scrollbar.

**Comment by allisonmuise** [comment]
@CTLocalGovTeam : Is this same css property used in Reporter? If so, I'll create a ticket in that repo as well.

**Comment by CTLocalGovTeam** [comment]
@allisonmuise,

By using css property word-break : break-all it will not break according to spaces but at character level.

- String containing 1 space in firefox using word-break : break-all property
![image](https://cloud.githubusercontent.com/assets/2959186/22053893/56ddc792-dd79-11e6-8ac3-9e4104a55302.png)


- String containing 1 space in chrome using word-break : break-all property
![image](https://cloud.githubusercontent.com/assets/2959186/22053871/40d60a5e-dd79-11e6-8a3e-fd8a96f0ec04.png)




- String containing multiple spaces in firefox using word-break : break-all property
![image](https://cloud.githubusercontent.com/assets/2959186/22059402/ab498dd4-dd92-11e6-98ec-71784dc8191c.png)


- String containing multiple spaces in chrome using word-break : break-all property
![image](https://cloud.githubusercontent.com/assets/2959186/22059385/9d5a7878-dd92-11e6-9dc3-b25c0f131169.png)





> Is this same css property used in Reporter? If so, I'll create a ticket in that repo as well.

    Yes


Please share your thoughts on this.





--Pratik Gohil

**Comment by allisonmuise** [comment]
@CTLocalGovTeam 
Thanks for the examples, Pratik. Given this information, I'm going to close this issue as a known limit that exists on specific browsers. Let's stick with the css property word-break: break-word.
