### ISSUE TITLE
BUG-000099365 Editing related records in the Crowdsource manager fails when global IDs are enabled on the related table as well as the feature class.

### ISSUE THREAD

**Issue by allisonmuise** [Esri/crowdsource-manager#196]
```
Create a point feature class and enable Global IDs on it.
Create a Table and add a GUID field
Enable GlobalIDs on the Table
Create a composite 1:M Relationship class using the globalID field from the points feature class and GUID field in the related table.
Publish to ArcGIS Online and add to the Crowdsource Manager Application.
Edit the related table, and see error "Edits could not be saved"
```

NOTES:

```
See video of error: http://screencast.com/t/pdOwk18bx4rT
File geodatabase to test with attached
Application to view behavior: http://ess.maps.arcgis.com/home/item.html?id=668872cb7cb64ef5bfe7b1d03f313127
```

Salesforce ID: BUG-000099365
Salesforce Submitter: Meg Hartel
Salesforce Submit Date: 9/15/2016 11:24 AM
Salesforce Bug Type: Failure/Error
Salesforce Severity: Medium
Repro Data: \esri.com\sf_filestore\PRD\Attachments\Defects\BUG-000099365
Work Around: (n/a)
Product: Configurable Web Apps
Functional Category: ArcGIS Online Application Templates
Client Platform: (n/a)
Version Found: N/A
Planned Version Fixed: (n/a)
Comment: (n/a)

**Comment by allisonmuise** [comment]
templates repo #1328

**Comment by allisonmuise** [comment]
repro app: http://arcgis4localgov2.maps.arcgis.com/apps/CrowdsourceManager/index.html?appid=a2ab069f85c74db594262c2a303ad604

**Comment by CTLocalGovTeam** [comment]
@allisonmuise,

We are analysing this issue and will keep you updated.

--Pratik Gohil

**Comment by allisonmuise** [comment]
The related table with the Global ID field is no longer being recognized. Previously I was receiving a message when attempting to commit an edit on a record; now I no longer get a tab for accessing the related records.

I will send a URL for a devext application via email.

**Comment by allisonmuise** [comment]
issue mentioned above is un-reproducible in latest devext build. closing issue.
