### ISSUE TITLE
Ability to add/remove report attachments.

### ISSUE THREAD

**Issue by etes** [Esri/crowdsource-manager#197]
Adding attachments to existing reports is critical for supplementing reports with supporting documents and files. Not all information and documents are submitted from the field.

It should also be possible to remove report attachments that are mistakenly uploaded or deemed inappropriate.

**Comment by allisonmuise** [comment]
You can currently add attachments as part of submitting related records in Manager. We deliberately don't allow editing of attachments on the original report in Manager. The idea behind this is that the originally submitted report should be preserved intact. 

That being said, in an upcoming release of Crowdsource Reporter we will be adding the ability for reporters to edit their own reports - including the attachments - and I can see a use for similar logic in Manager.

You mention dealing with innappropriate content as well. For this I suggest using the filter method discussed here: http://solutions.arcgis.com/local-government/help/crowdsource-reporter/get-started/create-layers/#moderate . I know this is the Reporter help, but the logic applies to Manager as well.

**Comment by etes** [comment]
Thanks for the clarification @allisonmuise. Editing attributes of a report from crowdsource manager is already allowed. 

So what's the deal with not allowing to add new attachments to that report? Besides an attachment is also an attribute of the report :).

**Comment by allisonmuise** [comment]
@etes: honestly - it not a workflow that we've heard is needed!

I agree - attachments are attributes, but unlike other attributes there isn't a way to track who has edited them or to restrict which ones can be manipulated and the organizations we worked with on the design of this app had a requirement to preserve the integrity of the initial report. 

To achieve this - The app manages the integrity of the other attributes by using the popup configuration to restrict access to fields. There isn't a way to do the same with attachments - they are either all editable or not with no way to distinguish between original and modified, or to hide rather than delete them. Limiting adding attachments to new related records gets around this a bit by associating new attachments with the original report while allowing some distinction between 'original' and 'added'.

Care to share your use case/workflow? You can reach me at amuise@esri.com.

**Comment by chris-fox** [comment]
@allisonmuise, received feedback on this in regards to our Homeless Activity Manager solution where the user wanted to be able to add or remove pictures from the original report.

**Comment by AndyPeepsJR** [comment]
Is there going to be any activity on this. I'm currently looking to use this to allow back office staff to moderate community contributions to historical environment records and have the need to edit attachments in some cases, and in others to tweak the location?

**Comment by allisonmuise** [comment]
@AndyPeepsJR - Yes, we are looking at allowing editing of attachments. It's not in our plans to allow geometry edits, though.

**Comment by pratikg** [comment]
@allisonmuise,

We are planning to implement this enhancement as described below.

**_Adding attachments in the popup tab:_**

1. We would be adding an attachment button to add the attachment, same as it appears in the comments tab in this application.

![image](https://user-images.githubusercontent.com/1454356/49573886-1f7b7d80-f965-11e8-9127-d2afc3edd17c.png)

2. The attachment would only be added in the feature once a user clicks on the save button.

**_Editing attachments in the popup tab:_**

1. The existing attachment will be displayed, in the same way as the reporter application.

![image](https://user-images.githubusercontent.com/1454356/49574354-45555200-f966-11e8-971a-2844f41c316e.png)

2. Any deleted attachment would be deleted from the layer only after the clicks on "Save" button, in the same way as the reporter application.

3. If the user deletes the attachment by clicking on the "cross" icon and then clicks on the cancel button, in this case, no attachment will be deleted, in the same way as the reporter application.

Should we proceed with the implementation?

While analysing this enhancement we came across below queries, please let us know how you would you like to handle this cases.

**_Case1: Allow Editing of Attachments in Comment sForm_**
Currently editing comment doesn't support editing its attachment. Do we need to support it? If Yes, its behaviour would be the same as described above.

![image](https://user-images.githubusercontent.com/1454356/49569182-3a47f500-f959-11e8-854c-a573ff0f3111.png)

**_Case2: Display all attachments in popup tab when Viewing/Editing the single feature_**
- As per our current implementation, attachment of type other than images(like .txt files etc..) are displayed in the popup tab.  Whereas, image attachments are displayed in the media tab. 
- To allow user Adding/Deleting the image attachments we need to display them in the popup tab also.
- In this case, When the user adds/deletes the image attachment the same needs to be updated in the media tab also.


**_Case4: Challenges in adding/deleting attachments when Multiple features are selected_**
How should we deal with the attachment when the user is editing multiple features? We are planning to hide the attachment section in this case and restrict that user to edit attachments only for single feature selection.

**Comment by allisonmuise** [comment]
@pratikg 

The described adding and editing workflows sound good.

Case1: Yes, please add the same functionality for the comments
Case2: Yes, the described modification is acceptable
Case4: I Agree that hiding the attachemnt section for batch editing makes the most sense

Please add  configuration option (off by default) that will allow users to control if they would like their application to support editing of attachments. All of the previously described scenarios (including displaying images on the details tab) should only be possible when the option is enabled.

**Comment by pratikg** [comment]
@allisonmuise,

Ok, we will be adding a configuration option "enableEditingAttachments". If it's set to true, all the above modifications will be applied. If it's set to false, an application will have no change.

**Comment by allisonmuise** [comment]
@pratikg Thanks!

**Comment by aparveen** [comment]
Verified in devext.

**Comment by skrishn** [comment]
added testcase
