### ISSUE TITLE
Honor filters on tables

### ISSUE THREAD

**Issue by allisonmuise** [Esri/crowdsource-manager#200]
@CTLocalGovTeam

Currently, the comments thread does not honor any filters that have been applied to the related table. What is the LOE to add this query when pulling in this content?

-A

**Comment by CTLocalGovTeam** [comment]
@allisonmuise,

This is LoE. We will be delivering it by the end of next week, since currently we are busy with other apps.

--Pratik Gohil

**Comment by allisonmuise** [comment]
@CTLocalGovTeam 
That's great! Thanks!

**Comment by allisonmuise** [comment]
verified
