### ISSUE TITLE
Apply org theming

### ISSUE THREAD

**Issue by allisonmuise** [Esri/crowdsource-manager#201]
Please manage work on this issue separate from work on other issues for 4.4.

Org-level theming options will be accessible in this JSON format:
{
header:{
background: "#337ab7",
text: "#fff"
},
body: {
background: "#FFF",
text: "#333"
},
button:{
background: "#D95F45",
text: "#333"
},
logo:{
small: "https://org.maps.arcgis.org/logo-small.png"
}
}

These options will be read in to the app and applied by the same mechanism that values from defaults.js are read in until alternate values are supplied in the configuration panel. This means that there may be a disconnect between what is shown in the config panel and the app's appearance. This is ok.

Schemas for the application of these options follow:

**Comment by allisonmuise** [comment]
![10-25-2016 3-33-40 pm](https://cloud.githubusercontent.com/assets/2752195/19706798/c539da9e-9ac8-11e6-8329-671042c82a88.png)

![10-25-2016 3-33-51 pm](https://cloud.githubusercontent.com/assets/2752195/19706801/c7eb80d0-9ac8-11e6-913a-cc82953112ef.png)

![10-25-2016 3-34-01 pm](https://cloud.githubusercontent.com/assets/2752195/19706804/c9b2060a-9ac8-11e6-8c86-f1cb2962a285.png)

![10-25-2016 3-34-09 pm](https://cloud.githubusercontent.com/assets/2752195/19706808/cb5c3534-9ac8-11e6-928e-bd1e4a6792ab.png)

![10-25-2016 3-34-16 pm](https://cloud.githubusercontent.com/assets/2752195/19706810/ccfd32bc-9ac8-11e6-8eef-3bcd7a38e95f.png)

![10-25-2016 3-34-27 pm](https://cloud.githubusercontent.com/assets/2752195/19706811/ce3c188c-9ac8-11e6-93cf-b50900851e32.png)

![10-25-2016 3-34-39 pm](https://cloud.githubusercontent.com/assets/2752195/19706813/cf904794-9ac8-11e6-8c79-0c3503b76c4e.png)

![10-25-2016 3-34-47 pm](https://cloud.githubusercontent.com/assets/2752195/19706819/d2d17e82-9ac8-11e6-96d3-601c2c768908.png)

![10-25-2016 3-34-57 pm](https://cloud.githubusercontent.com/assets/2752195/19706820/d4f69ac6-9ac8-11e6-9719-63b6be90c668.png)

![10-25-2016 3-35-08 pm](https://cloud.githubusercontent.com/assets/2752195/19706823/d688712a-9ac8-11e6-8e4d-f15cc008eedb.png)

![10-25-2016 3-35-14 pm](https://cloud.githubusercontent.com/assets/2752195/19706824/d7fdd66c-9ac8-11e6-8265-e31fefd4beb7.png)

**Comment by allisonmuise** [comment]
@CTLocalGovTeam CLARIFICATION:

The logo mentioned in the JSON will point to the application logo, NOT the favicon as indicated in the mockups. When a logo is specified at this level it will override the current logic for this logo. When no logo is specified, the app should use the current logic for finding a graphic for this space.

**Comment by allisonmuise** [comment]
As mentioned in this morning's meeting, the help icon is missing from the mockups. The portions of the help icon that are currently white should take on the header text color, and the portions of the icon that match the header background color should continue to take on the header background color.

**Comment by CTLocalGovTeam** [comment]
@allisonmuise,

As discussed on the weekly status call Info tab will be having same styling as comments tab.

--Pratik Gohil

**Comment by CTLocalGovTeam** [comment]
@allisonmuise,


Could you please provide which section of the org theming would be applied for below areas

![image](https://cloud.githubusercontent.com/assets/2959186/20176604/99d85ea4-a76e-11e6-889f-ec20672456d4.png)

--Pratik Gohil

**Comment by CTLocalGovTeam** [comment]
@allisonmuise 

Will existing apps automatically switch to the new theming pattern? or we provide them a configurable item to switch to the org theming pattern?

The config currently contains theme color, do we need to remove this item from configuration since we are switching to org theming?

-kedar

**Comment by allisonmuise** [comment]
@CTLocalGovTeam : 

The dropdown selection menu: what is shown in orange should be the header background color; what is shown in white should be the header text color.

Description panel: Text should be body text; background should be body background

The org themeing parameters will all need to be added to the configuration panel without losing backwards compatibility.

**Comment by allisonmuise** [comment]
Per AGOL team:

The config panel parameters will be connected to the org theming parameters by adding a sharedStyleProperty property to each of the affected parameters in the JSON. For example:

           {  
               "label":"Title logo:",
               "fieldName":"logo",
               "type":"string",
               "sharedStyleProperty":"logo.small",
               "tooltip":"Defaults to sample logo"
            },

**Comment by allisonmuise** [comment]
another change...the property name has been changed to SharedThemeProperty:
       {  
           "label":"Title logo:",
           "fieldName":"logo",
           "type":"string",
           "sharedThemeProperty":"logo.small",
           "tooltip":"Defaults to sample logo"
        },

Also - I sent Kedar credentials to access an organization that has the shared theme properties included in the org settings JSON.

**Comment by CTLocalGovTeam** [comment]
@allisonmuise,

As per discussion on the call, precedence of app logo would be as follows

![image](https://cloud.githubusercontent.com/assets/2959186/20301984/919b7ccc-ab4b-11e6-99fd-2ab7302a5b1c.png)

--Pratik Gohil

**Comment by allisonmuise** [comment]
close - the org/theme logo should take precedence over the group logo, though.
![11-15-2016 7-56-07 am](https://cloud.githubusercontent.com/assets/2752195/20312634/146f920c-ab09-11e6-9544-9d5e0e11ee26.png)
(note that the headers have been re-ordered)

**Comment by allisonmuise** [comment]
@CTLocalGovTeam : I confirmed with Kelly that by default the org theme parameters will be NULL.

**Comment by allisonmuise** [comment]
@CTLocalGovTeam : The calculate colors should not be configurable, or defined anywhere as explicit values as they are not part of the defined shared theming. These values should always be calculated from the shared theme values. 

Please remove these parameters from default.js.

**Comment by allisonmuise** [comment]
@CTLocalGovTeam 

Some (hopefully minor) changes based on what I have seen playing with various color schemes:

1) Please use the existing application color parameter for consuming the shared theme header background color. This is necessary for backwards compatibility. I can then link the existing parameter to the shared theme parameter.

2) The pull tab on the map selection panel would look better in the header color, not the calculated header color

3) Let's make the space under the table white

4) Let's try the background color of the panel the configured body background color instead of the calculated color

5) The color of the 'select a row' message that displays in the details space when no record is selected should be the body text color.

6) The bar at the top of the map selection panel that is currently showing the text color - let's make that the calculated body background color so that it blends in with the rest of the panel.

![1-25-2017 1-15-45 pm](https://cloud.githubusercontent.com/assets/2752195/22311549/c1560dca-e308-11e6-90c7-f7dd66b6b70c.png)

![1-25-2017 1-37-41 pm](https://cloud.githubusercontent.com/assets/2752195/22311550/c35259da-e308-11e6-99ac-749e17a90d13.png)

**Comment by allisonmuise** [comment]
additionally, as discussed on the call, let's swap the colors used in the map selection panel so that the major color is the configured body color, and the calculated color is only used for the header bar, on hover, for the map details, and to indicate the selected map & layer.

**Comment by allisonmuise** [comment]
The application logic should only read the values set in the configuration panel; there is no need for the app to handle any of the logic in deciding when org theme vs default vs configured values are used. The configuration panel will handle this logic.

**Comment by allisonmuise** [comment]
@CTLocalGovTeam : For backwards compatibility, the original 'theme' property must be used for the shared theme header.background property. The headerBackgroundColor should not be necessary.

Please make the necessary adjustments and submit a code drop ASAP.

Please copy Suba on this PR as I will be out of the office next week.

cc @skrishn

**Comment by CTLocalGovTeam** [comment]
@allisonmuise,

> For backwards compatibility, the original 'theme' property must be used for the shared theme header.background property.


We have already bound header.background to theme as shown below

![image](https://cloud.githubusercontent.com/assets/2959186/22852174/74e82548-f05c-11e6-85b7-fbdb01d441f8.png)


> The headerBackgroundColor should not be necessary.

Do you want to remove this option from configuration & default config file ?

Please confirm.

--Pratik Gohil

**Comment by skrishn** [comment]
@CTLocalGovTeam : I removed the headerBackgroundColor property from default.js and  configpanel.js along with its references in the config panel .
When I configure new app – I see a grey screen with loading page on the preview section. I get this console error message: Error: string.substitute could not find key "HeaderBackgroundColor" in template
Looks like this property is used in 18 different places in the app. 

![image](https://cloud.githubusercontent.com/assets/3836616/22953084/83c1ac3c-f2c4-11e6-8462-7ef89cba867e.png)

cc @allisonmuise

**Comment by CTLocalGovTeam** [comment]
@allisonmuise, @skrishn 

Removing the headerBackgroundColor property from default.js and configpanel.js along with its references in the config panel will not work as it has some dependencies in the code. To remove the headerBackgroundColor property from default.js and configpanel.js we would need to do some code changes. 

We will do the code changes and submit the pull request ASAP.

Please let us know your thoughts on this.

--Pratik Gohil

**Comment by skrishn** [comment]
@CTLocalGovTeam . Please go ahead and make the changes

Cc @allisonmuise

**Comment by allisonmuise** [comment]
verified!
