### ISSUE TITLE
configurable option to choose to display media or related records first

### ISSUE THREAD

**Issue by allisonmuise** [Esri/crowdsource-manager#205]
per Pat

when using manager for primarily media-review tasks, it would increase productivity to have the media tab load first. If we are adding this capability, we might as well as an option for loading the related records first, too.

**Comment by allisonmuise** [comment]
I'm open to suggestions, but I think we can do this with a single-selection radio button parameter in the configuration panel with three options: Details, Media, and Related Records. The selected option will be the panel that is open by default when a record is selected from the map or table. By default, Details will be selected to maintain backwards compatibility.

**Comment by CTLocalGovTeam** [comment]
@allisonmuise,

If we provide single-selection radio button parameter than we can only conclude which tab will be loaded first. What about the tab which will be loaded at 2nd & 3rd position ?

So we were planning to provide preference of order for the tabs as shown below :

![tabs options](https://cloud.githubusercontent.com/assets/2959186/20876759/32a82464-baea-11e6-8c53-8d9403c6ca74.png)

 

We need to consider some scenario for this approach as described below
> Scenario 1 : If user selects same value in all the 3 tabs
> Scenario 2 : If value of 2nd/3rd tab is same as 1st tab

In both this case default order will be loaded i.e; Info, Media & Comments

Please let us know what you think of this.

--Pratik Gohil

**Comment by allisonmuise** [comment]
@CTLocalGovTeam : I'm not looking to modify the order of the tabs - only which tab is open when a report is selected. 

Does the tab control we are using only allow the left tab to be open by default?

**Comment by CTLocalGovTeam** [comment]
@allisonmuise,

> Does the tab control we are using only allow the left tab to be open by default?

    No, by default we can open any tab.

As suggested, option of using single-selection radio button would not be possible because radio buttons are not supported in the  [Configuration parameters](https://doc.arcgis.com/en/arcgis-online/create-maps/configurable-templates.htm) so we are thinking of using dropdown.
 

We need to consider some scenario for this approach as described below

> Scenario 1 : If media tab is selected in configuration & selected feature does not contain any media
> Scenario 2 : If comments tab is selected in configuration & selected feature doesn't fulfill criteria to display comments tab


In all the above cases fallback Info tab will be opened

Please confirm.

--Pratik Gohil

**Comment by allisonmuise** [comment]
@CTLocalGovTeam 
Radio buttons will be added at 4.4. I c an make the switch from a drop-down later if that is easier for you do implement for now since there isn't documentation yet.

Yes, please fall back to the Info tab.

**Comment by CTLocalGovTeam** [comment]
@allisonmuise,

Sure, we will implement drop-down for now.

--Pratik Gohil

**Comment by allisonmuise** [comment]
verified
