### ISSUE TITLE
hide editing buttons when user doesn't have editing permissions

### ISSUE THREAD

**Issue by allisonmuise** [Esri/crowdsource-manager#207]
(reported from Holistic)
When accessing the application through an ArcGIS account that does not have editing capabilities, attempting to edit a report or submit a comment throws a browser error. Hide the edit and add comment buttons when the user does not have editing permissions, including when it is a level 1 account.

@CTLocalGovTeam : What is the LOE for this? Ideally it would get fixed this release, but I will push if that's not possible.

**Comment by allisonmuise** [comment]
use cases where editing must be restricted:
- [ ] Authenticated AGOL user does not have editing capabilities (includes Level 1 users)
- [ ] Editing is restricted to members of a group containing the layers
- [ ] Layer permissions only allow the user to edit features they created

None of these apply if the layer is shared with Everyone

**Comment by CTLocalGovTeam** [comment]
@allisonmuise,

On initial load, when no user have signed in should we show/hide the editing buttons ?

--Pratik Gohil

**Comment by allisonmuise** [comment]
@CTLocalGovTeam 
The buttons should be shown

**Comment by allisonmuise** [comment]
@CTLocalGovTeam : It appears that the core team has not taken this requirement as far as initially described. Please let me know the LOE to change to the following approach:

Never hide the buttons. When a user attempts to vote/comment/edit who does not have those capabilities enabled, display a message that says 'You do not have permission to perform this action."

**Comment by CTLocalGovTeam** [comment]
@allisonmuise 

The LOE for this is low as we have worked out the logic earlier.
Please confirm if we need to implement this for both Reporter & Manager.

**Comment by allisonmuise** [comment]
@CTLocalGovTeam Thank you - yes, for both apps

**Comment by allisonmuise** [comment]
verified
