### ISSUE TITLE
CSM only tests for an empty array when looking for relationships

### ISSUE THREAD

**Issue by allisonmuise** [Esri/crowdsource-manager#210]
App needs to test for null as well as the empty array. CSR already does this.

Use case: When cloning a layer without any related layers in AGOL, the service JSON includes an empty array for the related layers. When performing the same action in Portal, the value in the JSON for the related layers is null. Manager hangs when trying to read the second (Portal) layer.

![null_check](https://cloud.githubusercontent.com/assets/2752195/20845853/db25e7fa-b87b-11e6-880e-cc1bc603035e.png)

cc @chris-fox

**Comment by allisonmuise** [comment]
@skrishn Is this one on your list for Portal testing?

**Comment by skrishn** [comment]
@allisonmuise yes

**Comment by skrishn** [comment]
@allisonmuise verified.
