### ISSUE TITLE
BUG-000101689 Attribute fields that are subtype dependent with a domain applied do not display when editing in the Crowdsource Manager web app unless all fields in the feature layer are selected to be editable.

### ISSUE THREAD

**Issue by allisonmuise** [Esri/crowdsource-manager#221]
1447
 Web Map: http://ess.maps.arcgis.com/home/webmap/viewer.html?webmap=3826fbe234ff4975b15f15b4a4421066

Crowdsource Manager App: http://ess.maps.arcgis.com/apps/CrowdsourceManager/index.html?appid=e6837854955f47fdae9950c8b2e058be

1. Open the web map and only select the following fields to be editable in Configure Pop-up > Configure Attributes. Save web map. All three fields are subtype dependent with a domain applied and a default value. 

ConcernStatus -text default value
AppropriateYN -text default value
ReassignedEmailSent -integer default value

2. Open the web application and click on the record to prompt the Edit window > click Edit > none of the three fields will display. --> Bug

3. Repeat step 1 and select all fields to be editable. Then Refresh the application > select record to prompt Edit Window  > click Edit > all fields, including the subtype dependent fields will display. 

Video: http://screencast.com/t/GXzDyiEFN

FGDB attached. Feature class name = GeoConcerns
Salesforce ID: BUG-000101689
Salesforce Submitter: Rudy Ruvalcaba
Salesforce Submit Date: 12/22/2016 7:47 AM
Salesforce Bug Type: Failure/Error
Salesforce Severity: Medium
Repro Data: \\esri.com\sf_filestore\PRD\Attachments\Defects\BUG-000101689
Work Around: (n/a)
Product: ArcGIS Online
Functional Category: ArcGIS Online Application Templates
Client Platform: (n/a)
Version Found: 4.4
Planned Version Fixed: (n/a)
Comment: (n/a)

**Comment by allisonmuise** [comment]
(repro link pending)

**Comment by CTLocalGovTeam** [comment]
@allisonmuise,

As discussed, this issue is no longer reproducible.

Please let us know if you still face any issue.

--Sumit Zarkar

**Comment by allisonmuise** [comment]
@CTLocalGovTeam Thanks - pinged the support analyst again to follow up with the customer.

**Comment by allisonmuise** [comment]
@CTLocalGovTeam Let's discuss this on the call tomorrow morning. I have a repro case and a better understanding of what is going on, but I'm not sure if there's anything we can do about it.

**Comment by CTLocalGovTeam** [comment]
@allisonmuise,

To implement this we need to handle below-mentioned cases.

1. Display of subtypes field even if its parent field is unchecked
2. Edit and update functionality of such subtypes field
3. While displaying the option in the subtypes, considering the option that is selected in its parent field which is not visible
4. Displaying updated subtypes field of such cases in the data grid

--Pratik Gohil

**Comment by allisonmuise** [comment]
verified on devext
