### ISSUE TITLE
Change the timeslider color logic

### ISSUE THREAD

**Issue by skrishn** [Esri/crowdsource-manager#222]
Right now, time slider color uses 'Button background color', but if Button background color is set to White, the time slide appears like this 

![image](https://cloud.githubusercontent.com/assets/3836616/23378152/3f370b66-fce7-11e6-8b37-fb3851917d2e.png)

**Comment by CTLocalGovTeam** [comment]
@skrishn, @allisonmuise 

Instead of button background color, we are planning to apply button text color. The probability of setting button text color to white is very low.

Please confirm.

--Pratik Gohil

**Comment by skrishn** [comment]
@CTLocalGovTeam @allisonmuise : I like the idea. Lets wait on Allison's input.

**Comment by allisonmuise** [comment]
@CTLocalGovTeam I think the probability of whit button text color is equal to that of white being the  background colour. Can you look at the two button values and use the one that is furthest from white? Perhaps highest saturation value? The background of that panel will always be white, and ideally we want to contrast with that.

**Comment by allisonmuise** [comment]
verified
