### ISSUE TITLE
Allow configuration for web map filters to be "off" by default

### ISSUE THREAD

**Issue by Fish4Food** [Esri/crowdsource-manager#224]
Enable the option in configs, or change the default behavior of the manager app, to have web map filters turned off/ disabled by default.

E.g. Would like to enable multiple fields to be filter-able to allow staff to manipulate their data in the app. However, when multiple fields have a filter set up, when staff use the app, they have to go into each field and disable/change the filter first, before getting a default view of their data and before using/changing the filters for their needs.  If the filters were off by default, they could go into each field to filter as they needed (instead of having to turn off or change all of the filters first).

**Comment by allisonmuise** [comment]
@Fish4Food The default filter values can be turned off using the parameter on the Filter tab of the configuration panel.

**Comment by Fish4Food** [comment]
@allisonmuise I see that option in the AGO hosted app on the Filter tab, but we're hosting locally and cannot find this option in the default.js config folder.  Maybe I overlooked it, but all i have is "enableFilter" true/false parameter.

**Comment by allisonmuise** [comment]
That is the corresponding setting if you are hosting it locally. true = filters applied; false = filter values ignored

http://solutions.arcgis.com/local-government/help/crowdsource-manager/get-started/host-on-your-web-server/
