### ISSUE TITLE
Add ability to see popup info for non-editable layers

### ISSUE THREAD

**Issue by allisonmuise** [Esri/crowdsource-manager#235]
as with reporter
display popup info in Details area

**Comment by allisonmuise** [comment]
Related media and related records should display on tabs, just as they do for the editable features, but the editing pencils should be hidden.

**Comment by CTLocalGovTeam** [comment]
@allisonmuise,

While analysing we came across few queries which are listed below

1. As per the current functionality, data viewer displays the records of selected layer in the webmap list. Hence, when the user clicks on a feature of non-editable on a map, what should be displayed in the data viewer? We are planning to keep the records as it is.

2. Consider that user has clicked on the feature of an editable layer which gets highlighted on both map & data viewer. Now, if the user clicks on a feature of the non-editable layer. Considering this how would you like to handle the selection of the previous feature? We are planning to remove the previously selected feature of editable layer both from map & data viewer and highlight the newly clicked feature of the non-editable layer.

3. Whenever the feature(non-editable layer) is selected, regardless of ctrl+click or single click, the application will display details of selected feature and it will discard all the previously selected feature of an editable or non-editable layer.

Please confirm?

--Pratik Gohil

**Comment by allisonmuise** [comment]
@CTLocalGovTeam 
I am assuming that the table is what you are referring to as the 'data viewer'. With that assumption, all of the points made above sound correct.

**Comment by allisonmuise** [comment]
@CTLocalGovTeam This should be configurable as well. Please see Reporter config panel and implement the same for this app

**Comment by allisonmuise** [comment]
verified

**Comment by skrishn** [comment]
@aparveen added testcase
