### ISSUE TITLE
add legend widget

### ISSUE THREAD

**Issue by allisonmuise** [Esri/crowdsource-manager#236]

**Comment by allisonmuise** [comment]
I suggest starting with the button graphic from Basic Viewer. This button could sit in line with the navigation widgets on the left side of the map. Clicking the widget would expand a panel (like the search does) containing the legend content. This panel should be styled to fit in with Manager. Do not use the same styling from Basic Viewer.

**Comment by CTLocalGovTeam** [comment]
@allisonmuise,

Following are the screenshots of the legend widget in the different scenarios, depending on the availability of the area.

**Case1: Scroll handle at extreme top**
![image](https://user-images.githubusercontent.com/2959186/30803419-2ce6fdde-a207-11e7-9499-0650a694dc78.png)


**Case2: Scroll handle at the center**
![image](https://user-images.githubusercontent.com/2959186/30803422-3217ca4a-a207-11e7-8b6b-535f9a5079f9.png)


**Case3: Scroll handle at the extreme bottom**
![image](https://user-images.githubusercontent.com/2959186/30803429-373c476c-a207-11e7-8600-90585b17527d.png)

Please confirm, should we go ahead with this implementation?


Apart from this, we have a query which is listed below

1. Do we also need to display non-editable layers along with editable layer in the legend widget?




--Pratik Gohil

**Comment by allisonmuise** [comment]
I'm ok with cases 1 & 2 as shown, but I'm concerned about screen size. Will the widget always show like this, even on smaller screens/browser windows?

What are the alternatives for case 3?

**Comment by CTLocalGovTeam** [comment]
@allisonmuise,

Similar to #189 we are planning to display the legend widget in the centre of the page.

Do we also need to display non-editable layers along with editable layer in the legend widget?

Please confirm?

--Pratik Gohil

**Comment by allisonmuise** [comment]
@CTLocalGovTeam Yes, please show editable and non-editable layers. This approach sounds good.

**Comment by allisonmuise** [comment]
@CTLocalGovTeam Could we make this configurable, and off by default?

**Comment by allisonmuise** [comment]
@CTLocalGovTeam  Could we add a bit of white space between the nav buttons and the basemap and legend buttons. I'd like the space between the basemap and legend buttons, as well.

**Comment by allisonmuise** [comment]
verified

**Comment by skrishn** [comment]
@allisonmuise added testcase
