### ISSUE TITLE
Problem in updating related records in crowd source manager

### ISSUE THREAD

**Issue by jha-suraj** [Esri/crowdsource-manager#237]
I am getting below issue while saving related record value in related table while using ArcGIS crowd source manager. The primary key is objectid of feature class.

Error: Edits could not be saved.

Please help me to solve this issue. What could be the possible work around.

Thanks.
Suraj

**Comment by allisonmuise** [comment]
@jha-suraj What is your foreign key field?

**Comment by jha-suraj** [comment]
Thanks for your response.Foreign key is just a numeric field in comment table. Crowd source reporter is working fine with this feature layer.

**Comment by allisonmuise** [comment]
@jha-suraj Could you contact Esri Support or your distributor about this issue? That should be working so there is likely something else going on, either with how the relationship is defined or how the layers/map/app are configured.

**Comment by jha-suraj** [comment]
I have added two different related table for two different layers and established relationship, i mean also created two relationship class. In crowd source manager for some records i did not get Comment(Related record) tab and the record for which i got comment tab shows number of related record 0 although there are some comments entered by crowd source reporter also i am not able to add related record through crowd source manager. I inspected the page and  got the error in attached doc . 
[error.docx](https://github.com/Esri/crowdsource-manager/files/1185098/error.docx)

**Comment by allisonmuise** [comment]
@jha-suraj This is not a good means for me to troubleshoot this issue. Please contact Esri Support Services or your local Esri distributor for more help. They will be familiar with these apps, and will be able to work with you to understand your data structure and what is going on with the app.
