### ISSUE TITLE
Allow user to click sign in name in top right corner to open "Sign Out" option

### ISSUE THREAD

**Issue by cosbyr** [Esri/crowdsource-manager#248]
Right now the user is forced to click the triangle next to the name.

**Comment by CTLocalGovTeam** [comment]
@allisonmuise,

We have implemented this enhancement and will be available in the next code drop.

--Pratik Gohil

**Comment by allisonmuise** [comment]
@CTLocalGovTeam Where you've already made the change...want to send this to me now and I'll include it in the 6.1 release? There are currently no other issues for 6.2 for this app.

**Comment by CTLocalGovTeam** [comment]
@allisonmuise,

> Where you've already made the change...want to send this to me now and I'll include it in the 6.1 release? There are currently no other issues for 6.2 for this app.

Sure, we will include this ticket also in the upcoming code drop on Friday, March 16.


--Pratik Gohil

**Comment by allisonmuise** [comment]
verified
