### ISSUE TITLE
Selection options should reflect current state of app

### ISSUE THREAD

**Issue by allisonmuise** [Esri/crowdsource-manager#25]
the following options are available even when no features are selected:
Show Selected
Clear Selection:
Zoom To Selected

Please grey these out and disable them when no features are selected.

**Comment by allisonmuise** [comment]
When no feature is selected, please grey out and de-activate all three selection-based options.

**Comment by CTLocalGovTeam** [comment]
@allisonmuise 

OK.  We will implement this in the next release.

**Comment by allisonmuise** [comment]
verified
