### ISSUE TITLE
BUG-000110591 The search function in Crowdsource Manager returns all results if the web map has a search function defined and contains a hosted feature layer that has set of filters applied using the expression 'Any'.

### ISSUE THREAD

**Issue by allisonmuise** [Esri/crowdsource-manager#251]
<div><div><ol><li>Add a hosted feature layer to a new Map Viewer. </li><li>Under the content, hover over the layer and click on the Filter icon.</li><li>In the Filter window, click on &#39;+Add another expression&#39;, and select the expression &#39;Any&#39; in the line that states &quot;Display features in the layer that match ....&quot;. </li><li>Select filters of your choosing for both expressions and click Apply Filter.</li><li>Save the map as New map.</li><li>Navigate to Content, and open the newly create web map to view the Overview page.</li><li>Click on the Settings tab, and scroll down to &#39;Find Locations&#39;, under Application Settings.</li><li>Check the option &#39;By Layer&#39;, and click on &#39;Add Layer&#39;.</li><li>Select a layer of your choosing and click Save.</li><li>Share the item with a group (this is to create a Crowdsource Manager app). If prompted to update the sharing settings of the hosted feature layer in the web map, click Ok.</li><li>Navigate back to the Content page.</li><li>Click on &#39;Create&#39;, and select &#39;Using a Template&#39; under App.
	<ul><li>Sample of the app: <a href="http://ess.maps.arcgis.com/home/item.html?id=18bad0dda684457fac2d8176539ba68b" target="_blank">http://ess.maps.arcgis.com/home/item.html?id=18bad0dda684457fac2d8176539ba68b</a><br>		(The search in the sample is based on Reference).</li></ul>
	</li><li>Select the Scrowsource Manager and proceed to create web app.</li><li>In the web app configuration page, select the group you shared the map with, and then select the web map saved earlier.</li><li>Save the app, and click on &#39;Launch&#39;.</li><li>Click on the search icon at the top right, and search for an item based on the layer set earlier in step 8. Notice the search doesn&#39;t work, instead it returns all results.</li></ol>
Notes:

<ul><li>This doesn&#39;t happen if the set of filters had the expression &#39;All&#39; in step 3. </li><li>Reproduced on Portal for ArcGIS 10.5.1 as well.</li><li>Attached are screenshots comparing both search results of filter sets using &#39;Any&#39; and &#39;All&#39; expressions.</li></ul></div><div>
<span><b>Salesforce ID:</b> BUG-000110591</span><br/>
<span><b>Salesforce Submitter:</b> Ahmed Abdulwahab</span><br/>
<span><b>Salesforce Submit Date:</b> 1/05/2018 12:53 PM</span><br/>
<span><b>Salesforce Bug Type:</b> Failure/Error</span><br/>
<span><b>Salesforce Severity:</b> Medium</span><br/>
<span><b>Repro Data:</b> \\esri.com\sf_filestore\PRD\Attachments\Defects\BUG-000110591</span><br/>
<span><b>Work Around:</b> (n/a)</span><br/>
<span><b>Product:</b> (n/a)</span><br/>
<span><b>Functional Category:</b> ArcGIS Online Application Templates</span><br/>
<span><b>Client Platform:</b> (n/a)</span><br/>
<span><b>Version Found:</b> N/A</span><br/>
<span><b>Planned Version Fixed:</b> (n/a)</span><br/>
<span><b>Comment:</b> (n/a)</span><br/>
</div></div>

**Comment by allisonmuise** [comment]
http://arcgis4localgov2.maps.arcgis.com/apps/CrowdsourceManager/index.html?appid=985b35ef76e842b69f25da1ca37b640a

The only difference between the two maps in this app is the qualifier for the filter. One uses 'And' and the other 'Any'. Search for 'Allison' in both maps to see the difference in behavior.

**Comment by CTLocalGovTeam** [comment]
@allisonmuise,

We have fixed this issue and will be available in upcoming code drop.

--Pratik Gohil

**Comment by allisonmuise** [comment]
verified

**Comment by skrishn** [comment]
@aparveen added testcase
