### ISSUE TITLE
Default values not being written for related records

### ISSUE THREAD

**Issue by allisonmuise** [Esri/crowdsource-manager#253]
Default values are not being written to the related table when new Comments are created. These same default values are written when comments are created through Reporter.

http://arcgis4localgov2.maps.arcgis.com/apps/CrowdsourceReporter/index.html?appid=3edb41365a1c43d2b8f637797e46dd0f

http://arcgis4localgov2.maps.arcgis.com/apps/CrowdsourceManager/index.html?appid=89a11a4311ca4684a2b15711cad41a75

repro steps:
1. Submit a comment on the feature in the Reporter app. Note that the STATUS field has the default value Submitted.
2. Submit a comment on the feature in the Manager app. Note that the STATUS field does not have a default value.

Both apps are using the same layer, map, and group. The STATUS field has the default value 'Submitted' defined in the templates.

**Comment by CTLocalGovTeam** [comment]
@allisonmuise,

We have fixed this issue and will be available in upcoming code drop.

--Pratik Gohil

**Comment by allisonmuise** [comment]
@CTLocalGovTeam I can still repro this behavior. The Public View field in the comment table has a default value of 'Yes'. This field isn't editable, but it is visible. Note that this value isn't populated when a comment is submitted.

http://localgovtestdev.mapsdevext.arcgis.com/apps/CrowdsourceManager/index.html?appid=c8960073c12b413b818a7b27d82d71e0

**Comment by allisonmuise** [comment]
verified
