### ISSUE TITLE
Filter: unique vs Value setting doesn't carry over from map

### ISSUE THREAD

**Issue by allisonmuise** [Esri/crowdsource-manager#263]
When defining the filter in the map , you can specify if you'd like the filter to be of type Value or Unique. This setting is not carried over into Manager.

**Comment by pratikg** [comment]
@allisonmuise,

We have analysed this issue and observed that the ArcGIS API does not provide any info on whether the filter is applied through Value or Unique.

Even this settings are not retained in the map viewer. We applied unique filter settings, saved it, refreshed the map viewer and still filter settings points to the "Value" as shown below.

![csm_unique_filter](https://user-images.githubusercontent.com/1454356/49514556-652f3c00-f8ba-11e8-975a-7ec75c9715fd.gif)

Please share your thoughts on this.

**Comment by allisonmuise** [comment]
@pratikg I agree - this appears to be working as well as it is able to.
