### ISSUE TITLE
Unable to edit records when What kind of editing is allowed? -> Update features enabled

### ISSUE THREAD

**Issue by chris-fox** [Esri/crowdsource-manager#269]
This looks to be a regression at 7.1, maybe related to #261? I have a solution "Capital Project Review" that was working prior to the release but recently discovered when launching the application the pencil no longer displayed when I selected a record. I found when I change the What kind of editing is allowed? from "Update features" to "Add and update features" it resolved the issue. We shouldn't require add features ability in the manager application.

I have updated the editor settings on the item to workaround the issue, but for the workflow it would be better to allow users to decide if they only want users working with manager and their layers to update the attributes of the feature.

To reproduce:

1. Configure a manager application using a hosted feature layer.
2. Set the editor settings like below:

![image](https://user-images.githubusercontent.com/6796763/55408556-3b1b1d00-552e-11e9-9b73-3d4740666196.png)

@aparveen, @LindsayThomas

**Comment by LindsayThomas** [comment]
@aparveen can you take a look at this?

**Comment by aparveen** [comment]
@LindsayThomas I was able to repro it.

**Comment by LindsayThomas** [comment]
@aparveen okay thanks. I'll get a note to CT

**Comment by pratikg** [comment]
@aparveen, @LindsayThomas

We are able to reproduce this issue. Its fix will be available in the upcoming code drop.

**Comment by aparveen** [comment]
Verified in devext.
