### ISSUE TITLE
CS Manager is not drawing vector basemap

### ISSUE THREAD

**Issue by aparveen** [Esri/crowdsource-manager#271]
Crowdsource Manager doesn’t always drawing the basemap. It seems to be specific to vector basemaps. If I access the map in map viewer, it works fine. We had similar issue for Reporter which was fixed in December 2018 (AGOL 6.4 release) https://github.com/Esri/crowdsource-reporter/issues/363, Manager issue was mentioned in that reporter issue but does not look like it was addressed in the manager. 

[Test App](https://www.arcgis.com/apps/CrowdsourceManager/index.html?appid=85f76202cd134713be282179628471b7)

In this app, basemap has two layers, one is topo map which is vector layer ad another is hillshade which is not a vector layer.

![image](https://user-images.githubusercontent.com/10148401/60628597-032eaa80-9da7-11e9-8707-f840c36f7660.png)

**Comment by MikeTschudi** [comment]
Example of hillshade plus topo vectors from this basemap:
![image](https://user-images.githubusercontent.com/2125181/60740479-bc61c180-9f1a-11e9-8fe1-6e24aee3b7e3.png)

**Comment by aparveen** [comment]
Mike was able to reproduce the problem in CM by throttling the browser connection emulation to “Slow 3G”. He looked at the code changes to CR fix and thinks the similar fix would work for CM as well.

**Comment by pratikg** [comment]
@aparveen, @MikeTschudi 

We will fix this issue and will be available in the upcoming code drop.

**Comment by aparveen** [comment]
Verified in devext.
