### ISSUE TITLE
BUG-000122348 When attempting to select a point hosted feature layer with labels in a web map within Crowdsource Manager, multiple attempts must be made to select it.

### ISSUE THREAD

**Issue by allisonmuise** [Esri/crowdsource-manager#274]
<div><div><p><b><u>Preparatory Steps</u></b></p>

<p> </p>

<p>Step 1. Follow the instructions under the &quot;Crowdsource Manager maps&quot; section: <a href="https://solutions.arcgis.com/local-government/help/crowdsource-manager/get-started/setup-map/" target="_blank">https://solutions.arcgis.com/local-government/help/crowdsource-manager/get-started/setup-map/</a></p>

<ul><li>Note. The defect demonstrates that the behavior when a web map is shared with a group in ArcGIS Online. You can leave Step 6,7 and 8 as default. In this example, I shared the Group with Esri Support Services.</li></ul>

<p> </p>

<p>Step 2. Follow the instructions under the &quot;Configure Crowdsource Manager&quot; section: <a href="https://solutions.arcgis.com/local-government/help/crowdsource-manager/get-started/configure-app/" target="_blank">https://solutions.arcgis.com/local-government/help/crowdsource-manager/get-started/configure-app/</a></p>

<ul><li>Note. You only need to perform Step 1 and Steps 2. You can leave the General Settings, Theme Settings, Other options, Report Settings, Filter Settings as default to experience the issue.</li></ul>

<p> </p>

<p>Step 3. In the Group you created, select the web map&gt; In the Table of Contents, select the three dots (More Options) for the point hosted feature layer&gt;Select Manage Labels&gt; Select Label Features&gt; Under Alignment&gt; Select the Center&gt; Select OK&gt; Select Save</p>

<p> </p>

<p>Step 4. Navigate back the web mapping application&gt; Try selecting a few points&gt;You will observe that you are not able to select a feature consistently&gt; You can try zooming in and out and try selecting at different scales. There is no consistency of what you are able to select at what scales. It will work randomly.</p>

<p> </p>

<p><b><u>Experience the issue:</u></b></p>

<p>I have included two links to the Crowdsource Manager. One that includes a web map with labels, titled &quot;Webmap_withlabels&quot;and one that does not include labels, &quot;Webmap_without labels&quot; to demonstrate the difference.</p>

<p> </p>

<ul><li>Crowdsource Manager (with labels):
	<ul><li>Select <a href="https://arcg.is/1PLqXD0" target="_blank">https://arcg.is/1PLqXD0</a>&gt; Sign in with Esri Support Service credentials&gt; Select View Application&gt; In the left side, select &quot;Webmap_withlabels&quot;&gt; Try selecting a feature&gt; You will not be able to smoothly select one feature and select another one at all scales consistently.</li></ul>
	</li><li>Crowdsource Manager (without labels):
	<ul><li>Select <a href="https://arcg.is/1PLqXD0" target="_blank">https://arcg.is/1PLqXD0</a>&gt; Sign in with Esri Support Service credentials&gt; Select View Application&gt; In the left side, select &quot;Webmap_withoutlabels&quot;&gt; Try selecting a feature&gt; You will be able to smoothly select one feature and select another one at all scales consistently.</li></ul>
	</li></ul>

<p> </p>

<p><i>Note. Please see attached video for visual reference.</i></p>

<p> </p>

<p><b><u>Testing Observations:</u></b></p>

<ul><li>Behavior does not occur in a web mapping application created from the WebApp Builder.</li><li>Behavior does not occur in a web map</li><li>Behavior does not change if you change the symbology or the size of the symbology</li><li>Behavior does not change when in Label Features dialog box, you change the Text, Font size, add a Halo or make the text underline, italics or underlined</li><li>Behavior occurs in Internet Explorer and Google Chrome, which verifies it is not browser specific</li><li>Behavior still occurs when in Incognito window</li></ul>

<p> </p></div><div>
<span><b>Salesforce ID:</b> <a href="https://qamonitor/sftriage?sfid=BUG-000122348">BUG-000122348</a></span><br/>
<span><b>Salesforce Submitter:</b> Matt Tsui</span><br/>
<span><b>Salesforce Submit Date:</b> 5/13/2019 11:58 AM</span><br/>
<span><b>Salesforce Bug Type:</b> Failure/Error</span><br/>
<span><b>Salesforce Severity:</b> Medium</span><br/>
<span><b>Work Around:</b> <ol><li>In the created Group, select the web map. </li><li>In the Table of Contents, click the More Options icon for the point hosted feature layer.</li><li>Select Manage Labels &gt; Label Features.</li><li>Under Alignment type, select any other alignment beside Center, and select OK.</li><li>Save the changes.</li></ol>

<p> </p>

<p> </p></span><br/>
<span><b>Product:</b> (n/a)</span><br/>
<span><b>Functional Category:</b> ArcGIS Online Application Templates</span><br/>
<span><b>Client Platform:</b> (n/a)</span><br/>
<span><b>Version Found:</b> (n/a)</span><br/>
<span><b>Planned Version Fixed:</b> (n/a)</span><br/>
<span><b>Comment:</b> (n/a)</span><br/>
</div></div>

**Comment by allisonmuise** [comment]
3151

**Comment by allisonmuise** [comment]
@aparveen Can you reproduce this behavior?

**Comment by aparveen** [comment]
@allisonmuise I can repro it, it only happens with centrally aligned label, seems like on mouse click is obstructed by the label and can't reach to the point itself.
![image](https://user-images.githubusercontent.com/10148401/64562255-73a2fc00-d301-11e9-8b96-1d1481186fcc.png)

**Comment by allisonmuise** [comment]
reproducibility seems to vary a bit with symbology size and offset. here is a repro app: https://stategovernment.maps.arcgis.com/apps/CrowdsourceManager/index.html?appid=1f344dc5c7714c6986674f6cf456b0fc

**Comment by allisonmuise** [comment]
closing this as a known issue. Modifying this behavior would involve re-doing the very complex selection logic and there is a very simple workaround - adjust the offset of the labels.
