### ISSUE TITLE
Console error on clicking edit button in Popup

### ISSUE THREAD

**Issue by skrishn** [Esri/crowdsource-manager#276]
Noticed in production and qa apps. Firefox throws a warning and the rest of the browsers throw an error. 

Edits are being honored so it doesn't seem like a showstopper.

https://www.arcgis.com/apps/CrowdsourceManager/index.html?appid=85f76202cd134713be282179628471b7

![image](https://user-images.githubusercontent.com/3836616/65063823-e2044180-d933-11e9-90b5-36d6ce457130.png)

**Comment by aparveen** [comment]
CT team looked into this issue and found out that some calcite fonts are not being loaded and they don't have any control over loading these fonts. I reached out to AGOL dev team, they are looking into this issue.

**Comment by aparveen** [comment]
ArcGIS Online team looked into this and they responded that "it looks like those calcite requests are to something different than the calcite web that we use in the majority of our other configurable apps, so we are not familiar.  That calcite-bootstrap has a repo and there is the following issue within it that could be related:

https://github.com/Esri/calcite-bootstrap/issues/169

You probably want to have the devs look at that, and maybe the calcite-bootstrap version needs to be updated possibly?"

**Comment by allisonmuise** [comment]
verified
