### ISSUE TITLE
Add ability to shift+click to select multiple rows

### ISSUE THREAD

**Issue by chris-fox** [Esri/crowdsource-manager#284]
This issue is extending the behavior in #97, but would like to add Shift+Click to select all the rows in between. Currently using Ctrl+Click you can add multiple rows to the current selection.

What we are proposing is with Shift+Click it would behave much like excel. If I select row 3 and then Shift+Click row 10 it would select rows 3-10.

@jlindemann, @ScottOppmann

**Comment by aparveen** [comment]
@CTLocalGovTeam Could you please evaluate this enhancement request? Also, please let us know if you have the capacity to implement this in 8.2 release.

**Comment by skrishn** [comment]
Verified in dev and qa.
