### ISSUE TITLE
Blank image appears after the last image in media tab

### ISSUE THREAD

**Issue by skrishn** [Esri/crowdsource-manager#288]
In the media tab, after the last image right arrow appears and upon clicking it a blank image panel appears along with a console error.  The features are added from Survey123 app.  The map popup is configured with arcade expressions and a table is embedded in the popup ( on the application status field) . I guess the table in the popup seem to be appearing as a blank image in the media tab. The popup configuration is similar to one of our solution and the issue cannot be reproduced in this one as the hosted feature layer doesn’t come from Survey123.  I cannot repro if I create a map/app with their feature service without configuring the popup, and I tried to config the popup with table but not successful yet.  I tried to add features from Survey 123 app which has no issue ( still working on the popup config – table part). I think it’s the combination of Survey 123 features and the popup configuration is causing some issue.

**Comment by ashishchoure** [comment]
@skrishn 

- We need to add images in the media section of popup.
- The field selected for URL of image should have a null value.
- When you select a feature in which the URL field has a null value and all the images become invalid then you will see the issue.

![image](https://user-images.githubusercontent.com/5525972/84371992-1b828880-abf8-11ea-9d52-0425176d3f90.png)

Let me know if you need more information.

**Comment by skrishn** [comment]
verified in devext

**Comment by skrishn** [comment]
verified in qa
