### ISSUE TITLE
App hangs on clicking Select All when there is lot of features

### ISSUE THREAD

**Issue by skrishn** [Esri/crowdsource-manager#291]
If layer has a lot of features - app throws a alert message 'Features cannot be displayed" and app keeps loading.  

https://crowdsource.mapsqa.arcgis.com/apps/CrowdsourceManager/index.html?appid=659f8c4a2fba4ebaac7c048c2f83a5e3

1. Launch the app
2. Click Select All button - it could be irresponsive and after a while it throws alert message and app shows the loading bar. It appears some features are selected though but the app hangs during the process.

Is there a better way to handle this behavior?

**Comment by aparveen** [comment]
@CTLocalGovTeam Could you please evaluate the level of effort in this issue for patching in this release?

**Comment by ashishchoure** [comment]
@aparveen @skrishn 

Here is the current approach for selecting all the records :
- Once user clicks on "Select All" button, we simply loop through all the rows in the table and click them one after the other. 
- Once the row is clicked, the existing logic then selects the feature on the map and the popup will be displayed.
- This workflow of selecting row, highlighting graphic on map and then opening the popup in edit mode is interconnected.

We used the above approach to make sure all the above dependencies are handled.  However, if the layer has more number of features then application sometimes become unresponsive.

To overcome this, we may have to rethink the logic of "Select All" functionality.

This looks a significant change and will require good amount of testing also. Considering the amount of work involved, it will be good if we can move this to 8.3 release.

**Comment by topowright** [comment]
We are also seeing a similar experience with a large number of records making the app non-responsive. This happens on load and on selection.

**Comment by skrishn** [comment]
@ashishchoure : Please see the link  below - I get a alert message : Unable to select 1 invalid feature(s); could you explain why we get this message and what is causing it. 

https://lgtest.mapsdevext.arcgis.com/apps/CrowdsourceManager/index.html?appid=0b1cfefc82c544808dd226ab94f885b6
![select_all](https://user-images.githubusercontent.com/3836616/92654993-88fc8e80-f2a5-11ea-9ccf-7b36af37a8ac.gif)

**Comment by ashishchoure** [comment]
@aparveen @skrishn 

- The alert message is shown when we are not able to fetch any of the feature(s) or its geometry. 
- This is as per designed. When user clicks on "Select All" button and there is problem with selecting a feature(s), we will show the alert message with number of features that cannot be selected.

**Comment by skrishn** [comment]
@ashishchoure : thanks for the details but I am still confused on why these features are not being able to be selected. In this example, if you look at the map closely there are more than one feature that is not selected but only 1 is in the alert. Moreover, I am able to select that unselected feature by clicking on it. 

cc @aparveen

**Comment by ashishchoure** [comment]
@skrishn @aparveen 

Could you please share the webmap in which you are seeig this behavior.

**Comment by skrishn** [comment]
@ashishchoure  webmap: https://lgtest.mapsdevext.arcgis.com/home/webmap/viewer.html?webmap=6e477e9fe11d45fdbdebc00373125c3a. Sorry, i didnt realize the app wasnt shared publicly.

**Comment by skrishn** [comment]
@ashishchoure : Follow-up question on this, when you ascend on the length there is only one feature with 0 length which gets reported in the alert but there are some features on the map which is not highlighted with cyan. What could be the reason for it.

cc @aparveen

**Comment by ashishchoure** [comment]
@skrishn @aparveen 

- The line layer used in the shared application (Trails- Text Filter) has some multi part features(features with multiple paths).
- We were selecting only first part of a feature and hence some of the features were not highlighted on the map.
- This was an existing issue. We have fixed this issue at our end and it is a minor fix. We will test this implementation and send the pull request by tomorrow.

**Comment by skrishn** [comment]
Verified in dev and qa
