### ISSUE TITLE
Replace the search button with a textbox to access the selection tools effortlessly

### ISSUE THREAD

**Issue by skrishn** [Esri/crowdsource-manager#292]
As referencened in https://github.com/Esri/crowdsource-manager/issues/285#issuecomment-649220959 please implement the option '2a' ( i.e., replace the search button with a textbox)

**Comment by ashishchoure** [comment]
@skrishn @aparveen 

As per our understanding, we will now replace the search button icon with the search text box.
- The search text box will be shown if the web map has search configured.
- The search text box should be disabled/enabled same as the search button in the current application. (EG : If multiple records are selected then search is disabled, If "Select All" button is clicked then search text box is disabled etc.) 

So, as per the new requirement the application header will have,
1. App Logo
2. App Title
3. Search text box (If enabled)
4. Refresh button
5. Sign in option

Just wanted to make sure that we are on same page.

**Comment by skrishn** [comment]
@ashishchoure: yes, thats right.

**Comment by aparveen** [comment]
@ashishchoure when all features are selected the search box disappears, could you please take a look at this?
![image](https://user-images.githubusercontent.com/10148401/91593328-ce6ba400-e914-11ea-906c-e818c379ad57.png)

**Comment by aparveen** [comment]
@ashishchoure Checked the the production workflow and noticed that the search button disabled, so it is expected, please disregard my last comment. Thanks.

**Comment by skrishn** [comment]
verfied in devext

**Comment by skrishn** [comment]
verified in qa
