### ISSUE TITLE
The search by layer feature does not clear

### ISSUE THREAD

**Issue by SethDocherty** [Esri/crowdsource-manager#293]
We are running into an issue with the search capability that filters the rows as well as the individual column filters.

When a user searches by a layer and then clears the search filter, the table or records correctly displays all rows.  The problem arises when a user tries to filter by the column filters.  The records are not able to be filtered.  It seems as if clearing the search does not also remove the filter in the backend.

Furthermore, if you close of the search bar before clearing, it is not possible to clear your search to see all rows.
 
Attached is a gif to showcase this issue.
![Crowdsource Manager Search Issue](https://user-images.githubusercontent.com/18409326/86842819-bd6c8800-c073-11ea-91ca-b4f93789cfc3.gif)

**Comment by skrishn** [comment]
@SethDocherty : thank you for reporting this bug. I can reproduce this issue and it happens only when search by layer and filter is configured and not when either of it is configured.  Could you clarify how you're trying to clear search when search bar is closed before clearing.

**Comment by SethDocherty** [comment]
@skrishn I've been using the **X** button in the search bar to clear.
![image](https://user-images.githubusercontent.com/18409326/87352894-d2d92a80-c529-11ea-98a7-6bc7b6f21d44.png)

Hmm, interesting. I'm able to now close the search bar and then reopen and still retains the search value. I'll see If I can reproduce my earlier statement and edit this comment if I can.

**Comment by skrishn** [comment]
@SethDocherty where you able to repro

**Comment by skrishn** [comment]
@CTLocalGovTeam : what would be the LOE for this issue? Thanks

**Comment by ashishchoure** [comment]
@skrishn @aparveen 

We have analyze this ticket and it will be low level of effort.

**Comment by skrishn** [comment]
@ashishchoure : thanks for looking to it.

**Comment by aparveen** [comment]
@ashishchoure , Seeing an issue, after I search on a layer, if I try to filter the search result, I am getting console error, here is the app I was using during local testing: https://stategovernment.maps.arcgis.com/home/webmap/configureApp.html?appid=0bdcd42a7ec04821acb5c645b2603887
![image](https://user-images.githubusercontent.com/10148401/91599490-4937bd80-e91b-11ea-9634-e73c44bbbc0d.png)

**Comment by skrishn** [comment]
verified in dev

**Comment by skrishn** [comment]
@ashishchoure : Is the filter designed to work with a range? 

Please see the production app below 

1. Click on Filter icon
2. Enter a value in the first textbox and hit enter. Notice it applies the filter and we dont get to change the value in the second textbox. 
3. In order to change the second value we have to click on the filter icon. 

![filterRange](https://user-images.githubusercontent.com/3836616/92664780-c66b1700-f2b9-11ea-9e27-cc5b46d9cf7e.gif)

https://arcgis4localgov2.maps.arcgis.com/apps/CrowdsourceManager/index.html?appid=106b1b968ffb4596b5ad74d6f86bf72d

**Comment by ashishchoure** [comment]
@skrishn @aparveen 

- The filter works with the range values.
- The behavior which your seeing is as designed. Whenever you enter values in any of the range text box(s) the filter will be applied as we are applying the filter whenever text box value changes.
- So, if you change the value in first text box and the second text box has a valid value the filter will be applied. Now if you want to change the value of second text box then you will have to open the filter panel and then enter the value. 

Let me know if you need more information.

**Comment by skrishn** [comment]
verifed in qa
