### ISSUE TITLE
Refresh button does not reset the app when filters are applied. 

### ISSUE THREAD

**Issue by topowright** [Esri/crowdsource-manager#294]
### Background

Currently, when a user has a filter set on any column and the features that are returned are then closed in the list the refresh button in the top right corner of the app does not allow the user to reset the filters. 

### Current State

There is not a way to refresh the view of an app if a filter set on an attribute does not return any content. 
### Steps to Reproduce/requirement

1. Open Crowd Source Manager
![image](https://user-images.githubusercontent.com/5488313/87608419-be756900-c6b4-11ea-82fc-21521e9cdcf4.png)

2. Set a filter on one field
![image](https://user-images.githubusercontent.com/5488313/87608430-c503e080-c6b4-11ea-81a1-e442a0315587.png)

3. Close the incidents from the list
![image](https://user-images.githubusercontent.com/5488313/87608439-c92ffe00-c6b4-11ea-8fa4-9e8fddb611be.png)

4. The list will now not be present
![image](https://user-images.githubusercontent.com/5488313/87608449-cd5c1b80-c6b4-11ea-96ba-ddcea591709e.png)

5. Click the reset button and nothing happens

### Expected results/behavior
If I hit the reset button in the app I would expect the list and filters to reset to allow me to see all of the data that is represented in the list from the map. 
### Type of Opportunity
- [ ] Internal idea from an Esri employee
- [ ] Internal idea from an Esri employee that is needed based on needs from an indstury
- [x] An need from a customer or a current opportunity

**Comment by topowright** [comment]
@aparveen would it be possible to get this issue passed to @CTLocalGovTeam? This is an issue for a solution that we have customers currently using.

**Comment by ashishchoure** [comment]
@aparveen @skrishn 

As discussed on the call, we would need more information on this ticket on how to proceed. We can discuss this more if required.

**Comment by ashishchoure** [comment]
@skrishn 

As discussed on the call, here is the proposed solution,
- We will add a new configuration parameter which says “**Clear all the filters on manual refresh**” or “**Enable hard reset**”. (OR you can suggest a string)
   - This will be un-check by default to make sure the existing users don’t see these changes automatically (Backward compatibility)
   - If checked, the layer will load with filters applied from the web map (If any) and will clear
      - Applied column filters
      - Search filter
      - Feature Selection
   - If unchecked, the current manual refresh will work as is
   - Also, do you want us to consider this flag while implementing the GitHub ticket #304. i.e. In case of auto refresh interval

FYI @aparveen

**Comment by skrishn** [comment]
@chris-fox : Do you like this approach?

**Comment by chris-fox** [comment]
This looks good and I would say we name the option **Clear filters and selection with refresh**. I don't think the auto refresh should honor this setting. I don't think it makes sense for the manual refresh but not auto refresh.

**Comment by skrishn** [comment]
@chris-fox : thanks.

@ashishchoure : Please proceed with the changes. 

cc @aparveen

**Comment by ashishchoure** [comment]
### Dev Checklist


Items ​ | Is required​ | Status | Comments​
-- | -- | -- | --
Required NLS   change?​ | No |   | ​
Required   Backward compatibility​? | Yes |   |  
Required 508​? | No |   |  
Need   Sanitize?​ | No |   | ​


### Impact Analysis Report 



Impacted   Areas | Comments
-- | --
Have   Configuration changes?​ | Yes
Have Runtime   changes?​ | Yes
Impact on   RTL | No
Manual   Refresh Button | The code changes   for this area will impact the behavior of how the Manual Refresh button should   work
Filter (Column   filter and Search filter) | The column   filter and search filter should be retained or cleared based on the   configuration value
Feature   selection | The feature   selection should be cleared or maintained based on the configuration value
Data   Table | Data table should show the   features as per the applied filters or the cleared filters

**Comment by ashishchoure** [comment]
@skrishn @aparveen 

- As per our discussion, if the **Clear filters and selection with refresh** flag is set to true and the user clicks the refresh button then 
   - We will show a confirmation box with the message **"All filters, selections and unsaved changes will be discarded"** 
   -  on click of the ok button, the application will refresh
   - on click of the cancel button, the alert message will close and the application will not refresh 


![image](https://user-images.githubusercontent.com/5525972/97210062-127b0800-17e3-11eb-819b-ab1adc82cf23.png)

**Comment by skrishn** [comment]
verfied in qa. Testcase added
