### ISSUE TITLE
Filter attributes after a feature selection has been set

### ISSUE THREAD

**Issue by topowright** [Esri/crowdsource-manager#295]
#### Background
Currently, if you have a selection made that selects multiple features in a map you cannot then filter that selection based on attributes/ columns. 

#### Expected Results
We would like the ability to filter the selection based on the attributes in the already selected features. If there is only one feature selected the batch update process would be replaced by the standard popup information for that feature.

**Comment by SethDocherty** [comment]
Adding some visual context.  I have set of polygons, with different ID's:

![image](https://user-images.githubusercontent.com/18409326/87611292-b0841000-c6d5-11ea-8c7b-5988570ee398.png)

I would like to select a subset of my current selection using the filters in the column.  Currently it is not possible.
![image](https://user-images.githubusercontent.com/18409326/87611229-7d418100-c6d5-11ea-8886-6b6a04d4c4da.png)

Currently, the only option I have is by searching through a list and then selecting the ID. This is not feasible, from a user perspective, for certain columns for example that contain unique values. We would like the ability for the user to spatial constrain the list and then filter the based on attribute filters.
![image](https://user-images.githubusercontent.com/18409326/87611481-2d16ee80-c6d6-11ea-9c52-382013fb8433.png)

**Comment by topowright** [comment]
@aparveen would it be possible to get this issue passed to @CTLocalGovTeam? This is an issue for a solution that we have customers currently using.

**Comment by ashishchoure** [comment]
@aparveen @skrishn 

The current behaviour of selecting records and filters is as per the design and implementing the suggested changes would  have following challenges: 

- The user cannot apply filter after selection as we disable the filter once user enter in edit mode. This is to restrict user from changing the records in the data table and selection once in edit mode.
- In the current implementation, the total number of records in the data table are always in sync with the number of features on map (for the current layer). This way if we want to show only the selected records in the table then we will have to filter the records on the map (for current layer).
- Again, creating a new data table for the users current selection will be a considerable task in terms of efforts and performance as it involves heavy DOM manipulation. We will also need to filter the features on the map.
- Even if we create a new data table then we will have to find way to again go back to the original data table which will have all the features. This will again involve heavy DOM manipulation (depends on how much features are selected by the user and total number of features present in the layer)
- This could be a complex implementation and will require core design level changes. Also, this implementation will require high LOE and will have high impact. 

**Possible work around:**

- First filter the records through column filter(may be a combination of column filter and search filter) then select all the records, this way only intended features will be available in selection and then user can perform edits on them.

Please let us know how to proceed on this.

**Comment by SethDocherty** [comment]
@ashishchoure, thanks for your follow-up comment. Your suggestion of filtering content and then selecting all records provides the same end result that we were expecting. 

You can close out this issue.
