### ISSUE TITLE
Update the tooltip string on 'Search by layer' textbox's X button

### ISSUE THREAD

**Issue by skrishn** [Esri/crowdsource-manager#299]
When hovered on the X button, the tooltip reads 'Search this layer', please change it to 'Clear the search'

![tooltip](https://user-images.githubusercontent.com/3836616/92664310-78a1df00-f2b8-11ea-9342-1264000bdaa9.gif)

**Comment by ashishchoure** [comment]
### Dev Checklist

Items ​ | Is required​ | Status | Comments​
-- | -- | -- | --
Required NLS   change?​ | Yes |   | ​
Required   Backward compatibility​? | No |   |  
Required 508​? | No |   |  
Need   Sanitize?​ | No |   | ​


### Impact Analysis Report


Impacted   Areas | Comments
-- | --
Have   Configuration changes?​ | No
Have Runtime   changes?​ | Yes
Impact on   RTL | No
Setting tooltip string in search component | The code changes for this area are impacting the tooltip functionality. It should set   independently for search and clear text icon button in the search component

**Comment by skrishn** [comment]
verified in qa
