### ISSUE TITLE
Remove the alert message: Unable to select x invalid feature(s) on performing Select All

### ISSUE THREAD

**Issue by skrishn** [Esri/crowdsource-manager#300]
@ashishchoure : Refer to the comment https://github.com/Esri/crowdsource-manager/issues/291#issuecomment-689822711

- When performing Select All, a alert message comes up if there are any invalid features ( Example: "Unable to select 1 invalid feature(s)." ).  We dont want to show the alert message anymore and select all the features instead.

- When interactively selecting a record on the table with invalid geometry,  an alert is thrown: "Feature cannot be displayed" and for this behavior we will leave it as it is currently.

**Comment by ashishchoure** [comment]
### Dev Checklist


Items ​ | Is required​ | Status | Comments​
-- | -- | -- | --
Required NLS   change?​ | Yes |   | ​Remove string
Required   Backward compatibility​? | No |   |  
Required 508​? | No |   |  
Need   Sanitize?​ | No |   | ​



### Impact Analysis Report


Impacted   Areas | Comments
-- | --
Have   Configuration changes?​ | No
Have Runtime changes?​ | Yes
Impact on   RTL | No
Select   All, Show Selected, and Show All functionality in the data table | The code changes for this area are impacting the Select All, Show Selected, and Show All button functionality. It should be   independent of features geometry and should show all the features   selection(with and without geometry) in the data table
Shift+click functionality in the data table | The code changes   for this area is impacting the shift+click functionality to select table rows   for the features with and without geometry

**Comment by skrishn** [comment]
verified in qa
