### ISSUE TITLE
Provide an option to automatically refresh the table.

### ISSUE THREAD

**Issue by aparveen** [Esri/crowdsource-manager#304]
Currently in Manager there is no way to set a refresh interval . Our user could benefit from having an option to automatically refresh the table.

**Comment by aparveen** [comment]
@CTLocalGovTeam Could you please prioritize the assessment for this issue. Thanks so much

**Comment by ashishchoure** [comment]
@aparveen @skrishn 

In our discussion, we discussed some requirements which are as follows:
1.	Selection should be maintained
2.	User applied filters should be maintained


Here is our solution:
- We will add a checkbox in configuration which will allow user to honor the refresh interval of layers through a web map. (**“Enable auto refresh”**)

   - We will add one more check box along with the text box which will allow user to set custom refresh interval. If this is checked then all the layers will be refreshed with the specified time interval mentioned in the text box. This will override the layer’s refresh interval set in web map. 
   - This option will be visible only if **“Enable auto refresh”** is checked.


**NOTE:** 
-	The layer will not refresh if editing is in process i.e. the Geo form (edit feature) is open. Once user closes the form the layer will refresh.
-	Also, whenever the multiple features are selected edit mode gets activated. So in this case as Geo form is open the layer will not be refreshed.

**Comment by aparveen** [comment]
> @aparveen @skrishn
> 
> In our discussion, we discussed some requirements which are as follows:
> 
> 1. Selection should be maintained
> 2. User applied filters should be maintained
> 
> Here is our solution:
> 
> * We will add a checkbox in configuration which will allow user to honor the refresh interval of layers through a web map. (**“Enable auto refresh”**)
>   
>   * We will add one more check box along with the text box which will allow user to set custom refresh interval. If this is checked then all the layers will be refreshed with the specified time interval mentioned in the text box. This will override the layer’s refresh interval set in web map.
>   * This option will be visible only if **“Enable auto refresh”** is checked.
> 
> **NOTE:**
> 
> * The layer will not refresh if editing is in process i.e. the Geo form (edit feature) is open. Once user closes the form the layer will refresh.
> * Also, whenever the multiple features are selected edit mode gets activated. So in this case as Geo form is open the layer will not be refreshed.

@ashishchoure is it possible to honor web map refresh interval instead of adding the config parameter. here is the user case, user already have set interval in his/her webmap and in the Manager, they want to see the new records added to the layer popped up automatically without doing anything.

**Comment by ashishchoure** [comment]
@aparveen 

- We can honor the web map refresh interval without adding any configuration parameter.
- However, we think we should have a single check box which will say "**Honor web map refresh interval**". This will be un-check by default.
   - We are proposing this to handle the backward compatibility. So, only users who change the flag value to true will  see auto updates in the application.
   - If we directly honor the refresh interval then existing user's will see auto updates and this will be a change in behavior for them.

- If you want all the user's to see the auto updates (and not to worry about the backward compatibility) in the application then we will not have any addition in the configuration.
 
Please let us know you thoughts on our approach.

**Comment by aparveen** [comment]
> @aparveen
> 
> * We can honor the web map refresh interval without adding any configuration parameter.
> * However, we think we should have a single check box which will say "**Honor web map refresh interval**". This will be un-check by default.
>   
>   * We are proposing this to handle the backward compatibility. So, only users who change the flag value to true will  see auto updates in the application.
>   * If we directly honor the refresh interval then existing user's will see auto updates and this will be a change in behavior for them.
> * If you want all the user's to see the auto updates (and not to worry about the backward compatibility) in the application then we will not have any addition in the configuration.
> 
> Please let us know you thoughts on our approach.

@ashishchoure I agree with you about the config parameter, talked to @skrishn morning, she agreed as well.

**Comment by ashishchoure** [comment]
### Dev Checklist



Items ​ | Is required​ | Status | Comments​
-- | -- | -- | --
Required NLS   change?​ | No |   | ​
Required   Backward compatibility​? | Yes |   |  
Required 508​? | No |   |  
Need   Sanitize?​ | No |   | ​




### Impact Analysis Report


Impacted   Areas | Comments
-- | --
Have   Configuration changes?​ | Yes
Have Runtime   changes?​ | Yes
Impact on   RTL | No
Refresh functionality | The code changes for this change will have an impact on how the application auto-refreshes. The   application should auto refresh only when the refresh interval is set on the   layer in web map and the flag value is set to true
Backward compatibility | The existing user's application should not auto-refresh unless the user goes into the   configuration and change the flag value to true
Filter (Column   filter and Search filter) | The column   filter and search filter should be retained
Feature   selection | The feature   selection should be retained
Edit mode | The application   should not auto-refresh when the user is in edit mode

**Comment by aparveen** [comment]
@ashishchoure cant remember if I ask this before, with auto refresh on, both the data table and the map will refresh right?

**Comment by ashishchoure** [comment]
@aparveen 

Yes data table and map will refresh at the same time after an auto refresh.

**Comment by ashishchoure** [comment]
@aparveen 

As per our discussion here are the changes that we will be doing : 
- The auto refresh parameter default value will be changed from `false `to `true`. This way if the layer has refresh interval set, all the users will see an auto refresh in the application after specified time interval.
- The auto refresh parameter will be removed from the configuration panel and it will be available in the config file.

Please let us know if we are on the same page.

**Comment by aparveen** [comment]
FYI @skrishn

**Comment by aparveen** [comment]
> @aparveen
> 
> As per our discussion here are the changes that we will be doing :
> 
> * The auto refresh parameter default value will be changed from `false `to `true`. This way if the layer has refresh interval set, all the users will see an auto refresh in the application after specified time interval.
> * The auto refresh parameter will be removed from the configuration panel and it will be available in the config file.
> 
> Please let us know if we are on the same page.

@ashishchoure, Also, you are going to add the fix for console error in tomorrow's code drop, right?

**Comment by ashishchoure** [comment]
@aparveen 

Yes, we will be adding a fix for console error along with other changes.

**Comment by skrishn** [comment]
verified in qa
