### ISSUE TITLE
Add message for users using deprecated browser

### ISSUE THREAD

**Issue by aparveen** [Esri/crowdsource-manager#309]
We need to add a message for using deprecated browser.
Here are browser icon files we needed to show: 
[Browser icons.zip](https://github.com/Esri/crowdsource-manager/files/5547139/Browser.icons.zip)

**Requirements for CT:**

1. Detect if user's browser is IE11 or Edge Legacy
2. If detected display one of the following messages:

**For ArcGIS Online:**

You are using a browser that is deprecated. Some parts of this application may not work optimally or at all in this browser. Support for this browser will be discontinued in the future.

Please use the latest versions of Google Chrome, Mozilla Firefox, Apple Safari, or Microsoft Edge.

For more information on browser support, see our documentation. Provide your feedback through GeoNet, the Esri Community. <link to https://community.esri.com/community/gis/web-gis/arcgisonline>

(show supported browser icons here)

**For Enterprise:**

You are using a browser that is no longer supported. Some parts of this application may not work optimally or at all in this browser.

Please use the latest versions of Google Chrome, Mozilla Firefox, Apple Safari, or Microsoft Edge.

(show supported browser icons here)

3. Message should be dismissible and allow user to continue to the app.

**Comment by aparveen** [comment]
@CTLocalGovTeam we need to add this message in this release and need to have a code drop before November 24th for the string to be translated, could you please assess the level of effort? Thanks so much.

**Comment by aparveen** [comment]
@CTLocalGovTeam, here is what it looks like in WAB. Also could you please try this new safari icon?
[safari_new.zip](https://github.com/Esri/crowdsource-manager/files/5556398/safari_new.zip)

![image](https://user-images.githubusercontent.com/10148401/99454808-c8fe7400-28db-11eb-86c5-237e57922cbc.png)

**Comment by ashishchoure** [comment]
### Dev Checklist : 
Items ​ | Is required​ | Status | Comments​
-- | -- | -- | --
Required NLS change?​ | Yes | Done  | ​
Required Backward compatibility​? | No | NA |  
Required 508​? | No | NA  |  
Need Sanitize?​ | No | NA  | 


### Impact Analysis Report : 

Impacted Areas | Comments
-- | --
Have Configuration changes?​ | No
Have Runtime changes?​ | Yes
Impact on RTL | Yes
Message for deprecated browser | The code change for this implementation will have an impact on whether the deprecated message is being shown when running the application in IE browser. The message should be shown only for Internet Explorer and not for other browsers. 

​

**Comment by skrishn** [comment]
verified in qa
