### ISSUE TITLE
Manager auto refresh functionality to behave like web map

### ISSUE THREAD

**Issue by aparveen** [Esri/crowdsource-manager#314]
We provided the option to automatically refresh app during last release https://github.com/Esri/crowdsource-manager/issues/304,
but we want manager to behave like map viewer when auto refreshing. the app should not be refreshed unless there is an update (feature or attribute) in the layer.

**Comment by ashishchoure** [comment]
### Dev Checklist :

Items ​ | Is required​ | Status | Comments​
-- | -- | -- | --
Required NLS change?​ | No |   | ​
Required Backward compatibility​? | Yes |   |  
Required 508​? | No |   |  
Need Sanitize?​ | No |   | ​


### Impact Analysis Report : 

Impacted Areas | Comments
-- | --
Have Configuration changes?​ | No
Have Runtime changes?​ | Yes
Impact on RTL | No
Refresh functionality | The code changes for this change will have an impact on how the application auto-refreshes. The application should auto refresh only when the refresh interval is set on the layer in web map and the layer's content is being refreshed in the backend **(Layer has some features which are added/deleted/updated)**
Filter (Column filter and Search filter) | The column filter and search filter should be retained
Feature selection | The feature selection should be retained
Edit mode | The application should not auto-refresh when the user is in edit mode. 
Auto-refresh after coming out from edit mode **(If the layer is updated)**| If the layer is being updated in the backend when the user is in edit mode then the layer should be refreshed immediately once the user comes out of the edit mode

**Comment by aparveen** [comment]
@ashishchoure One thing I notice that, if multiple records are selected, it automatically goes to editing mode, right? in that case the map and table should not refresh, but I see the map and table is refreshing, could you please take a look at it?

**Comment by ashishchoure** [comment]
@aparveen 

Could you please share the application and webmap?

**Comment by ashishchoure** [comment]
@aparveen 

As per our discussion,
- The manager application will not update the state of the table when the application is in edit mode, however, the layer on the map will be auto-updated as this happens from the backend.
- Once the application is in edit mode and the layer updates in the backend, we will update the state of the layer and application when the user comes out of the edit mode.

Please let me know incase of any other information.

**Comment by aparveen** [comment]
Verified in qa
