### ISSUE TITLE
Sorting removed after edit

### ISSUE THREAD

**Issue by karmstro77** [Esri/crowdsource-manager#324]
When sorting records by a field, if you then select a record and make an edit to it, hitting the save button will remove all the sorting in the table. This prevents users from easily finding records to edit and having to hit the sort button after every edit.

**Comment by aparveen** [comment]
@CTLocalGovTeam could you please assess the issue for level of effort and risk?

**Comment by sumitzarkar** [comment]
@aparveen 

We will analyze this and  would share the details soon with you

**Comment by aparveen** [comment]
@skrishn test case

**Comment by sumitzarkar** [comment]
### Dev Checklist


Items ​ | Is required​ | Status | Comments​
-- | -- | -- | --
Required NLS changes?​ | No  | NA  | ​
Required Backward compatibility​ | No  | NA  | ​
Required 508​ | No  | NA  | ​
Need Sanitize?​ | No  | NA  | ​
___

### Impact Analysis Report

Impacted Areas | Comments
-- | --
Have Configuration changes?​ | No
Have Runtime changes?​ | Yes
Impact on RTL | No
Sorting should be maintained | 1. After Edit <br/> 2. After Using 'Show Selected'/'Show all' records button <br/> 3. After applying filter <br/> 4. After Auto refresh <br/> 5. After Manual refresh 
Sorting should be cleared|  After changing the layer from webmaplist

**Comment by aparveen** [comment]
@sumitzarkar seeing an issue, when auto refresh is on after edit sorting order is not maintained. Here is a test app https://stategovernment.maps.arcgis.com/apps/CrowdsourceManager/index.html?appid=0bdcd42a7ec04821acb5c645b2603887. I think you have an account in this org. Please let me if can't access it.

**Comment by sumitzarkar** [comment]
@aparveen 

We are able to access this app. As this app is in AGOL we have old code in it and hence you are able to see this issue.

Lets discuss if we are missing anything.

**Comment by sumitzarkar** [comment]
@aparveen 

As discussed on the call, only When you sort by ObjectId field and if auto refresh is on after edit sorting order is not maintained. This is due to a functionalty where we need to show the latest feature on top, we sort it by ObjectId field in descending order. Hence the ascending sorting on objectid field is not maintianed after auto refresh/edit.

**Comment by aparveen** [comment]
Verified
