### ISSUE TITLE
Multiple record selection after sorting is selecting extra records

### ISSUE THREAD

**Issue by aparveen** [Esri/crowdsource-manager#325]
@CTLocalGovTeam  also noticed another issue with sorting, if I sort and then try to select multiple records (hold down shift), it selects a bunch of extra records. Could you please look into this as well for 9.3?

**Comment by aparveen** [comment]
FYI @skrishn test case

**Comment by sumitzarkar** [comment]
### Dev Checklist


Items ​ | Is required​ | Status | Comments​
-- | -- | -- | --
Required NLS changes?​ | No  | NA  | ​
Required Backward compatibility​ | No  | NA  | ​
Required 508​ | No  | NA  | ​
Need Sanitize?​ | No  | NA  | ​
___

### Impact Analysis Report

Impacted Areas | Comments
-- | --
Have Configuration changes?​ | No
Have Runtime changes?​ | Yes
Impact on RTL | No
Selection functionality  | Entire functionality for Shift + selection

**Comment by aparveen** [comment]
Verified
