### ISSUE TITLE
Sort order should not reset in CS Manager app when using OBJECTID field for sorting

### ISSUE THREAD

**Issue by aparveen** [Esri/crowdsource-manager#327]
If we sort based on OBJECTID field, after saving edits, Manager sort the table back in descending order. Please see the screen capture of this behavior.
We should not reset the sort at any time after the edit is made. If an user intentionally set a sort order, we should not reset it on them even if they have refresh enabled and the layer is updated.. With editor tracking enabled I can always go back and change the sort order on creation date to get the newest records.
![CSManagerSortIssue](https://user-images.githubusercontent.com/10148401/133518593-641e8b97-9301-4eed-a142-6d3337826302.gif)

**Comment by sumitzarkar** [comment]
@aparveen 

### Dev Checklist


Items ​ | Is required​ | Status | Comments​
-- | -- | -- | --
Required NLS changes?​ | No  | NA  | ​
Required Backward compatibility​ | No  | NA  | ​
Required 508​ | No  |  NA | ​
Need Sanitize?​ | No  | NA  | ​
___

### Impact Analysis Report

Impacted Areas | Comments
-- | --
Have Configuration changes?​ | No
Have Runtime changes?​ | Yes
Impact on RTL | No
Runtime Changes | 1. Whenever sorting is not applied on any column, features should be sorted in descending order of objectId (newest on top) <br/> 2. Sorting on any column including object id should be maintained <br/> 3. Test sorting Asc/Desc on objectid field

**Comment by aparveen** [comment]
Verified
