### ISSUE TITLE
Crowdsource Manager does not show filtering option when the filter is set on new map viewer

### ISSUE THREAD

**Issue by aparveen** [Esri/crowdsource-manager#334]
Crowdsource Manager does not show filtering option when the filter is set on new map viewer. I was doing some testing on the new map viewer filtering and found out that the “Ask for value” option is not available in the New map viewer, Ask for Values in the filter UI of the Classic Map Viewer was removed from the New Map Viewer (or rather, not added to it). I believe Manager's filtering is dependent on this parameter.
![image](https://user-images.githubusercontent.com/10148401/153309610-6d7431da-78a1-45ea-b398-e94358e550c3.png)

Here is a test app:
https://sg-em-devext.mapsdevext.arcgis.com/apps/CrowdsourceManager/index.html?appid=cfaf77cb66a5481ea4e7dd16b52a3b1b

**Comment by aparveen** [comment]
@sumitzarkar Could you please investigate this issue and discuss the findings with @LindsayThomas and @skrishn

**Comment by sumitzarkar** [comment]
@aparveen @LindsayThomas  @skrishn 

We have analyzed this issue and here are our findings:

- Filter functionality was implemented in CSM according to the details in the ticket - https://github.com/Esri/crowdsource-manager/issues/99
- App is designed to show only those filters which have 'Ask for Values'. Ref of the previous discussion - https://github.com/Esri/crowdsource-manager/issues/99#issuecomment-179956976
- The new Map Viewer is currently not supporting this 'Ask for values' feature - [Ref Link](https://doc.arcgis.com/en/arcgis-online/reference/limitations-and-compatibility-mv.htm)
 ![image](https://user-images.githubusercontent.com/9443956/153342235-f22c2cf1-1ae2-47ae-baed-4c97162ecf37.png)
- We depend on the information which we find in the operational layer details of a webmap which helps us in showing filter icons to only those specific columns which are involved in filtering and allow user to fiter it with user values at runtime.
- As this feature is not yet implemented in New Mapviewer we don't see a way to support this functionality in Manager APP.
- We can get AGOL team's input regarding the implementation of this feature in New Mapviewer and then based on their input we can plan. 
- If this functionality is not going to be added at all we may have to find an additional way to support it in CSM. If this is going to be added soon we can mark this as a known limitation for now.

Please let us know your thoughts on this

**Comment by skrishn** [comment]
@sumitzarkar: Thank you for looking into this. Let me connect with the team, and get back to you soon.

**Comment by LindsayThomas** [comment]
@skrishn @sumitzarkar we are waiting on an answer from the AGOL team on whether or not interactive filter capability is on the roadmap. We will sync with you once we know.

**Comment by LindsayThomas** [comment]
@sumitzarkar The development is not planning on adding the Interactive/prompt for values filter to the new map viewer. 

Are we able to look at additional option to allow the application to work correctly without additional configuration on the users part?

**Comment by sumitzarkar** [comment]
@LindsayThomas 

We are analyzing all possibilities to allow the application to work without additional configuration. Will get back to you with all the feasible possibilities.

Are we looking to fix this for AGOL 10.1 release?

**Comment by LindsayThomas** [comment]
@sumitzarkar 

> @LindsayThomas
> 
> We are analyzing all possibilities to allow the application to work without additional configuration. Will get back to you with all the feasible possibilities.
> 
> Are we looking to fix this for AGOL 10.1 release?
We would like too. But if the LOE and Risk are high then we may push till 10.2.

**Comment by sumitzarkar** [comment]
@LindsayThomas 

>Are we looking to fix this for AGOL 10.1 release?
We would like too. But if the LOE and Risk are high then we may push till 10.2.

LOE and Risk are high for this change, let's push this for 10.2. it would need a good amount of testing as well

**Comment by aparveen** [comment]
@sumitzarkar Is there a way to make this change for 4.x viewer maps only, 3x viewer maps where ask for value is enabled won't be  impacted?

**Comment by sumitzarkar** [comment]
@aparveen  We need to chek if we can get any details to distinguish and identify in which mapViewer the webmap is created. Will analyze this and will share the details.

**Comment by sumitzarkar** [comment]
@aparveen 

Here are our findings to distingush between Map Viewer and Classic Map Viewer;
 - We can use "authoringApp" property to distinguish between webmap created in Map Viewer Classic and new Map Viewer. 
 -  When map is created or edited in **Map Viewer Classic** "authoringApp" is set to  "**WebMapViewer**" 
 - And, for new Map Viewer "authoringApp" is set to "**ArcGISMapViewer**"
 
 Could you check this with AGOL team if our unerstanding is correct

**Comment by aparveen** [comment]
@sumitzarkar I reached out to AGOL team and they confirmed that this property is reliable for distinguishing between the two map viewer maps. Could you please update the issue about the backward compatibility issue we could see if we don't distinguish between these two?

**Comment by sumitzarkar** [comment]
@aparveen 

- With the current implementation in production we provide the option to change the filter value in CSM app only when 'Ask for value' is enabled

- As an implementation of this ticket, we decided to show filters to each field that is involved in Definition Expression (excluding date fields, and some filtering conditions that cannot be honored ).
- After the Implementation of this ticket user can change the filter values for any field involved in the definition expression which is different from the previous implementation where the user can only change the values of the filter for fileds where  'Ask for values' is enabled, and cannot change the filter value for any other field which is involved in definition Expression.
- This could be a major difference in the app behavior where the user will be allowed to change the value for filters although as an admin you would like to restrict to not changing those filter values.

- And, this issue will still be there if we distinguish between the map viewers or not. 


**Example:**
-  In the webmap filter is applied on the layer for field Status = 'In Progress' so that users can see only those features in the layer which have 'In Progress' status. 
- With the current app in production users don't have an option to change this filter from the CSM APP and the user can only work on the features with the status as 'In Progress'
- After implementation of this ticket user will get an option to change the filter value for the status field as it is involved in definition expression and now the user can see any features in CSM app.

**Comment by aparveen** [comment]
@sumitzarkar could you please update this issue with clarified discussion we had this morning. We are good with this approach as long as it does not break backward compatibility.

**Comment by sumitzarkar** [comment]
@aparveen 

>could you please update this issue with clarified discussion we had this morning. We are good with this approach as long as it does not break backward compatibility.

As discussed on the call - With the implementation of this new change, filters will be available for user on the columns only in New Map Viewer. So from backward compatibility point of view for the apps with old map viewer we don't see any functional impact.

**Comment by sumitzarkar** [comment]
@aparveen 

- We observed that the old map viewer does not contain **'include'** and **'exclude'** filtering conditions. However, these conditions are present in a new map viewer.
  ![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/9443956/167677873-376e33b4-1bc1-461c-9fc2-c4c13622f7b9.png)

- In **'include'** and **'exclude'** filtering conditions users can select multiple values but in the Manager App we don't have any provision to select multiple values. 
- So we cannot support **'include'** and **'exclude'** filtering conditions along with the current implementation of CSM.
- If we need to support these filtering conditions at runtime we may have to create a multi-select dropdown in filtering controls and this is not considerd under current scope of this ticket.

**Comment by aparveen** [comment]
@sumitzarkar I think we are good with not having the new functionalities. So the 4.x map viewer filtering functionality will have parity with 3.x map viewer except the "Ask for value" right?

**Comment by sumitzarkar** [comment]
@aparveen 

### Dev Checklist



Items  | Is required | Status | Comments
-- | -- | -- | --
Required NLS changes? | Yes | - |
Required Backward compatibility | Yes | - |
Required 508 | No | - |
Need Sanitize? | No | - |




### Impact Analysis Report



Impacted Areas | Comments
-- | --
Have Configuration changes? | No
Have Runtime changes? | Yes
Impact on RTL | No
Runtime impacts | 1. Test by applying different filters on different field types in the new web map viewer.<br>2. The filter icon should be shown on the column on which filers are applied.<br>3. Filter icon should not be shown for date,Blank/Not Blank and include/exclude filters.<br>4. Test with "Apply default filters automatically" configuration settings in the filters tab for CSM App.<br>5. If the web map is created in the old web map viewer then the application for that web map should work as before.

**Comment by aparveen** [comment]
@sumitzarkar In Manager filter enhancement, I can see the filter and default choice is value, In 3.x maps it always shows the unique value, do we need to show these two choices?
![image](https://user-images.githubusercontent.com/10148401/169599393-813f0147-7a1b-41fb-9659-aabbf9689300.png)
in 3.x maps it looks like the below screenshot
![image](https://user-images.githubusercontent.com/10148401/169599567-231ab41c-314b-4ba6-a392-f0eb028e7b1b.png)

**Comment by sumitzarkar** [comment]
@aparveen 

- Whenever we have domain fields we see only a dropdown to select the value. And, for other fields, we show both the options in 3.x as well as 4.x
- In the above example for 3.x status field must have a domain defined and hence we see an only dropdown 
- And for 4.x example the field city seems to be non domain and hence both the options (Value and Unique) are shown.

For e.g. In the below screen capture Text Field is non domain and we can see both options whereas for TextFieldCoded is domain and we see only one option (dropdown)
![CSM334](https://user-images.githubusercontent.com/9443956/169788638-8e191d84-962f-4496-99c3-9c69eae3cbce.gif)

Please check and let us know. If you still see any issues please share the app link to reproduce the issue.

**Comment by skrishn** [comment]
verified in dev

**Comment by aparveen** [comment]
@sumitzarkar seeing a minor issue with the filter icon, if when scrolling down the table the filter icon is disappearing, it appears back again when scroll back to the top again, the table header is there just the icon is disappearing, is this expected?
![CSManager_filterIconVanishes](https://user-images.githubusercontent.com/10148401/172258935-ee96e5f4-3dc8-4b7d-bb31-d06ab6b26270.gif)
?

**Comment by sumitzarkar** [comment]
@aparveen 

Good Catch 👍 
We are able to reproduce this issue, and this is due to the floating header. We have a floating header in the table which is shown on scrolling the table content and we missed enabling the filter icons on this floating header. 

We have identified the root cause and we are working on it, we will deliver the fix soon.

**Comment by skrishn** [comment]
verified in qa
