### ISSUE TITLE
Crowdsource manager is not working with new map viewer map after adding a layer.

### ISSUE THREAD

**Issue by aparveen** [Esri/crowdsource-manager#341]
The user has an old CS Manager app, recently they added a new layer using new map viewer, saved it and the app does not load any more, I see a console error.
Test app: https://ess.maps.arcgis.com/apps/CrowdsourceManager/index.html?appid=2aec901e916a4868b4ecb19b5924494c

![image](https://user-images.githubusercontent.com/10148401/169907124-78a4846a-b672-4907-8e72-e38c47b4f3f7.png)

**Comment by aparveen** [comment]
@sumitzarkar could you please take a look at this issue and assess the LOE?

**Comment by sumitzarkar** [comment]
@aparveen 

We have analyzed this issue and here are our findings:
- In Webmap settings, if the search is enabled and some layers are added for search, then in CSM when a layer is selected  and if it is added for search in webmap then the search box will be displayed in the header as shown in the below screenshot
 ![image](https://user-images.githubusercontent.com/9443956/170065934-4c4358eb-f60b-4a43-b7e5-a46bab32ddf5.png)
- So The CSM app checks if search is enable by chechink application properties from webmap itemInfo (_this.itemInfo.itemData.applicationProperties.viewing.search.enabled_)
- If the search is enabled we try to acess the layers(array of layers) property form search object(_this.itemInfo.itemData.applicationProperties.viewing.search.layers_)
- We observed that when a search is enabled on  any **layer ** in the webmap, and if that layer is deleted from the New Map viewer then the Search property is still enabled but the layers array becomes undefined
- As discussed on the call we will add the check to see if the layers array is valid or not in CSM.  However, we think this needs to be handled in Map Viewer also so as to avoid any issues in other applications.

We have fixed this issue and we will deliver it in the next code drop.

**Comment by aparveen** [comment]
@sumitzarkar @sandhyakurumanale-ct I am seeing the same issue after adding a new layer (search is not enabled) which is not shared to the group. After layer the layer to the group it works as expected, I will log in an issue for CT to look at, my expectation was if I add a layer that is not part of the group Manager will only show the layer that is shared and not become unresponsive.
Test app: https://stategovernment.maps.arcgis.com/apps/CrowdsourceManager/index.html?appid=e064623afe294dcd93c3be1f68b21ebf

**Comment by sandhyakurumanale-ct** [comment]
@aparveen 

### Dev Checklist

Items ​ | Is required​ | Status | Comments​
-- | -- | -- | --
Required NLS change?​ | No |   | ​
Required Backward compatibility​? | No |   |  
Required 508​? | No |   | ​
Need Sanitize?​ | No |   | ​

### Impact Analysis Report


Impacted Areas | Comments
-- | --
Have Configuration changes?​ | No
Have Runtime changes?​ | Yes
Impact on RTL | No
Runtime changes |1.In Web map settings, if the search is enabled and some layers are added for search then the application should be loaded successfully after deleting the search layers in the new map viewer <br>2.In Web map settings if the search is disabled which was previously enabled, the application should be loaded successfully after adding  the new layers in the new map viewer

**Comment by aparveen** [comment]
@sumitzarkar I am seeing the same error in QA, test app: https://sg-em-qaext.mapsqa.arcgis.com/home/item.html?id=c44da620405040619990f4119a4514a7
Test map: https://sg-em-qaext.mapsqa.arcgis.com/home/item.html?id=564bc312fe564b2c857110f78151e5d2
I deployed the Special Event Permit and Operations solution, open the special permit map, add a layer that is not part of the group and popup is enabled for the added layer saved it but the won't load and I am seeing the same console error.

**Comment by aparveen** [comment]
![image](https://user-images.githubusercontent.com/10148401/174410568-5704532c-c716-43d7-8d5a-2f35d2a9a599.png)

**Comment by sumitzarkar** [comment]
@aparveen 

The above mentioned issue is same as https://github.com/Esri/crowdsource-manager/issues/344#issuecomment-1158520084

**Comment by aparveen** [comment]
Verified in QA
