### ISSUE TITLE
Reference Layer is not showing in the app

### ISSUE THREAD

**Issue by aparveen** [Esri/crowdsource-manager#350]
User is having some trouble with getting reference layers to show up. she configured it to show reference layers in the options tab within the app, it shows in the legend but will not draw. A link to the application is below in case that helps.
App: https://gnrc.maps.arcgis.com/apps/CrowdsourceReporter/index.html?appid=ca5d29c5a000423393a9c895aad18d89
Maps:

https://gnrc.maps.arcgis.com/apps/mapviewer/index.html?webmap=e77973abca25433a99e05c1908f6284a

https://gnrc.maps.arcgis.com/apps/mapviewer/index.html?webmap=c0f726b91409417c9d3c47ee30b25eb5

The congested by year and top crash areas are the reference layers and the map was created in new map viewer

**Comment by aparveen** [comment]
@sumitzarkar

**Comment by sumitzarkar** [comment]
## Dev Checklist


Items ​ | Is required​ | Status | Comments​
-- | -- | -- | --
Required NLS changes?​ | No   |   | ​
Required Backward compatibility​ | No  |   | ​
Required 508​ | No  |   | ​
Need Sanitize?​ | No  |   | ​
___

## Impact Analysis Report

Impacted Areas | Comments
-- | --
Have Configuration changes?​ | No
Have Runtime changes?​ | Yes
Impact on RTL | No
Runtime impact | Test for Refrence layers added as feature layer or a featureCollection layer

**Comment by skrishn** [comment]
verified in qa
