### ISSUE TITLE
Crowdsource manager is not showing any records after the map was opened in new map viewer

### ISSUE THREAD

**Issue by aparveen** [Esri/crowdsource-manager#359]
One of our team member reported that he opened the map in new map viewer, didn't save then in classic map viewer he changes one of the arcade expression, after that the records are not showing, he went back and switched the expression back to its original state but still manager is not showing any records, there is no console error either
Test App: https://statelocaltryit.maps.arcgis.com/apps/CrowdsourceManager/index.html?appid=5050bc075de445f5b445e87687032775
Test map: https://statelocaltryit.maps.arcgis.com/home/webmap/viewer.html?webmap=efda505a6ad54b2796a8c77bd6f93848

**Comment by aparveen** [comment]
@swaruparaut could you please take a look at it? I could'nt assign Sumit and I think he mentioned that you started working with Manager (I may be wrong)

**Comment by sumitzarkar** [comment]
@aparveen 

We don't see any records being returned on rest end for the applied filter

https://services6.arcgis.com/Pu6Fai10JE2L2xUd/arcgis/rest/services/Requests_sign_a8a87023f680401d83827686f1695ae7/FeatureServer/0/query?f=html&where=(publicview%20%3D%20%27Yes%27)%20AND%20(pocfirstname%20LIKE%20%27%25John%25%27)%20AND%20(poclastname%20LIKE%20%27%25Smith%25%27)%20AND%20(status%20%3D%20%27Submitted%27)%20AND%20(assignedto%20LIKE%20%27%25Public%20Works%25%27)%20AND%20(locdesc%20LIKE%20%27%25Main%20St%25%27)%20AND%20(details%20LIKE%20%27%25Sign%25%27)%20AND%20(pocemail%20LIKE%20%27%25jsmith%40email.com%25%27)%20AND%20(pocphone%20LIKE%20%27%25555-5555%25%27)%20AND%20(notes%20LIKE%20%27%25ABC%25%27)%20AND%20(resolution%20LIKE%20%27%25ABC%25%27)%20AND%20(reqtype%20%3D%20%27Damaged%20or%20Missing%20Sign%27)&returnGeometry=true&spatialRel=esriSpatialRelIntersects&outFields=*&maxRecordCountFactor=4&outSR=102100&resultOffset=8000&resultRecordCount=8000&cacheHint=true

**Comment by aparveen** [comment]
Sumit if this parameter is unchecked I was expecting to see all the records in manager
![image](https://user-images.githubusercontent.com/10148401/233155615-e76c19bf-8bc8-47eb-92f1-dde5edd4d402.png)

**Comment by sumitzarkar** [comment]
@aparveen 

'Apply default filters automatically' parameter is only used for filters where ask for value is enabled. Static filters will always be applied on csm app load and client's webmap's filters are all static in nature and no results obtained in app.

![image](https://user-images.githubusercontent.com/9443956/233288442-a5f064bd-9cc2-4104-97b3-339332c290c3.png)

**Comment by aparveen** [comment]
No action needed for this one.
