### ISSUE TITLE
Change graphic marking selected feature in map

### ISSUE THREAD

**Issue by allisonmuise** [Esri/crowdsource-manager#39]
Please use a plain cyan square around the selected feature, rather than the current cyan square with crosshairs.

**Comment by CTLocalGovTeam** [comment]
@allisonmuise 

OK.  We will implement this in the next release.

**Comment by allisonmuise** [comment]
@ScottOppmann : Are you ok with the plain rectangle?
cc @LindsayThomas

**Comment by allisonmuise** [comment]
verified
