### ISSUE TITLE
Allow app to be public

### ISSUE THREAD

**Issue by allisonmuise** [Esri/crowdsource-manager#40]
Currently the app prompts for credentials even if it, and the content displayed in it, are public.

Only prompt for credentials if the application or the content in it require credentials in order to display.

**Comment by allisonmuise** [comment]
In cases where the app is public but the group and all items are private, display the message 'Please Sign In'. 

If there are no items to display once the user is signed in, display the current 'no items' message.

**Comment by CTLocalGovTeam** [comment]
@allisonmuise There may be a case where app and group are public, but all items are private. In this case, there is no way to find out if group contains any items without signing in. We'l have to display the 'no items' message. Please confirm.

**Comment by allisonmuise** [comment]
Yes, this is correct

**Comment by allisonmuise** [comment]
along with this - please remove the custom preview option that was put in at the end of last release. Once we can make this app public we will be able to provide a full try-it-live/demo experience.

**Comment by allisonmuise** [comment]
preview options moved to #51

**Comment by allisonmuise** [comment]
verified
