### ISSUE TITLE
Change Selection Options menu graphic

### ISSUE THREAD

**Issue by allisonmuise** [Esri/crowdsource-manager#41]
I will provide a new graphic for this menu

**Comment by CTLocalGovTeam** [comment]
@ allisonmuise Could you please provide the graphic for this menu?

**Comment by allisonmuise** [comment]
pushing to next release

**Comment by allisonmuise** [comment]
New graphic (it's white):
![settings](https://cloud.githubusercontent.com/assets/2752195/8582693/504c325c-257d-11e5-800a-db8e6ed670e9.png)

Please add a small arrow to the right of the icon to indicate that it's a menu. Clicking the arrow or the icon should open the menu.
![new-icons](https://cloud.githubusercontent.com/assets/2752195/8582714/66d63392-257d-11e5-87b9-791e83fdf40e.jpg)

**Comment by allisonmuise** [comment]
verified
