### ISSUE TITLE
Change View Options menu icon

### ISSUE THREAD

**Issue by allisonmuise** [Esri/crowdsource-manager#42]
I will provide a new graphic for this menu

**Comment by CTLocalGovTeam** [comment]
@ allisonmuise Could you please provide the graphic for this menu?

**Comment by allisonmuise** [comment]
Pushing to next release

**Comment by allisonmuise** [comment]
Graphic:
![settings](https://cloud.githubusercontent.com/assets/2752195/8582642/fed91ed0-257c-11e5-8435-d59aa04b7d37.png)

Please add a small arrow to the right of the icon to indicate it is a drop-down. Clicking the icon or the arrow should expand the menu.
![new-icons](https://cloud.githubusercontent.com/assets/2752195/8582655/1cce21e2-257d-11e5-8745-7ff931439761.jpg)

**Comment by allisonmuise** [comment]
verified
