### ISSUE TITLE
remove geographic filtering

### ISSUE THREAD

**Issue by allisonmuise** [Esri/crowdsource-manager#45]
remove geographic filtering from the table view. All features should be displayed regardless of what is in the current extent.

Update the table and map on a timed interval, or when a map/layer is loaded only.

**Comment by allisonmuise** [comment]
Table should be sorted by OID - displaying features from most recent to oldest. The current sorting options will not allow users to return to this sort order after sorting by another field. 
@CTLocalGovTeam : Please suggest a way to allow users to sort this way.

Auto refresh should be disabled while editing

Selected features should continue to be selected following refresh.

**Comment by allisonmuise** [comment]
In place of auto refresh, please add a manual refresh button to the UI. Please share a mockup of the proposed location before adding this button to the app.

**Comment by CTLocalGovTeam** [comment]
@allisonmuise 
Here is a mockup for the proposed refresh layer button.

![image](https://cloud.githubusercontent.com/assets/2959186/7200198/49aac274-e518-11e4-8d44-da7693f4cca2.png)

**Comment by allisonmuise** [comment]
Please proceed with this design

**Comment by allisonmuise** [comment]
verified
