### ISSUE TITLE
accessing details view

### ISSUE THREAD

**Issue by allisonmuise** [Esri/crowdsource-manager#47]
open the details view for the currently highlighted feature. Clicking (not selecting via check box - #43 ) another record in the table should switch the details content to that of the just-clicked record.

**Comment by allisonmuise** [comment]
Clarification:
'View  Details' should be related to the active feature, not the selected feature(s)
Clicking the 'View Details' Button should open the details of the active feature. 
Changing the active feature should update the content shown in the Deatils View window.

@CTLocalGovTeam Please confirm that his clarifies this issue.

**Comment by CTLocalGovTeam** [comment]
Yes. It clarifies this issue and we will implement it in next release.

**Comment by CTLocalGovTeam** [comment]
@ allisonmuise We will implement this in sprint 2 till then the existing functionality will be retained as is.

**Comment by allisonmuise** [comment]
verified
