### ISSUE TITLE
use group thumbnail for app icon

### ISSUE THREAD

**Issue by allisonmuise** [Esri/crowdsource-manager#48]
If the group has a thumbnail, this thumbnail should be displayed as the app icon in the top left corner of the app.

If an image is provided during the configuration of the app it should override the group thumbnail.

If the group does not have a thumbnail and no image is provided during configuration, use the current graphic as a fall-back.

**Comment by allisonmuise** [comment]
remove default paths in configuration file

**Comment by CTLocalGovTeam** [comment]
@ allisonmuise We have removed default path from the config.js. We will include it in sprint 1.

**Comment by allisonmuise** [comment]
Thanks! verified.
