### ISSUE TITLE
Configurable option for color of active feature

### ISSUE THREAD

**Issue by allisonmuise** [Esri/crowdsource-manager#49]
Add a configuration panel item for choosing the color of the table row and selection graphic for the active feature. 

Selected features will always be cyan.

**Comment by CTLocalGovTeam** [comment]
OK. We will add item in the configuration panel to select color, the selected color will be used to highlight both active row in the table and active feature on the map. 
We will implement this in the next release.

**Comment by allisonmuise** [comment]
I see this value in the default.js, but it is not in the configuration-panel.js
Please expose this color through the configuration panel in such a way that it will not break previously configured applications.

**Comment by CTLocalGovTeam** [comment]
@allisonmuise 
It is already exposed in configuration-panel.js
Here is a diff from the pull request. 
A default value is also provided in defaults.js for this parameter.
Are you able to see this in the configuration panel when you click 'Configure app'?

![image](https://cloud.githubusercontent.com/assets/2959186/7411163/f49e4fe0-ef52-11e4-9286-ccf3106189b0.png)

**Comment by allisonmuise** [comment]
yup - now I see it :)
