### ISSUE TITLE
Update map/layer list UI to match Reporter

### ISSUE THREAD

**Issue by allisonmuise** [Esri/crowdsource-manager#50]
This work has been discussed previously and is included in the current sprint plan. I'm adding it here as well for tracking purposes.

**Comment by allisonmuise** [comment]
Because the list is always visible in this app, can we treat is more similar to how we are the Reporter issues list? 
By this I mean:
- When a maps with 1 editable layer is selected: I like the highlight in theme color. Can we also leave the map highlighted in white like it is on hover?
- When a map with multiple editable layers is selected: Outline the map & layers with the theme color (current behavior) AND highlight the selected layer in white as it is on hover?

**Comment by CTLocalGovTeam** [comment]
@allisonmuise, @ScottOppmann, @LindsayThomas   Ok. 
1. When a map with 1 editable layer is selected then it will be outlined with theme color and will remain highlighted with white background as shown below.

![image](https://cloud.githubusercontent.com/assets/2959186/7451468/b3130a60-f26e-11e4-82a0-d6be416811bc.png)


2. When a layer is selected from a map having multiple layers then outline of theme color will be retain and both map and selected layer will be highlighted with white background as shown below.

![image](https://cloud.githubusercontent.com/assets/2959186/7451472/c1d88930-f26e-11e4-9e31-affe1870288a.png)

However when user hovers on another layer it will also be highlighted with white background. This result in showing two layers highlighted at the same time. One that is selected and another that is hovered. 

We will take forward these changes to Reporter app to maintain consistency across both the apps.

**Comment by allisonmuise** [comment]
ok

**Comment by allisonmuise** [comment]
verified
