### ISSUE TITLE
Update preview functionality 

### ISSUE THREAD

**Issue by CTLocalGovTeam** [Esri/crowdsource-manager#51]
v1 of the app displays a static preview page when 
* template is directly accessed without publishing an app from the template
* user chooses preview from "publish, preview, download" options while sharing a group

v2 of the app does not require preview page because the app will now display public content within the group. Sign in is not mandatory to access the app like in v1. Also, if user chooses to "Preview" while sharing a group, then groupid is passed as a url parameter that gets honored by the app and users will be able to see a dynamic preview of the app instead of a static html page preview. 

These are our initial thoughts to begin the discussion. Need to update this after considering all possibilities of hosted, portal, public, private, mixed group environments.

**Comment by allisonmuise** [comment]
My thoughts:

1. Preview from the template's details page (always hosted, always public. This option is only available for Esri Default templates and I will have full control over the content sharing.): 
- AGOL, connected Portal - display content from the default configuration. 
- Disconnected Portal - display existing HTML page

2. Preview when sharing group (sharing privileges of group and items should be irrelevant. If they are private the user will be signed in and browser will have access):
- AGOL, connected and disconnected Portal: Preview with group content and default config settings

**Comment by CTLocalGovTeam** [comment]
@allisonmuise,

In case of AGOL, without signing in, users can go to the app's details page and view it and everything works, i.e. the default group is displayed.

Will this release of crowdsourcing apps make it to AGOL or they will be updated in the "Early adopter templates" group? Because users who are signed in to an Org that does not allow members to search outside their Org, will not be able to find the template's details page.

In case of connected Portal, if the template is provided built into the portal, and user tries to open the app from its details page, the default configuration will spin up and try to find the group that is in AGOL and will display an error message that it could not find the group.

For disconnected portals, how do we identify if a portal is disconnected? Do you know of any property that the portal exposes to identify if its disconnected? 

Can you please let us know in which scenarios the static preview page is to be displayed?

**Comment by CTLocalGovTeam** [comment]
@allisonmuise ,

Here are the scenarios we discussed on the call today,

![image](https://cloud.githubusercontent.com/assets/2959186/7393357/dff0a79e-eeaa-11e4-8a77-d6e6ae88f05f.png)

**Comment by allisonmuise** [comment]
(numbering the use cases above from 1-7)
When app is launched from item details page:
1. ok
2. ok
3. App should be able to reach the content. I created a user account in a trial organization that does not allow non-administrators access to content outside the organization and I can still access the preview experiences for both Basic Viewer (map template) and Public Gallery (group template) even though thtey are pointing to content that exists outside my org. Manager (and Reporter) should behave the same.
4-7. Display the HTML page for both connected and disconnected portal. @MikeTschudi may be able to help with identifying apps launching in Portal vs AGOL.

**Comment by CTLocalGovTeam** [comment]
@allisonmuise, @ScottOppmann, @LindsayThomas,

Your observation for case no.3 is correct. You are able to access the preview experience because you did not sign in and try to launch the app, is this correct? 
Because the Org restrictions (cannot access public content outside org) apply only after a user has signed in. 

@MikeTschudi, 
For case nos. 4-7 we found an Org property `isPortal:true` that we can use to identify if the app is running from a portal instance. Is this ok ?
We do not need to identify if the portal is connected or disconnected, since in both cases, the static preview page will be shown.

We are planning to include this in Sprint 2. Can you please label this issue to "Sprint 2" .

**Comment by MikeTschudi** [comment]
@CTLocalGovTeam Using the ```isPortal``` property that you found is the approach recommended by the Online team

**Comment by allisonmuise** [comment]
App preview is working in AGOL-hosted apps. I am unable to test portal-hosted apps until the app is included in the Portal builds. Leaving this open and assigned to me to test once that is available.

**Comment by allisonmuise** [comment]
verified
