### ISSUE TITLE
Maintain sorting after editing

### ISSUE THREAD

**Issue by allisonmuise** [Esri/crowdsource-manager#53]
Is there a way to maintain the sort order after committing edits? If I've edited the sort field, the record can stay where it is until I re-sort, but being bounced to the top of the list and needing to re-sort after every edit is a frustrating workflow.

**Comment by CTLocalGovTeam** [comment]
@allisonmuise, @ScottOppmann, @LindsayThomas The position of edited record will remain unchanged when edits are committed. Resorting will re-position the record. This will be accommodated in sprint 2.

**Comment by allisonmuise** [comment]
Please also keep my position in the list. Currently I'm being bounced up to the top record after every edit.

**Comment by CTLocalGovTeam** [comment]
@allisonmuise 
The position of edited cell in list view will remain unchanged when edits are committed.
This will be accommodated in sprint 2.

**Comment by allisonmuise** [comment]
verified
