### ISSUE TITLE
Signing In with an Esri Named User Acct will display the First and Last Name in reporter but just the username in manager

### ISSUE THREAD

**Issue by LindsayThomas** [Esri/crowdsource-manager#54]
On Reporter -Signing In with an Esri Named User Account will display the First and Last Name of the user (For Example: Lindsay Thomas)
On Manager - Signing In with an Esri Named User Account will display the username (For Example: lind5149_lg)

Shouldn't they be the same?

**Comment by allisonmuise** [comment]
Yes - @CTLocalGovTeam : Please display FirstName LastName in Manager rather than the username.

**Comment by CTLocalGovTeam** [comment]
@allisonmuise, @LindsayThomas,
Agree. We will display the full name of the user as in reporter app.
This will be included in the upcoming release.

**Comment by allisonmuise** [comment]
verified
