### ISSUE TITLE
Accessing the Manager application in a browser that is too small appears jumbled

### ISSUE THREAD

**Issue by LindsayThomas** [Esri/crowdsource-manager#55]
On a really small browser OR on a smartphone the application icons are jumbled and the application is not usable. 

Provide a message to users OR prevent them from having this experience

![img_0002](https://cloud.githubusercontent.com/assets/2379312/7541528/24f3b8c4-f584-11e4-8b3b-adc5c139c959.PNG)

**Comment by allisonmuise** [comment]
@LindsayThomas We don't do this for any of our other non-smartphone supporting apps so I'm not sure what modified behavior you're looking to see. Should the app fail to load? Should the app present a message that says that the app would look better on a bigger browser? Should that message allow them to continue using the app if they want to?

**Comment by allisonmuise** [comment]
as designed
