### ISSUE TITLE
Signing In with an Esri Named User Account then clicking the "X"  or "cancel" gives the user a message "ABORTED"

### ISSUE THREAD

**Issue by LindsayThomas** [Esri/crowdsource-manager#59]
Signing In with an Esri Named User Account then clicking the "X" OR "Cancel button" gives the user a message "ABORTED" and the application then completely refreshes. It should just close the sigin dialog and go back to the app.

**Comment by CTLocalGovTeam** [comment]
@allisonmuise, @LindsayThomas,
Agree. Clicking cancel should just close the sign in dialog and go back to app.
This will be included in the upcoming release.

**Comment by LindsayThomas** [comment]
@CTLocalGovTeam Just to confirm Cancel and 'X' will both have the same behavior?

**Comment by CTLocalGovTeam** [comment]
@LindsayThomas @allisonmuise 
That is correct. Cancel and 'X' will both have the same effect, i.e., close the sign in dialog and go back to the app.

**Comment by allisonmuise** [comment]
verified
