### ISSUE TITLE
'Clear Selection' missing when viewing only selected features

### ISSUE THREAD

**Issue by allisonmuise** [Esri/crowdsource-manager#61]
Repro steps:
1) select several features 
2) click the Selection Options button
3) Click the 'Show Selected' option
4) Click the Selection Options button again
3) There is no option for 'Clear Selection'. Clearing the selection from here requires 3 clicks (Show All > Selection Options > Clear Selection)

Please add 'Clear Selection' to this menu. Clicking this option should show the full table and unselect all selected features.

**Comment by CTLocalGovTeam** [comment]
@allisonmuise Yes. we can do this. We'll show the full table and unselect all selected features.

**Comment by CTLocalGovTeam** [comment]
@allisonmuise 
We have implemented this and will deliver in upcoming release.

**Comment by allisonmuise** [comment]
verified
