### ISSUE TITLE
Issues with layers that use size renderers.

### ISSUE THREAD

**Issue by allisonmuise** [Esri/crowdsource-manager#65]
See a video of this behavior on box:
https://esri.box.com/s/ficahgmaazki7nfn3vkzrpsjt1940vxk

After re-editing a field the table in the same session, the field will revert back to the original value

**Comment by CTLocalGovTeam** [comment]
@allisonmuise 
We were not able to repro this. Does this occur for all layers? Can you please share a webmap.

**Comment by allisonmuise** [comment]
I am seeing this behavior or other, similar, strange behavior when editing features symbolized by color or by size. Not all layers symbolized like this have issues, and I'm not seeing it on any layers that use other renderers.

For example, in this map: http://localgovtest.maps.arcgis.com/home/webmap/viewer.html?webmap=5144a7fb27914e9eb8bbf1e6b931229e I am seeing this behavior with the 'This line layer has attachments and comments and votes' layer when it is symbolized by size. 

When the 'AttachmentsVotesComments - Points' layer is symbolized by size, the app freezes every time I click on a row in the table. (also see the 'Blight Reports' and 'Blight Reports - Size' layers)

Both these behaviors disappear when I use a single symbol and I can reproduce them on multiple layers.

**Comment by CTLocalGovTeam** [comment]
@allisonmuise, 
We were able to repro the freeze issue on 'AttachmentsVotesComments - Points' and investigating this.
Will keep you posted on re-edit-reverts-to-original issue (still trying to repro).

**Comment by allisonmuise** [comment]
I could repro the editing issue wednesday and yesterday on two layers using FireFox and Chrome, even after clearing my cache. I rebooted my machine this morning and don't see the editing issue anymore. The freezing issue is still there, though, so I will modify the title of this issue.

**Comment by CTLocalGovTeam** [comment]
@allisonmuise,
We were able to repro and fix the freezing issue. However, for layers styled like this, we are noticing that the cyan colored selection square graphic (as well as active graphic) does not change according to symbol size. It displays the fallback symbol of a fixed size. Investigating this further.

**Comment by CTLocalGovTeam** [comment]
@allisonmuise ,
For point layers styled with 'Counts and Amounts (size)', we are not able to interrogate the size of a feature's symbol. We need this to display the selection symbol that is slightly larger than the feature's symbol. The API does not provide the size of symbols used to display the class breaks.

Due to this, for point layers styled with this option, the cyan colored selection graphic as well as active graphic will always use the fallback symbol of a fixed size.

We have started [this thread on GeoNet](https://geonet.esri.com/message/524496) for this and awaiting responses from esri/gis community.

**Comment by allisonmuise** [comment]
ok - does today's pull request include a fix for the freezing issue?

**Comment by CTLocalGovTeam** [comment]
@allisonmuise Yes the pull request V1.0 includes a fix for the freezing issue

**Comment by CTLocalGovTeam** [comment]
@allisonmuise we have identified a fix for highlighting symbols with appropriate size when layers are styled with 'Counts and Amounts (size)'.
We are ready on our side with this fix. Please let us know if you would like us to generate a pull request for both Manager and Reporter.

**Comment by allisonmuise** [comment]
verified
