### ISSUE TITLE
shortcut icons

### ISSUE THREAD

**Issue by allisonmuise** [Esri/crowdsource-manager#66]
Please use the app icon as the shortcut icon for this app, like the Reporter.
![5-28-2015 12-35-16 pm](https://cloud.githubusercontent.com/assets/2752195/7869227/37c2e300-0536-11e5-9aa1-4a2df1929eaf.png)

**Comment by CTLocalGovTeam** [comment]
@allisonmuise 
We were able to repro and fix this. Will deliver this in upcoming release.

**Comment by allisonmuise** [comment]
verified
