### ISSUE TITLE
Display of multi-line text

### ISSUE THREAD

**Issue by allisonmuise** [Esri/crowdsource-manager#67]
When text is entered into a multi-line parameter in Reporter:

![5-28-2015 1-24-40 pm](https://cloud.githubusercontent.com/assets/2752195/7870274/13275ed4-053d-11e5-97b8-306274556674.png)

The resulting text displays with the correct spacing in the Reporter details view, ArcGIS Online popups, and Manager details view:
![5-28-2015 1-26-36 pm](https://cloud.githubusercontent.com/assets/2752195/7870312/48d82752-053d-11e5-8d85-e8a824781820.png)
![5-28-2015 1-23-36 pm](https://cloud.githubusercontent.com/assets/2752195/7870339/81e5a61e-053d-11e5-8a24-edd805a44718.png)
![5-28-2015 1-23-51 pm](https://cloud.githubusercontent.com/assets/2752195/7870348/8a746c3e-053d-11e5-86e6-aa9b1acbf54e.png)

In the table of Manager, the spacing is incorrect:
![5-28-2015 1-23-43 pm](https://cloud.githubusercontent.com/assets/2752195/7870517/b284ffee-053e-11e5-8f72-85570c0ebfe2.png)

**Comment by CTLocalGovTeam** [comment]
@allisonmuise 
We were able to repro and fix this. Will deliver this in upcoming release.

**Comment by allisonmuise** [comment]
verified
