### ISSUE TITLE
Search icon in topbar is not re-enabled when all records are unselected in show selected mode

### ISSUE THREAD

**Issue by CTLocalGovTeam** [Esri/crowdsource-manager#73]
@ScottOppmann @LindsayThomas @allisonmuise 
Discovered an issue not related to enhancements for this phase of work.

Steps to reproduce:

1. Use a webmap with a layer that has layer search enabled. Observe that search icon in topbar is enabled.
2. Select some rows in table
3. Switch to selected mode. Observe that search icon in top bar gets disabled, since we cannot search in selected mode.
4. Unselect all rows one by one from table or map till all rows get removed 
7. The table now defaults to showing all rows
8. Since the table is now showing all rows, the search icon in top bar should be re-enabled. It stays disabled. This is the issue. It should get re-enabled when showing all rows.

The impact of this code fix is minor and localized.
Please let us know if you'd like this fixed.

**Comment by allisonmuise** [comment]
Yes, please fix this issue.

**Comment by allisonmuise** [comment]
verified
