### ISSUE TITLE
Update field value for all selected features

### ISSUE THREAD

**Issue by DShokes** [Esri/crowdsource-manager#75]
This functionality would allow for bulk status updates and feature assignment. It could also enable simple field calculations.

**Comment by allisonmuise** [comment]
Proposed workflow for this based on redesign work in progress:
- remove editing from table view
- on row click/select in table view, toggle to popup view in muli-purpose pane
- popup view has 2 modes (view/edit) that are sticky. If previously in edit mode, popup view will open in edit mode. if previously in view mode, popup view will open in view mode.
- if multiple features selected, media and related records view tabs are hidden and popup view toggles to edit mode. All edits performed are applied to all selected records
- before committing edits, display warning to approve batch edits to x selected features.

**Comment by allisonmuise** [comment]
See #97 and #101
