### ISSUE TITLE
Placeholder text is not displayed for search bar in IE9 browser.

### ISSUE THREAD

**Issue by CTLocalGovTeam** [Esri/crowdsource-manager#76]
@allisonmuise,
We found this issue recently in our internal testing.

Steps to reproduce:
1. Use a webmap with a layer that has layer search enabled.
2. Click on search icon
Here for IE9, the expected placeholder text is not displayed in the search bar unlike other browsers.

**Comment by allisonmuise** [comment]
@CTLocalGovTeam : What is the level of effort to resolve this, and how much risk will the fix pose to the rest of the app?

**Comment by CTLocalGovTeam** [comment]
@allisonmuise 
The level of effort for this fix is very small. The code change required for this fix is also localized and low impact. We can include this fix in the upcoming delivery this Wednesday the 19th.

**Comment by allisonmuise** [comment]
OK, please proceed.

**Comment by CTLocalGovTeam** [comment]
@allisonmuise 

This issue is also present in crowdsource reporter app. Should we go ahead and include a fix for reporter too?

**Comment by allisonmuise** [comment]
yes, please

**Comment by allisonmuise** [comment]
verified
