### ISSUE TITLE
Support for RtL languages

### ISSUE THREAD

**Issue by allisonmuise** [Esri/crowdsource-manager#78]
As mentioned during the last iteration, there are some areas where RtL support could be improved, such as: 
![9-2-2015 2-26-43 pm](https://cloud.githubusercontent.com/assets/2752195/9645133/c060213e-517e-11e5-8b2a-c48820c6971e.png)
I believe @CTLocalGovTeam  testers found some other areas as well. Please add those to this issue as well.

**Comment by CTLocalGovTeam** [comment]
@allisonmuise 
The other areas where RTL is to be supported are:
1. Webmap list to switch its position to be displayed on right hand side in RTL mode, and accordingly the table and map view should be displayed on the left hand side of the map list
2. The header panel should also switch its position in RTL. App title should be displayed on right, and header buttons for refresh, filter, views, settings, sign in, to be displayed on left.
3. Navigation controls in map view should switch position to left

**Note on RTL support in IE**  
* RTL is supported on IE only when operating system's regional language settings are changed. Changing just the browsers language settings has no effect. 
* In chrome and firefox, changing just the browser's language will display app in RTL mode. 
* Changing language using URL parameter will display in RTL mode, regardless of browser's and OS's language settings in all browsers including IE.

**Comment by allisonmuise** [comment]
@CTLocalGovTeam : Yes, these are all changes that should be made.

**Comment by CTLocalGovTeam** [comment]
@allisonmuise 

**iPads only**
Just an update that we are noticing a strange behavior only on iPads when app is run in RTL mode. 
1. When you tap to make a row 'active', it appears as if the row is not activated. You need to scroll the table horizontally to the end and back. Now you see the complete row is activated.
2. The same behavior is seen when you tap the checkbox to select a row. You need to scroll the table horizontally to the end and back to see that the row is selected/highlighted.
3. Tap to edit a row also exhibits this issue. Scroll to the end and back to see that the row is editable with textboxes and dropdowns.
4. Edit a field that has domain applied. Select any value from the dropdown. It appears as if the field is not updated as it still shows the old value. Scroll back and forth and the new value is displayed.

All functionality for activating a row, selecting a row, editing a row works fine. Its the visual feedback that is not working. This makes the app practically unusable in RTL mode on iPads.

We are investigating this and will keep you updated.

**Comment by allisonmuise** [comment]
Thank you for the update

**Comment by allisonmuise** [comment]
verified
