### ISSUE TITLE
Update to fully support web-tier secured services

### ISSUE THREAD

**Issue by allisonmuise** [Esri/crowdsource-manager#81]
https://devtopia.esri.com/WebGIS/arcgis-portal-app-templates/issues/893#issuecomment-284331

**Comment by CTLocalGovTeam** [comment]
@allisonmuise 
The app uses ArcGIS JSAPI's identity manager which abstracts all forms of authentication. Can you please describe the behavior you see with web-tier services. 

Also, can you provide more information on how the environment is set-up, i.e., how is ArcGIS Server and Portal configured. We'd have to setup the same environment here to replicate and test. 
Is the webmap created in ArcGIS Online or Portal. Are credentials stored while adding layer to webmap, etc. and any additional information to help us replicate.

**Comment by allisonmuise** [comment]
@CTLocalGovTeam : Sorry - meant to supply more info on this one. It is my understanding that this support is available in the latest boilerplate (per Matt Driscoll). The other templates that allow editing (such as Basic Viewer) have already been updated and the approach for Manager should be the same. 

This change is specific to 10.4 Portal. Do you have access to a 10.4 Portal to test this if I get you more details on the setup? If not, please make the change as best as you can based on how it's been done in Basic Viewer and we'll test on our end.

Additional info from the devtopia link above:
'The JS API to be included in 10.4 (Portal) has been updated to support sending credentials with AJAX requests to specific domains. This will allow editing of feature services secured with web-tier authentication. The templates that support feature service editing need to be updated to utilize this change.'

A related issue has code snippets that I will send via email.

**Comment by CTLocalGovTeam** [comment]
@allisonmuise,

Thanks for the additional info. Here are some observations and queries.

1. The boilerplate does seem to have code for supporting web tier security. The latest boilerplate also contains an additional config item in `config/template-config.js` called `"webTierSecurity": false`.  
Since it defaults to false, users will have to download app code, modify this item to *true* to use web tier secured services. Is this the expected approach?
2. We do not have access to 10.4 portal. So we request your help in testing this.
3. We also found that [Basic Viewer template](https://github.com/Esri/viewer) repo does not have this config item or the associate code, so we are not sure if its updated.

**Comment by allisonmuise** [comment]
@CTLocalGovTeam : It looks like this change was only made in the private Viewer repo and wasn't pushed to the public one. Here is a screenshot of the changes Kelly made in her commit that is marked as resolving this issue:
![12-1-2015 8-53-30 am](https://cloud.githubusercontent.com/assets/2752195/11507628/c1b54b14-9809-11e5-9cce-e470fd1d8a4f.png)
The same code change is visible in the Edit template (~line 485):https://github.com/Esri/edit-template/blob/master/js/template.js

Neither app seems to use the configuration parameter you've mentioned. I have asked Kelly for clarification on how/if this should be implemented.

**Comment by allisonmuise** [comment]
@CTLocalGovTeam : 
Here is Kelly's response:
Take a look at the app boilerplate for an example of using webTierSecurity. If they want to edit they’ll have to set it to true. 
https://github.com/Esri/application-boilerplate-js/blob/development/application_boilerplate/js/template.js

**Comment by MikeMillerGIS** [comment]
@CTLocalGovTeam I feel it is safe to set the variable to true as I have that code enabled in the Info Lookup at that is part of AGOL
https://github.com/Esri/information-lookup/blob/master/js/template.js#L520

**Comment by allisonmuise** [comment]
verified with colorado service from J Smith
