### ISSUE TITLE
Remove preview

### ISSUE THREAD

**Issue by allisonmuise** [Esri/crowdsource-manager#83]
preview experience in AGOL has updated to recognize the difficulty of delivering preview for portals. This file and associated code can be removed.

**Comment by CTLocalGovTeam** [comment]
@allisonmuise 
The preview experience that is implemented in Crowdsourcing Apps was similar to the MapTour template at the time, i.e., to show a static html page with information about the app.

When we look at the MapTour template now, it does not have a static preview page, instead it redirects to its documentation website (screenshot below). 

Do we want to update to a similar behavior?

![image](https://cloud.githubusercontent.com/assets/2959186/11440163/42aa1196-9526-11e5-8a61-e358f757cbf2.png)

**Comment by allisonmuise** [comment]
No, the preview experience for Manager can now be the same as Reporter. We originally needed the html page for the following reasons:
1) The app always prompted for sign in so we couldn't provide a public preview of the actual app. This has been fixed so that the app behaves the same as the majority of the templates.
2) Portal installations couldn't access the AGOL content in the app preview. This was an issue with all templates and has been addressed across all templates by the Portal team.

**Comment by CTLocalGovTeam** [comment]
@allisonmuise 
The static preview page was built to be displayed only on portals. Three conditions needed to satisfy to display the static preview page:
1. appID is not present either in config or URL parameter
2. groupID is not present either in config or URL parameter
3. app is running inside a portal (`isPortal:true` in Org properties)

All three conditions are met (only in Portals) when you go to app's item details page and click the thumbnail (see screenshot)
![image](https://cloud.githubusercontent.com/assets/2959186/12017327/20a079e2-ad7b-11e5-9740-427c02359975.png)

After we remove the static preview feature and associated code, when users try to preview the app by clicking the thumbnail in the app's details page, they will now see an "Group does not exist or is inaccessible." error message (only in Portals). 
This is the same behavior we see on devext when you directly access this app http://localgovdev.mapsdevext.arcgis.com/apps/PublicGallery/index.html  

In ArcGIS Online, the live preview will work as the configured default group will always be available.

Please let us know if this is in line with your expectations.

**Comment by allisonmuise** [comment]
Yes, This is the expectation. Portal 10.4 and forward will handle this better, and this change will bring this app in line with other AGOL templates.

**Comment by allisonmuise** [comment]
verified
