### ISSUE TITLE
Redesign UI to allow for display of media, attachments and related records in a panel

### ISSUE THREAD

**Issue by MikeMillerGIS** [Esri/crowdsource-manager#86]
When a user selects an image, the record it reviewed and all attachments and hyperlinked items are loaded into a panel for display

**Comment by MikeMillerGIS** [comment]
![image](https://cloud.githubusercontent.com/assets/2707285/10542482/6eeb4268-73e6-11e5-963f-b995791d4a6c.png)

**Comment by allisonmuise** [comment]
@MikeMillerGIS : 
Can you add a bit more information about what you're looking for? Manager already lets users open & download attachments. They show up on the 'Report' view under the popup content. I'm not sure what you mean by hyperlinked items?

**Comment by MikeMillerGIS** [comment]
Thoughts on a mock up
![image](https://cloud.githubusercontent.com/assets/2707285/10643838/072e29c2-77f3-11e5-97a9-b1863c73d8b8.png)

**Comment by MikeMillerGIS** [comment]
Pop up will be defined in the layer in the pop up configuration
Media is defined in the pop up as well as attachments which are web viewable(images)
Relates are related records

A tab with more than one record can display the records in a scrollable list or in a single record per page view(global setting on app)

Option to edit related records if related record is editable.  Edit button is shown next to pop up to show attribute inspection

**Comment by allisonmuise** [comment]
http://developers.arcgis.com/javascript/samples/ed_toolbar/

**Comment by allisonmuise** [comment]
This issue has been split into #96, #97 #98 #99 #100
