### ISSUE TITLE
Present list of filters per layer

### ISSUE THREAD

**Issue by MikeMillerGIS** [Esri/crowdsource-manager#87]
User requires the ability to filter a layer by a set of filters, both attribute and time.
![image](https://cloud.githubusercontent.com/assets/2707285/10643434/cee0a33a-77f0-11e5-8d4d-0b1914490e0b.png)

Thoughts:
Filters defined on the layer in the webmap
Filter need to be defined as an Ask For Value filter
Each one of these filters is then exposed in a ui in the app
![image](https://cloud.githubusercontent.com/assets/2707285/10643454/ef34cbfc-77f0-11e5-8b05-2c21c6a96663.png)

For time slider, the layer will have to have time enabled(property of the layer in the service)

**Comment by allisonmuise** [comment]
Split into #98 and #99
