### ISSUE TITLE
update boilerplate to resolve CORS issues in Portal

### ISSUE THREAD

**Issue by allisonmuise** [Esri/crowdsource-manager#91]
https://devtopia.esri.com/WebGIS/arcgis-portal-app-templates/issues/959

**Comment by CTLocalGovTeam** [comment]
@allisonmuise 
Can you please provide more information on CORS issues you see in Portal.

**Comment by allisonmuise** [comment]
This issue should be resolved by updating to the latest boilerplate. This has already been implemented for Basic Viewer. I don't have specific repro steps for this issue.

**Comment by allisonmuise** [comment]
verified
