### ISSUE TITLE
Add URL parameter for currently selected feature

### ISSUE THREAD

**Issue by allisonmuise** [Esri/crowdsource-manager#92]
use case:
GeoEvent sends message saying that report has been received/assigned. Message contains link to FEATURE in Manager so that, once in the app, user doesn't need to search for the feature.

This may mean that the map/layer, and feature id need to be stored somehow.

**Comment by CTLocalGovTeam** [comment]
@allisonmuise 

1. When multiple features are selected, the last feature that was selected, will be reflected in the URL. Correct?
2. Do we also need to populate the URL with the map extent? or just zoom to that feature?
3. When a time-aware layer is used, and the time extent is changed, do we also need to reflect this in the URL? This will be required in cases where a feature may not lie in the initial time extent.
In cases where the feature may no longer be available in the map (may be due to deletion), 
we can display a configurable message "The feature (id) could not be found". However, the map and layer will load as per URL parameters. Correct?
4. When the layer is no longer available in the webmap, or the webmap is no longer available in the group, then the app will go in to initial load state with disabled items and an error message is displayed, "Could not find map {name}"

**Comment by allisonmuise** [comment]
>Thus when user copies/shares the URL and opens it, the app will load the map/layer and zoom to that feature. Please let us know if this is in line with your expectations.

I believe this will work. The end goal is that users who have paired this application up with GeoEvent Server will be able to generate an email or text message with a constructed URL that will load the app directly to a specific report. The map id and layer id will need to be hard-coded in advance, I imagine, but this should fulfill that requirement.

>When multiple features are selected, the last feature that was selected, will be reflected in the URL. Correct?

Correct

>Do we also need to populate the URL with the map extent? or just zoom to that feature?

Zoom to the feature is preferred

>In cases where the feature may no longer be available in the map (may be due to deletion), we can display a configurable message "The feature (id) could not be found". However, the map and layer will load as per URL parameters. Correct?

Correct. I suggest a message that details potential reasons why the feature was not found. For example 'The feature (id) could not be found. The feature may be hidden by filters or it may have been deleted.'

>When the layer is no longer available in the webmap, or the webmap is no longer available in the group, then the app will go in to initial load state with disabled items and an error message is displayed, "Could not find map {name}"

Correct

**Comment by CTLocalGovTeam** [comment]
@allisonmuise 
When a time-aware layer is used, and the time extent is changed, do we also need to reflect this (starttime, endtime) in the URL? This may be required in cases where a feature may not lie in the initial time extent.

**Comment by allisonmuise** [comment]
@CTLocalGovTeam : Let's discuss this on the call this morning

**Comment by allisonmuise** [comment]
@CTLocalGovTeam : After further thought, we are going to defer this change. No work required at this time.

**Comment by allisonmuise** [comment]
@CTLocalGovTeam : Reading over this conversation, I feel like it is getting more complicated than necessary. The requirement isn't to have the app generate URLs that can be shared. We just need the app to recognize a series of URL parameters that dictate which map, layer, and feature should be selected when the app opens. 

The user need is as follows: Users are creating scripts that generate emails when new reports come in. In the email, they want to include a link that will directly open the referenced report, rather then always being directed to the top level of the app. The script can build the URL; the app just needs to recognize it.

In regards to the questions about features that are inaccessible due to filters or deletion: If the referenced map, layer, or feature cannot be displayed: load the app and present a message that says that the requested feature cannot be found.

The application does not need to update as the user navigates through different features, layers and maps, or as they apply filters.

**Comment by walzjc** [comment]
Is there a work around for this issue? If not, is there an approximate date on when this issue will be fixed?

**Comment by allisonmuise** [comment]
@walzjc we are currently evaluating this enhancement for inclusion in a release later this year.

**Comment by Fish4Food** [comment]
Would this enhancement be similar to the URL Parameters for esri's  Web AppBuilder apps? Really need and am looking for to this functionality!  We do not use GeoEvent Processor, however, I've developed scripts that run on a schedule to look for updates. I'd like to generate useful links for staff that can click on the issue link directly from the email - that would open and zoom to the issue in the Manager app. Right now I'm doing this but using WAB apps for the Manager portion instead, in part due to this limitation.

**Comment by allisonmuise** [comment]
@Fish4Food : Yep, that's the plan.

**Comment by CTLocalGovTeam** [comment]
@allisonmuise,

While analysing this functionality we came across following questions which are listed below

> We just need the app to recognize a series of URL parameters that dictate which map, layer, and feature should be selected when the app opens.

What would be the name of the parameter in which map, layer & feature information would be stored? We are planning to implement webmapid, featurelayer & selectedfeature. Following are the details of the expected value in each of the parameters.

1. webmapid: It would contain the webmap ID
2. featurelayer: It would contain the name of the  feature layer
3. selectedfeature: It would contain the objectID of the feature

> In regards to the questions about features that are inaccessible due to filters or deletion: If the referenced map, layer, or feature cannot be displayed: load the app and present a message that says that the requested feature cannot be found.

Following are the cases we could think about for implementing this functionality.


![image](https://user-images.githubusercontent.com/2959186/30808266-05f7091c-a21b-11e7-9629-25f894b51ccb.png)

![image](https://user-images.githubusercontent.com/2959186/30808326-4ae4819e-a21b-11e7-9446-2fe6118ff2b9.png)


Please confirm?




--Pratik Gohil

**Comment by allisonmuise** [comment]
For the parameter names, let's use webmap, layer, and oid

For the cases: 
- numbers 1, 3, 5, 6, 7, 8 are clear and I agree
- number 2: Could this open the app to the map & layer?
- number 4: Could this open the app to the map (& layer if there is only 1)

**Comment by CTLocalGovTeam** [comment]
@allisonmuise,

> number 2: Could this open the app to the map & layer?

Yes.

> number 4: Could this open the app to the map (& layer if there is only 1)

From this, we understand that in this case, we should display the only single layer that is available in that web map. Hence, the layer name present in the parameter and the one that we display would not be same. Please confirm? If Yes, we could implement it.


--Pratik Gohil

**Comment by allisonmuise** [comment]
@CTLocalGovTeam I think we are on the same page....Basically, the user experience would be the same as if they selected a map from the map selection panel

The overall goal of these two cases being to get the user as close as we can to the feature they are trying to find before we show the message that we can't find the feature.

**Comment by allisonmuise** [comment]
verified

**Comment by walzjc** [comment]
What is the correct syntax for the URL parameter to select and zoom to a feature?

**Comment by allisonmuise** [comment]
@walzjc We have added this info to the documentation for sending emails: http://solutions.arcgis.com/local-government/help/crowdsource-manager/get-started/email-notification/

In general it is appURL&webmap=mapGUID&layer=layerID&oid=OIDvalue, but I suggest checking out the section at the end of that help topic for more info on what, exactly, the app is expecting for those values.

**Comment by walzjc** [comment]
When using the URL parameters, if you go in to edit the record and click to change one of the drop down attributes it does not change. You have to click in the drop down list a second time in order for the change to hold. It works fine if you don't use the URL parameters. Is this a bug?

**Comment by allisonmuise** [comment]
@walzjc I am unable to reproduce this behavior in any browsers. I suggest contacting Esri Support Services so they can identify the source of the issue and log any necessary bugs/enh.
