### ISSUE TITLE
Expand app header across full width of app

### ISSUE THREAD

**Issue by allisonmuise** [Esri/crowdsource-manager#95]
App header is currently broken into  two sections: one with the app title & logo and one with the title of the currently selected layer and the other widget icons.

App header should contain the logo in the left corner followed by the app title, and the widgets on the right side. (like all our other apps)

Layer title will move to immediately above the table.

**Comment by CTLocalGovTeam** [comment]
@allisonmuise 
The styling specs recommends that 'Search will open to the left'. 

![image](https://cloud.githubusercontent.com/assets/2959186/12817220/ea18d60c-cb76-11e5-991c-eceb39a64d55.png)

Whereas current implementation is a box that opens as shown below

![image](https://cloud.githubusercontent.com/assets/2959186/12817254/33f37020-cb77-11e5-85c4-d836a5ffbdff.png)

Do we need to modify this as per styling recommendation to slide and open to the left?

**Comment by allisonmuise** [comment]
@CTLocalGovTeam :The current search that drops down is fine.

**Comment by allisonmuise** [comment]
verified
