### ISSUE TITLE
Update table record/map feature selection behavior

### ISSUE THREAD

**Issue by allisonmuise** [Esri/crowdsource-manager#97]
Remove concept of 'active vs selected' features.

- Clicking/tapping a record in the table selects that table record and the corresponding map feature.
- Clicking/tapping another record switches the selection to that record/feature
- CTRL+Click or tap-and-hold on another record/feature adds to the selection

When a single record/feature is selected, display the information for that feature in the info pod.
When multiple records/features are selected, switch the details panel to the popup details tab and enter editing mode ( #101 )

**Comment by CTLocalGovTeam** [comment]
@allisonmuise 

When multiple features are selected, 
* CTRL-click on a selected feature will unselect it. 
* If user single-clicks on a selected feature(from selected set), only that feature will remain selected and other selections will be lost.
* If user single-clicks a feature that is not selected, only that feature will remain selected and other selections will be lost.    

Is this ok?

On tablets, users may find it difficult to tap-hold each feature to multi-select. How about when user does a tap-hold, the app goes into 'multi-select mode' and then subsequent taps select/deselect features. The only way to come out of 'multi-select mode' is to deselect all by tapping them again once one-by-one. Please let us know your thoughts on this.

**Comment by allisonmuise** [comment]
@CTLocalGovTeam : On second thought - there's no  current need to do multiple selections on tablets, so let's not worry about this for this release. Just Shift/ctrl click on desktops with the behaviors you've described above..

**Comment by allisonmuise** [comment]
verified
